### ISSUE TITLE
9.2.3 broke `sql-sync`

### ISSUE THREAD

**Issue by rodrigoaguilera** [drush-ops/drush#3497] opened 2018-04-04 06:45 UTC
I'm facing a similar issue to this one 
https://github.com/drush-ops/drush/issues/3417

Trying to run 
drush --yes --root=/var/www/web sql-sync @web.stagelocal @self

You will destroy data in web_dev and replace with data from web_stage.
Do you really want to continue?: yes.                                       
[notice] Starting to dump database on source.
[success] Database dump saved to auto.gz 
[notice] Starting to import dump file onto target database.
[error]  File(s) not found: auto.gz
[error]  Failed to import auto.gz into target.

But now the filename gets to be auto.gz instead of DATABASENAME_DATE.gz

**Comment by weitzman** [comment] 2018-04-04 09:44
I think this is a duplicate of the issue you linked to. It’s going to happen whenever you have a new release of drush on one side of sql sync and an old release on the other.

**Closed by weitzman** 2018-04-04 09:44 UTC

**Comment by rodrigoaguilera** [comment] 2018-04-04 09:50
@weitzman 
Thank you. I did not checked that

From your comment can be guessed that any mismatch of drush versions will break the site when is indeed when one of the versions is older than 9.2.1.

**Comment by weitzman** [comment] 2018-04-04 10:50
Correct. thanks for clarifying
