### ISSUE TITLE
Drush relies on composer.json to find site aliases, but doesn't complain when that has a problem

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3955] opened 2019-03-01 10:34 UTC
**Describe the bug**

Drush appears to rely on the contents of the composer.json file to discover site aliases in drush/sites/, but doesn't show any error message if there's a problem there.

**To Reproduce**

1. Create some alias files in drush/sites/. 
2. Check they are shown with `drush sa`
3. Break the composer.json file in some way -- add some invalid JSON somewhere, for example
4. Run 'drush sa' again.

**Expected behavior**

An error message.

I left a TODO in my composer.json while I was in the middle of something else, because I was confident I would not be doing any Composer-based operations. I was then confused when Drush site aliases suddenly stopped working!

**Actual behavior**

No error message and no aliases found:

```
drush sa -vvv
 [preflight] Config paths: /Users/joachim/Sites/project/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /Users/joachim/Sites/project/vendor/drush/drush/drush/sites
 [preflight] Commandfile search paths: /Users/joachim/Sites/project/vendor/drush/drush/src
 [bootstrap] Starting bootstrap to none [1.22 sec, 3.32 MB]
 [bootstrap] Drush bootstrap phase 0 [1.22 sec, 3.32 MB]
 [bootstrap] Try to validate bootstrap phase 0 [1.22 sec, 3.32 MB]
 [success] No site aliases found. [1.23 sec, 3.39 MB]
```

**Workaround**

Don't break your composer.json!

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  |  9.5.2
| Drupal version? | 8.x
| PHP version     | 7.2
| OS?             | Mac

**Comment by weitzman** [comment] 2019-03-01 11:16
dupe of #3922

**Closed by weitzman** 2019-03-01 11:16 UTC
