### ISSUE TITLE
pm-enable does not validate against module dependency versions in .info.yml 

### ISSUE THREAD

**Issue by laughingman77** [drush-ops/drush#3736] opened 2018-10-16 03:20 UTC
**Describe the bug**
If a version of a module dependency version is declared in .info.yml, the version argument is ignored. This works correctly in the admin interface, but I could still drush pm-enable <module> when it should have failed.

**To Reproduce**
Install latest webform (5.0-rc22)

Added the following to <my_module>.info.yml:

> dependencies:
>   \- webform:webform (>= 5.0-rc23)

Try to install your module

**Expected behavior**
Unable to install the module through the admin interface or with drush.

**Actual behavior**
/admin/extend disabled the install checkbox and correctly showed:

> Requires: Webform (>= 5.0-rc23) (incompatible with version 8.x-5.0-rc22)

CLI pm-enable did not block the module form being enabled:

`$ ./vendor/bin/drush pm-enable <my_module>
 [success] Successfully enabled: <my_module>`

**Workaround**
Possibly implement hook_requirements()

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4.0
| Drupal version? | 8.6.1
| PHP version     | 7.1
| OS?             | Linux

**Additional information**
This came up in a ticket for marketing_cloud: https://www.drupal.org/project/marketing_cloud/issues/3006866#comment-12816195

I also tested this with major minor versions, to see if the issue was with RC versioning, and had the same results

**Comment by weitzman** [comment] 2019-01-30 13:44
Dupe of #3669

**Closed by weitzman** 2019-01-30 13:44 UTC
