### ISSUE TITLE
Drush 9.2.0 - multisite - drush cr removes site specific modules from moduleHandler service

### ISSUE THREAD

**Issue by Paladyn85** [drush-ops/drush#3466] opened 2018-03-14 08:31 UTC
Hi!

I am using Drupal 8.4.5 with Acquia Lightning 3.1.0.
Site updates are managed by Composer.
I am using Drush 9.2.0.

I have problem with running site specific modules. They are visible and installed in Drupal.
After clearing cache (drush cr) they disappear from moduleHandler service. All modules shared between sites are visible. Same modules are working alright when moved to shared modules folder.

drush pm-uninstall module_name
and then
drush en module_name
on one of site specific modules reactivates all other missing modules. But still they disappear after cache cr.

Clearing cache from /admin/config/development/performance works well and doesn't remove any installed modules.

I have drush installed globally on Drupal VM.

Drush cr --debug, doesn't return any error.

Best regards!
Paladyn85

**Comment by weitzman** [comment] 2018-03-22 23:15
Dupe of #3391

**Closed by weitzman** 2018-03-22 23:15 UTC
