### ISSUE TITLE
Fatal error in LocaleCommands, Drush 9.5.1/ Drupal 8.7.x

### ISSUE THREAD

**Issue by quietone1** [drush-ops/drush#3745] opened 2018-10-17 01:25 UTC
Installed drush with `composer require drush/drush` which succeeded. Then on entering `drush` I got the (abbreviated) error below. Then I checked the version
```
v@dev0 {/opt/sites/d8} (8.7.x)$ drush --version
Drush Commandline Tool 9.5.1
```
Reverting to drush 9.4 and drush is working as expected. 

I did check for this in the issue but didn't spot anything similar but admittedly it was a brief look.
```
v@dev0 {/opt/sites/d8} (8.7.x)$ drush
 [error]  TypeError: Argument 1 passed to Drush\Drupal\Commands\core\LocaleCommands::__construct() must implement interface Drupal\Core\Language\L
anguageManagerInterface, instance of Drupal\Core\Extension\ModuleHandler given, called in /opt/sites/d8/core/lib/Drupal/Component/DependencyInject
ion/Container.php on line 266 in Drush\Drupal\Commands\core\LocaleCommands->__construct() (line 59 of /opt/sites/d8/vendor/drush/drush/src/Drupal/
Commands/core/LocaleCommands.php) #0 /opt/sites/d8/core/lib/Drupal/Component/DependencyInjection/Container.php(266): Drush\Drupal\Commands\core\Lo
caleCommands->__construct(Object(Drupal\Core\Extension\ModuleHandler), Object(Drupal\Core\State\State))                                           
#1 /opt/sites/d8/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(A
rray, 'locale.commands')                                                                                                                          
#2 /opt/sites/d8/core/lib/Drupal/Component/DependencyInjection/Container.php(480): Drupal\Component\DependencyInjection\Container->get('locale.com
mands', 1)                                                                                                                                        
#3 /opt/sites/d8/core/lib/Drupal/Component/DependencyInjection/Container.php(319): Drupal\Component\DependencyInjection\Container->resolveServices
AndParameters(Array)                                                                                                                              
#4 /opt/sites/d8/core/lib/Drupal/Component/DependencyInjection/Container.php(171): Drupal\Component\DependencyInjection\Container->createService(A
rray, 'drush.command.s...')                                                                                                                       
#5 /opt/sites/d8/vendor/drush/drush/src/Boot/DrupalBoot8.php(230): Drupal\Component\DependencyInjection\Container->get('drush.command.s...')
#6 /opt/sites/d8/vendor/drush/drush/src/Boot/BootstrapManager.php(295): Drush\Boot\DrupalBoot8->bootstrapDrupalFull(NULL)
#7 /opt/sites/d8/vendor/drush/drush/src/Boot/BootstrapManager.php(504): Drush\Boot\BootstrapManager->doBootstrap(5, 6, NULL)
#8 /opt/sites/d8/vendor/drush/drush/src/Boot/BootstrapManager.php(438): Drush\Boot\BootstrapManager->bootstrapMax(6)
#9 /opt/sites/d8/vendor/drush/drush/src/Boot/BootstrapManager.php(407): Drush\Boot\BootstrapManager->bootstrapToPhaseIndex(-2, Object(Consolidatio
n\AnnotatedCommand\AnnotationData))             
`` `

**Comment by weitzman** [comment] 2018-11-01 12:38
Dupe of #3753. Try a `drush cr` and report there about how it went.

**Closed by weitzman** 2018-11-01 12:38 UTC
