### ISSUE TITLE
Upgrade from drupal8 beta 15 to beta 16 results in error

### ISSUE THREAD

**Issue by jhmnieuwenhuis** [drush-ops/drush#1665] opened 2015-10-05 18:33 UTC
I upgraded from drupal 8 beta 15 to beta 16.
When using drush 8 up drupal I get an error.
The update of drupal is done, I have to do the database update in Drupal.

The drush version = 8.0-dev

The error occurs after the message Finished performing updates. 
:
Do you wish to run all pending updates? (y/n): y
Performing system_update_8006                                        [ok]
Performing system_update_8007                                        [ok]
Performing system_update_8008                                        [ok]
Performing system_update_8009                                        [ok]
Performing system_update_8010                                        [ok]
Performing views_update_8002                                         [ok]
Performing block_content_update_8002                                 [ok]
Performing block_update_8003                                         [ok]
Performing field_update_8001                                         [ok]
Performing system_update_8011                                        [ok]
Cache rebuild complete.                                              [ok]
Finished performing updates.                                         [ok]
PHP Fatal error:  Class 'Symfony\Component\HttpFoundation\Response' not found in /home/hn/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php on line 133
PHP Stack trace:
PHP   1. {main}() /home/hn/.composer/vendor/drush/drush/drush.php:0
PHP   2. drush_main() /home/hn/.composer/vendor/drush/drush/drush.php:11
PHP   3. Drush\Boot\DrupalBoot8->terminate() /home/hn/.composer/vendor/drush/drush/drush.php:79
Drush command terminated abnormally due to an unrecoverable error.   [error]
Error: Class 'Symfony\Component\HttpFoundation\Response' not found in
/home/hn/.composer/vendor/drush/drush/lib/Drush/Boot/DrupalBoot8.php,
line 133

**Comment by jibran** [comment] 2015-10-05 19:27
Duplicate of #1602 PR is in #1603.

**Comment by greg-1-anderson** [comment] 2015-10-06 15:46
Closing as duplicate.

**Closed by greg-1-anderson** 2015-10-06 15:46 UTC
