### ISSUE TITLE
Options with bool(false) default value aren't a real flag

### ISSUE THREAD

**Issue by Sweetchuck** [drush-ops/drush#3779] opened 2018-11-10 11:11 UTC
**Describe the bug**

Default value of an option which is defined like this `$options = ['a' => FALSE]` cannot be overridden from drush.yml.

I think **all** the options has to be overridable from `drush.yml`.

Here are the descriptions of the meanings of the default values:
https://github.com/consolidation/annotated-command#option-default-values

**To Reproduce**

```php
<?php

class FooCommands {
  /**
   * @command foo:bar
   */
  public function (
    $options = [
      'a' => FALSE,
    ]
  ) {
    var_dump($options['a']);
  }

}
```

Content of `drush.yml`
```yaml
command:
  foo:
    bar:
      options:
       a: true
```

Run `drush foo:bar`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush Commandline Tool 9.5.2
| Drupal version? | 8.6 but not relevant
| PHP version?    | 7.2.11 but not relevant
| OS?             | Linux

### Use case

I would like run a Drush command like this `drush site:install` with the following `drush.yml` file:
```yaml
command:
  site:
    install:
      options:
        existing-config: true
```
But the `command.site.install.options.existing-config` is totally ignored.
Also the `DRUSH_OPTIONS_EXISTING_CONFIG='true' drush site-install --existing-config` command doesn't work.
So I have to add it to CLI command, like this:
`drush site-install --existing-config`.

## List of commands

1. \Drush\Commands\OptionsCommands::optionsetProcBuild
1. \Drush\Commands\OptionsCommands::optionsetGetEditor
1. \Drush\Commands\config\ConfigPullCommands::pull
1. \Drush\Commands\core\CacheCommands::set
1. \Drush\Commands\core\DrupalDirectoryCommands::drupalDirectory
1. \Drush\Commands\core\DrupliconCommands::optionset
1. \Drush\Commands\core\InitCommands::initializeDrush
1. \Drush\Commands\core\RunserverCommands::runserver
1. \Drush\Commands\core\SiteInstallCommands::install
1. \Drush\Commands\core\UpdateDBCommands::updatedb
1. \Drush\Commands\help\HelpCommands::help
1. \Drush\Commands\help\ListCommands::helpList
1. \Drush\Commands\sql\SqlCommands::conf
1. \Drush\Commands\sql\SqlCommands::query
1. \Drush\Commands\sql\SqlCommands::dump
1. \Drush\Commands\sql\SqlSyncCommands::sqlsync

**Comment by greg-1-anderson** [comment] 2018-11-10 14:39
Duplicate of https://github.com/drush-ops/drush/issues/2956

**Closed by greg-1-anderson** 2018-11-10 14:39 UTC
