### ISSUE TITLE
Make handleMissingSourceRows from drush migrate PRE_IMPORT event, configurable on import

### ISSUE THREAD

**Issue by timlie** [drush-ops/drush#4743] opened 2021-04-29 20:00 UTC
**Is your feature request related to a problem? Please describe.**
When coming from migrate_run 8.x-1.0-alpha4 with drush 8, I noticed my migrations took a lot longer (twice the time from before) when I started using drush 10.3.4
After debugging its clear to me that this is triggered by the migrate PRE_IMPORT event used in the MigrateExecutable class from drush. It executes the handleMissingSourceRows function. Although I see the great use of this function, it causes a lot of overhead when not needed.

**Describe the solution you'd like**
Ideally it should be possible to make it configurable, like --delete

**Comment by vaish** [comment] 2021-05-07 10:08
Most of the overhead described here is caused by the bug reported in #4750. Once that bug is fixed (patch coming soon) overhead will be significantly smaller. However, I think that it still makes sense to make `handleMissingSourceRows` feature optional.

**Comment by claudiu-cristea** [comment] 2021-06-19 09:22
@timlie, #4750 is fixed now. Could you test again with the 10.x branch to see if it fixes the overhead?

**Comment by claudiu-cristea** [comment] 2021-09-05 21:14
No reply for a long time. I guess it was fixed by #4750. Feel free to reopen if not.

**Closed by claudiu-cristea** 2021-09-05 21:14 UTC
Labels: type-bug, area-migrate
