### ISSUE TITLE
~/.my.cnf file prevents using drush

### ISSUE THREAD

**Issue by deajan** [drush-ops/drush#2183] opened 2016-05-12 20:19 UTC
Hello,

As root, if I happen to have a .my.cnf file with a password directive, mysql client as well as mysqldump execute well without any other parameters like -u or -p but drush will fail with:

```
The drush command 'pm-update' could not be executed.                                                                                                                               [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                                                       [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the
URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.
```

Anything I am missing here ?
Regards,
Ozy.

**Comment by weitzman** [comment] 2016-05-12 22:13
This is by design. It was a popular feature request. Feel free to suggest
docs changes or better error messages.

**Comment by deajan** [comment] 2016-05-13 07:01
I don't understand why. Could you explain why this has been asked please ?

Anyway, it would be nice to have a cmdline switch that enables the use of .my.cnf file password again.
Then, an error message like the following would be great:
```
The drush command 'pm-update' could not be executed.                                                                                                                               [error]
Drush was not able to start (bootstrap) the Drupal database.                                                                                                                       [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a working database setup by specifying the
URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for details.
 * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See http://drupal.org/node/1428638 for details.
 * connect the database when a [my.cnf] file is present. Remove the file or use the --usecnf parameter on the command line.
```

**Comment by BartVB** [comment] 2016-06-13 17:34
The user that's in my .my.cnf doesn't have access to the Drupal database which causes drush to fail silently. I.e. `drush cc` only shows me 'cancel/drush/registry' as options. It doesn't mention that it does this because Drush can't connect to the database.

Is there a way to make Drush override the .my.cnf settings? The only option that I see currently is removing my credentials from .my.cnf but I use those a lot. Or I could change the permissions of the user in .my.cnf but that doesn't sound like a great solution either.

@deajan's error message would have saved me quite a bit if debugging.

**Comment by weitzman** [comment] 2016-06-13 17:37
There not a way right now to bypass a my.cnf

**Comment by BartVB** [comment] 2016-06-14 06:49
There is in MySQL:
http://dev.mysql.com/doc/refman/5.7/en/option-file-options.html
 `--defaults-extra-file` = What Drush uses now. This is read before ~/.my.cnf
 `--defaults-file` = The only options file that the MySQL client uses. ~/.my.cnf is ignored. This also results in a more predictable environment for Drush.
`--login-path` = A file with login credentials/server information. This seems to be a perfect match for Drush? The documentation doesn't specify but my guess is that this also ignores ~/.my.cnf

**Comment by meglio** [comment] 2016-07-04 07:40
I encountered this problem as well and had to remove `.my.cnf` file. This is counter-intuitive.

**Proposition**: make drush output that it was using `.my.cnf` when connecting to the database.

**Comment by weitzman** [comment] 2016-07-04 12:03
Drush doesn't know. It's the MySQL Clint that drush calls that would know
and there is now way to ask it.

**Comment by meglio** [comment] 2016-07-04 12:07
I'm a bit confused. When Drush uses default credentials that mysql can read from some configuration file - is one case. When Drush is using connection settings from Drupal's settings.php file - is another case. No?

**Comment by deajan** [comment] 2016-07-06 18:28
@weitzman Then how about having drush check if a password directive exists in ~/.my.cnf ?

**Comment by weitzman** [comment] 2016-07-06 21:46
Mysql checks a bunch of places and doesn't easily publish exactly where those are. I thin a solution here, if desired, would be to optionally change how we pass creds to mysql so that our creds override anything in my.cnf. Thats how it used to work, in fact. We started honoring my.cnf at same time we started never showing creds on the command line. Not sure if we can still do that and optionally not honor my.cnf

**Comment by deajan** [comment] 2016-07-08 09:06
Agreed, it's a workaround solution.
As of my understandings, if no my.cnf password directive exists, drush gets it's credentials from settings.php.

What about a basic solution like a cmdline switch, let's say --no-mycnf ?

**Comment by weitzman** [comment] 2016-08-06 19:44
Drush is always sending the same creds - the ones form settings.php. Its just that the mysql client disregards those when a my.cnf is present.

**Comment by deajan** [comment] 2016-08-18 09:14
I'm pretty sure drush makes calls to mysql with -u <user> where <user> comes from settings.php.
Using -u and having a my.cnf file mixes the database user with a database password configured for a linux user.

How about a --current-user switch that removes the -u part, leaving mysql to use the current linux user together with the my.cnf password ?

**Comment by bdanin** [comment] 2016-10-03 22:15
How come this is still an open issue? We need the ability to switch to a current user defined in settings.php and bypass my.cnf when running drush commands. This is causing problems that never existed prior to Drush 8.x, making drush rather ineffective.

**Comment by weitzman** [comment] 2016-10-04 19:29
- Its an open issue because no-one has submitted a PR to fix it. 
- I suggest you take an extra minute to re-word your comments in an open source project like this. Your current wording suggests that you feel entitled to a fix for this issue. [Thats not how it works](http://jeremyckahn.github.io/blog/2014/10/19/open-source-does-not-mean-free-labor/).

**Comment by reinier-vegter** [comment] 2016-10-12 14:17
Ok, this annoyed me very much since I'm using Drush 8.x for https://www.drupal.org/project/flightcontrol , and it rendered all of our own environments failing.

Hereby a fix + PR.

Regards,
Reinier

BTW, thanks for all the effort put into Drush folks!

**Comment by deajan** [comment] 2016-10-14 06:05
Now you deserve a cookie !
I tried to manually apply this your patch in order to test, but phar doesn't seem happy because it broke the file signature.
I'm not familiar with phar, can please someone tell me how to use "not phared" version ?

**Comment by reinier-vegter** [comment] 2016-10-14 07:02
Hi @deajan ,
you might clone the git repo (8.x branch) and go from there.
A 'composer install' will do then (also check the drush script for proper filemode).

BTW, discussion about the PR is here: https://github.com/drush-ops/drush/pull/2387

**Comment by deajan** [comment] 2016-10-14 12:11
@reinier-vegter Tested your PR. Works okay for me and resolves the issue, both when my.cnf is present and when it's not.
Posting this here instead of #2387 in order to keep this issue up to date.
Thanks man !

**Comment by weitzman** [comment] 2017-01-19 20:49
Have folks here tried adding --extra=--no-defaults to your drush command? That should bypass the reading of mysql option files like my.cnf. At least thats how I read the docs.

**Comment by dylantack** [comment] 2017-01-20 01:33
`--extra` isn't available on most drush commands, so that wasn't an option for me.

The workaround I found was temporarily overwriting `$HOME`, for example:
`HOME=. drush -y site-install minimal`

The could have bad side-effects for some people, but it worked in my situation.

**Comment by samking** [comment] 2017-03-12 09:06
I just stumbled onto this issue as well (on Drush 8.1.10), but my `~/.mylogin.cnf` file triggered it instead of a `~/.my.cnf`.  This isn't a big issue for me since I can just remove the mylogin.cnf, but I just wanted to let you all know for posterity in case anyone else stumbles on this thread or in case folks didn't know that the issue was bigger than just my.cnf.

Thanks!

**Comment by mglaman** [comment] 2017-03-13 20:33
If you're working with Travis, I had to run the following. Chose `before_install`

```
  # Remove ~/travis/.my.cnf. Drush picks this up and ignores settings.local.php dburl for some reason.
  - rm ~travis/.my.cnf
```

https://github.com/mglaman/commerce-project-template/commit/eccbb7f69a40a3ab6750b20c33323caea450a688

**Comment by weitzman** [comment] 2017-04-19 02:01
We changed behavior recently in master. Alas is too disruptive for 8.x

**Closed by weitzman** 2017-04-19 02:01 UTC

**Comment by deajan** [comment] 2017-04-19 06:55
@weitzman Would you mind quickly explaining the new behavior ? Thanks

**Comment by marcdelay** [comment] 2017-07-18 21:35
I have just spent a couple hours reading back through the history of this bug and back to the historical bugs on D.O. I'd Just like to point out that no one specifically "asked" for drush to read from my.cnf file over settings.php.

The ask was for drush to stop leaking credentials through logs, ps, bash history etc.

I agree that using option files is the best option and one that a lot of effort went into. I think the problem is that default/system wide cnf files should never take precedence over settings.php.  

Mainly the problem is that we have no idea what other things are going on on someone's server. (In my case our servers are deployed with ansible which uses auto-generates my.cnf files that are in no way connected to drupal.)

I think that if db credentials are found in settings.php then we need to use those credentials only as found in the patch submitted by @reinier-vegter. 

If no credentials are found in settings.php then feel free to let my.cnf take over.

**Comment by geerlingguy** [comment] 2017-08-08 02:40
Just posting this here for my and others' potential future Google queries:

Over in Drupal VM, when adding a test for Debian 9 support via a Docker container, I started running into an issue where, when `site-install`ing with `--db-url=mysql://drupal:drupal@127.0.0.1/drupal`, I would get a failure:

```
Access denied for user 'root'@'localhost'
```

The db-url has `drupal` for the username, so I (correctly) presumed the `root` account was coming from the root user's `~/.my.cnf` file.

The funny thing is, in every other OS I'm testing (Ubuntu 16/14, CentOS 6/7, Debian 8), I have not had an issue using the exact same setup. The .my.cnf file reads:

```
# Ansible managed
[client]
user="root"
password="root"
```

And stranger yet, when I simply switch `127.0.0.1` to `localhost`, Debian 9 is happy installing the site using `drupal`/`drupal` as passed in through the Drush `site-install` option. 

It seems like it would make more sense if it _always_ failed trying `root` whether using localhost or 127.0.0.1. In Drupal VM's case, it's listening on all interfaces (`bind-address = 0.0.0.0`) and also via Unix socket (`socket = /var/run/mysqld/mysqld.sock`).

Maybe MySQL itself has some weird undocumented limitation when using IP vs. socket with what order of variable precedence it uses?

**Comment by donquixote** [comment] 2018-06-11 23:54
@weitzman 

> We changed behavior recently in master. Alas is too disruptive for 8.x

There should at least be a note in the help output.

Currently it says

> Drush was not able to start (bootstrap) the Drupal database.
> Hint: This may occur when Drush is trying to:
>  * bootstrap a site that has not been installed or does not have a configured database. In this case you can select another site with a
> working database setup by specifying the URI to use with the --uri parameter on the command line. See `drush topic docs-aliases` for
> details.
>  * connect the database through a socket. The socket file may be wrong or the php-cli may have no access to it in a jailed shell. See
> http://drupal.org/node/1428638 for details.

So, perhaps there could be an additional bullet point like

Drush is trying to:
* ..
* ..
* connect to the database through a cli command using the --defaults-extra-file parameter to pass credentials through a tmp file. This method can break if other credentials are specified in a ~/.my.cnf file in your home directory. You may have to delete or rename the local ~/.my.cnf file.

**Comment by donquixote** [comment] 2018-06-11 23:56
@weitzman, @deajan

> We changed behavior recently in master. Alas is too disruptive for 8.x

> @weitzman Would you mind quickly explaining the new behavior ? Thanks

This would be nice indeed.
Do you have a link to a commit or to a PR?

Perhaps there is a simpler solution that can be applied to 8.x.
(until then, updating the help text would be a good idea)

**Comment by donquixote** [comment] 2018-06-12 00:02
PR: https://github.com/drush-ops/drush/pull/3581
