### ISSUE TITLE
Drush fails to bootstrap postgresql database on non-local server if postgres not installed locally

### ISSUE THREAD

**Issue by AppreciateIT** [drush-ops/drush#2652] opened 2017-03-04 20:01 UTC
I've wasted several days figuring this out.  Although the site itself is functional, many drush commands won't work because drush can't communicate with the database.  The issue is that drush seems to use psql to stat the database, and if you didn't install Postgresql server on the local machine, psql is not installed.  Not sure if the same is true if using remote MySQL database.  This may be noticed especially when using a dockerized Drupal site as the virtual machines usually don't contain the database onboard.  This was discovered using a Nginx hosted dockerized Drupal 8.

**Comment by weitzman** [comment] 2017-03-05 04:56
Dupe of #1371

**Closed by weitzman** 2017-03-05 04:56 UTC
