### ISSUE TITLE
Since 7.0.0-alpha4, Drush don't pick up $options['uri'] when defined in sites/default/drushrc.php 

### ISSUE THREAD

**Issue by morvans** [drush-ops/drush#1231] opened 2015-03-05 09:33 UTC
I usually have a sites/default/drushrc.php which define 'uri' and 'sites-subdir' like this : 
```
<?php
$options['uri'] = 'http://172.17.42.1:3004';
$options['sites-subdir'] = 'default';
```
Since 7.0.0-alpha4, drush always use 'default' uri instead of what I define :
```
# drush uli
http://default/user/reset/1/1425547681/V1yYn-xPpn4pEngewPgRWye33OutL-K1GLmFsAhdcJw/login
```

After a quick git bisect of the log between 7.0.0-alpha3 and 7.0.0-alpha4 :

* 838a741715d0c6452830202dd6a9db293c9a4cae => Works
* c7ea4b1d8ee29b467b3233b320e779535a9d0b8f => PHP Exception
* 0d2eeb51e08bb9ba8ac038220cb13e644352d5fc => Doesn't work

**Comment by greg-1-anderson** [comment] 2015-03-06 17:57
This should be supported.

**Comment by weitzman** [comment] 2015-03-06 18:17
Dupe of #800

**Closed by weitzman** 2015-03-06 18:17 UTC
