### ISSUE TITLE
They have Removed conf_path() from core

### ISSUE THREAD

**Issue by sirsquall** [drush-ops/drush#1663] opened 2015-10-05 14:27 UTC
https://www.drupal.org/node/2573443

PHP Fatal error:  Call to undefined function conf_path() in /var/www/drupal/vendor/drush/drush/lib/Drush/Boot/DrupalBoot.php on line 388

I'm using : 
Drupal Version   : 8.0.0-beta16
Drush Version   :  8.0.0-beta14

**Comment by weitzman** [comment] 2015-10-05 14:29
Dupe of #1631. Please update drush when updating Drupal 8.

**Closed by weitzman** 2015-10-05 14:29 UTC
