### ISSUE TITLE
DrushCommands not found in ../search_api/src/Commands/SearchApiCommands.php on line 16

### ISSUE THREAD

**Issue by AltaGrade** [drush-ops/drush#3483] opened 2018-03-28 18:08 UTC
We are seeing the following error on one of our websites:

```
 PHP Fatal error:  Class 'Drush\Commands\DrushCommands' not found in /home/username/public_html/sites/all/modules/search_api/src/Commands/SearchApiCommands.php on line 16
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Class 'Drush\Commands\DrushCommands' not found in
/home/username/public_html/sites/all/modules/search_api/src/Commands/SearchApiCommands.php,
line 1
```

Drush Version  is 8.1.13

Would appreciate any recommendations on how to overcome this error. Thanks!

**Comment by weitzman** [comment] 2018-03-28 19:37
Likely a dupe of #3456

**Closed by weitzman** 2018-03-28 19:37 UTC
