### ISSUE TITLE
drush updb crashes badly when there's no DB server

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2813] opened 2017-06-15 14:53 UTC
```
$ drush updb
Error: Call to undefined function drupal_get_installed_schema_version() in drupal_load_updates() (line 80 of web/core/includes/install.inc).
Drush command terminated abnormally due to an unrecoverable error.    [error]
$ drush updb
The following updates are pending:
```

The only difference between the two commands is that MySQL had crashed.

The command should give a more graceful error message when the DB can't be found.

**Comment by weitzman** [comment] 2017-06-15 14:59
Dupe of several issues.

**Closed by weitzman** 2017-06-15 14:59 UTC
