### ISSUE TITLE
Enabling a module does not make its routes available

### ISSUE THREAD

**Issue by mikeryan776** [drush-ops/drush#1297] opened 2015-03-27 22:19 UTC
See https://www.drupal.org/node/2451665 - with this change, enabling a module through drush that defines a route does not make the route available, you need to do a drush cr afterwards. Would be nice if drush did the router rebuild.

**Comment by greg-1-anderson** [comment] 2015-03-30 16:40
Could someone please confirm that this issue is in fact solved now that #1303 has been merged?

**Comment by Berdir** [comment] 2015-03-30 20:25
Yes, this works, but drush si now shows an error, which I assume is related to the change there:

Argument 1 passed to Drupal\Core\DrupalKernel::terminate() must be an instance of Symfony\Component\HttpFoundation\Request, none given, called in                                 [notice]
/home/berdir/tools/drush/lib/Drush/Boot/DrupalBoot8.php on line 102 and defined DrupalKernel.php:548 [46.98 sec, 36.98 MB]
Argument 2 passed to Drupal\Core\DrupalKernel::terminate() must be an instance of Symfony\Component\HttpFoundation\Response, none given, called in                                [notice]
/home/berdir/tools/drush/lib/Drush/Boot/DrupalBoot8.php on line 102 and defined DrupalKernel.php:548 [46.98 sec, 36.98 MB]

**Comment by greg-1-anderson** [comment] 2015-03-30 20:49
I suspect that #1303 is unnecessary, and afb0ffa fixes this; however, I have not been able to test this yet, as I get the following when I try to enable a module via Drush:
```
$ drush en tracker
Argument 4 passed to Drupal\Core\Field\FieldTypePluginManager::__construct() must be an instance of Drupal\Core\TypedData\TypedDataManager, none given, called in /Users/ga/local/drupal/other-d8/drupal-8.0.x/sites/default/files/php/service_container/service_container_prod/f3c642b96884a132323220a4427d8e089a4c451f56943048e982da5183325c24.php
on line 5027 and defined FieldTypePluginManager.php:47
Undefined variable: typed_data_manager FieldTypePluginManager.php:51          

Fatal error: Class 'Drupal\Core\Routing\RouteBuilderIndicator' not found in /Users/ga/local/drupal/other-d8/drupal-8.0.x/sites/default/files/php/service_container/service_container_prod/f3c642b96884a132323220a4427d8e089a4c451f56943048e982da5183325c24.php on line 6086
```
Have not tried to track this down; perhaps I'll see if I get the same results using a different module.

**Comment by greg-1-anderson** [comment] 2015-03-30 20:58
Okay, my issue above seems to be sqlite-related; doing tests with mysql now.

**Closed** 2015-03-30 22:11 UTC

**Comment by greg-1-anderson** [comment] 2015-03-30 22:14
The root cause here was that Drush was creating the bootstrap object too frequently, so the $bootstrap variable returned by drush_preflight() became stale.  With d483730, the lookup of the $bootstrap object in #1303 is unnecessary, except in edge cases.  I left the global access in place, though, for reasons explained in #1303.
