### ISSUE TITLE
download drupal can't work

### ISSUE THREAD

**Issue by terao** [drush-ops/drush#2400] opened 2016-10-18 10:36 UTC
drush -y dl drupal-8 run , then Fatal error occurred on unbuntu16.4 and centOS7.2 .

This problem has occurred from 2 days ago

`
$ /usr/local/bin/drush -y dl drupal-8 --destination=/var/www --drupal-project-rename=html 
PHP Fatal error:  Uncaught RuntimeException: Your environment or operation system isn't supported in phar:///usr/local/bin/drush/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 phar:///usr/local/bin/drush/includes/environment.inc(641): Webmozart\PathUtil\Path::getHomeDirectory()
#1 phar:///usr/local/bin/drush/includes/preflight.inc(415): drush_server_home()
#2 phar:///usr/local/bin/drush/includes/preflight.inc(231): _drush_preflight_base_environment()
#3 phar:///usr/local/bin/drush/includes/preflight.inc(41): drush_preflight()
#4 phar:///usr/local/bin/drush/includes/startup.inc(458): drush_main()
#5 phar:///usr/local/bin/drush/includes/startup.inc(365): drush_run_main(false, '/', 'Phar detected. ...')
#6 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#7 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#8 {main}
  thrown in phar:///usr/local/bin/drush/vendor/webmozart/path-util/src/Path.php on line 257
Drush command terminated abnormally due to an unrecoverable error.       [error]
Error: Uncaught RuntimeException: Your environment or operation
system isn't supported in
phar:///usr/local/bin/drush/vendor/webmozart/path-util/src/Path.php:257
Stack trace:
#0 phar:///usr/local/bin/drush/includes/environment.inc(641):
Webmozart\PathUtil\Path::getHomeDirectory()
#1 phar:///usr/local/bin/drush/includes/preflight.inc(415):
drush_server_home()
#2 phar:///usr/local/bin/drush/includes/preflight.inc(231):
_drush_preflight_base_environment()
#3 phar:///usr/local/bin/drush/includes/preflight.inc(41):
drush_preflight()
#4 phar:///usr/local/bin/drush/includes/startup.inc(458):
drush_main()
#5 phar:///usr/local/bin/drush/includes/startup.inc(365):
drush_run_main(false, '/', 'Phar detected. ...')
#6 phar:///usr/local/bin/drush/drush(114): drush_startup(Array)
#7 /usr/local/bin/drush(10): require('phar:///usr/loc...')
#8 {main}
  thrown in
phar:///usr/local/bin/drush/vendor/webmozart/path-util/src/Path.php,
line 257

(exit code: 1)
`

**Comment by weitzman** [comment] 2016-10-19 09:28
Dupe of #2405. Please reply there.

**Closed by weitzman** 2016-10-19 09:28 UTC
