### ISSUE TITLE
sql-dump adds fail text to SQL

### ISSUE THREAD

**Issue by iainhouston** [drush-ops/drush#3305] opened 2018-01-13 07:34 UTC
The string "Connection to ...." (see below) is added to the SQL output; it will fail the subsequent importing of the SQL.
(`drush 9.0.0-rc2`)

```
$ drush @balive sql-dump > tmp.sql
tail tmp.sql
/*!40101 SET SQL_MODE=@OLD_SQL_MODE */;
/*!40014 SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS */;
/*!40014 SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS */;
/*!40101 SET CHARACTER_SET_CLIENT=@OLD_CHARACTER_SET_CLIENT */;
/*!40101 SET CHARACTER_SET_RESULTS=@OLD_CHARACTER_SET_RESULTS */;
/*!40101 SET COLLATION_CONNECTION=@OLD_COLLATION_CONNECTION */;
/*!40111 SET SQL_NOTES=@OLD_SQL_NOTES */;

-- Dump completed on 2018-01-13  7:24:53
Connection to bradford-abbas.uk closed.
```

**Comment by iainhouston** [comment] 2018-01-15 15:21
FYI Using Drush launcher 0.5.0; Drush 9.0.0-rc2 via composer.

**Comment by weitzman** [comment] 2018-01-17 04:12
Looks like thats coming from ssh. See https://superuser.com/questions/457316/how-to-remove-connection-to-xx-xxx-xx-xxx-closed-message.

Can you run with --verbose so we can see the exact ssh command thats Drush is running?

**Comment by iainhouston** [comment] 2018-01-17 11:18
Yes, the `rsync` is missing both the terminal "/"s so its not replacing files but adding the complete source directory to the target.

So it should be 

```
rsync ...                                                                           \    
webmaster@bradford-abbas.uk:/var/www/drupal/web/sites/default/files/                \       
/var/www/drupal/web/sites/default/files/
```

rather than

```
vagrant@vagrant:/var/www/drupal/web$ drush rsync  @balive:%files @self:%files --verbose
 [info] ssh -o PasswordAuthentication=no -i ~/.ssh/BAPC-2.pem webmaster@bradford-abbas.uk 'drush  --backend=2 --root=/var/www/drupal/web --uri=bradford-abbas.uk  core-status   --project=files 2>&1' 2>&1
 [info] /usr/local/bin/drush  --backend=2 --root=/var/www/drupal/web --uri=default  core-status   --project=files 2>&1
You will delete files in /var/www/drupal/web/sites/default/files and replace with data from webmaster@bradford-abbas.uk:/var/www/drupal/web/sites/default/files

 Do you want to continue? (yes/no) [yes]:
 > 

Calling system(rsync -e 'ssh -o PasswordAuthentication=no -i ~/.ssh/BAPC-2.pem' -akzv  --stats --progress webmaster@bradford-abbas.uk:/var/www/drupal/web/sites/default/files /var/www/drupal/web/sites/default/files);
receiving incremental file list
files/
...
```

**Comment by iainhouston** [comment] 2018-01-17 11:25
Yes, it's using the `-t` flag.

```
$ drush @balive sql-dump > tmp.sql --verbose
Calling proc_open(ssh -o PasswordAuthentication=no -i ~/.ssh/BAPC-2.pem -t webmaster@bradford-abbas.uk 'drush  --verbose --root=/var/www/drupal/web --uri=bradford-abbas.uk  sql-dump --verbose 2>&1' 2>&1)
```

**Comment by weitzman** [comment] 2018-02-12 21:45
I think this is a dupe of #1270.

**Closed by weitzman** 2018-02-12 21:45 UTC
