### ISSUE TITLE
`drush cex` doesn't remove `language` directory when it should

### ISSUE THREAD

**Issue by boobaa** [drush-ops/drush#3572] opened 2018-06-01 11:23 UTC
Steps to reproduce:
- Install a D8 site with two languages.
- Export its config via `drush cex`. A `language` directory will be created under `sync`.
- Delete the non-default language.
- Re-export the config via `drush cex`.

Actual results:
- Drush says `The .yml files in your export directory (sites/default/files/config_whatever_hash/sync) will be deleted and replaced with the active config.`
- The `language` directory along with all its .yml files are still present.
- Subsequent `drush cex` commands will also report their deletion but won't actually delete them either.

Expected results:
- The `language` directory should be gone altogether with all the subdirectories and .yml files in it.

This is not a D8 core bug: when the config is first exported from the web UI, the tarball does contain the `language` directory, but when it's exported with all the non-default languages deleted, the `language` directory is gone from the tarball.

**Comment by yobottehg** [comment] 2018-06-01 15:42
I can confirm this from multiple previous experiences. This is also true for single files inside these language directories (For example a view translation that got deleted).

**Comment by DerH4NNES** [comment] 2018-09-13 16:42
I dont't think that this is a drush problem. I can reproduce that problem with the drupal console too.

**Comment by cydgit** [comment] 2018-09-19 10:17
drush cex doesn't delete collections. The above pull request fixes it.

**Comment by Sylry** [comment] 2018-10-22 16:56
It seems it breaks the cex command with that exception on a site where I have several languages:
`In FileStorage.php line 254:
FilesystemIterator::__construct(conf/drupal/config/sync/language/ar): failed to open dir: No such file or directory`

If I comment the lines of what was merged, it works like before.

**Comment by Sylry** [comment] 2018-10-23 10:57
A quick fix is to try/catch the `$target_collection->deleteAll();` which was added 
Another one is to try/catch the `$this->storage->deleteAll($prefix)` in config_filter FilteredStorage

But it might be a better solution to check in drupal core (`FileStorage::deleteAll()`) if the directory exists before trying to instanciate the FilesystemIterator

**Comment by vrwired** [comment] 2018-10-24 21:03
I ran into same issue and did not have config_split installed. It did export full via UI though seemed to take a while. I also temp commented out latest merge on vendor/drush/drush/src/Drupal/Commands/config/ConfigExportCommands.php 

I got back
 [success] Configuration successfully exported

**Comment by dpacassi** [comment] 2018-10-29 10:39
I have the same issue with `Drush 9.5.2`, rolling back to `Drush 9.3.0` solves the issue for me.

**Comment by joergLin** [comment] 2018-10-29 11:32
> I have the same issue with Drush 9.5.2, rolling back to Drush 9.3.0 solves the issue for me.

Same here, rolling back to `Drush 9.3.0` solves it while using `Drupal 8.6.2` with `config_split`.

**Comment by dlopez-akalam** [comment] 2018-10-31 11:23
I have the same issue described on https://github.com/drush-ops/drush/issues/3572#issuecomment-431896252
I can confirm that reverting [75340711266608048ae8c5de2bc142fbf93e46ed](https://github.com/drush-ops/drush/commit/75340711266608048ae8c5de2bc142fbf93e46ed) fixes the issue for us.

Here is a patch reverting this commit for a quick fix for those who needs to use drush 9.5.2
[drush-ops_drush-3572.patch.txt](https://github.com/drush-ops/drush/files/2534033/drush-ops_drush-3572.patch.txt)

**Comment by charlieartist** [comment] 2018-11-02 03:17
I'm seeing this as well, running Drush 9.5.2

**Comment by WidgetsBurritos** [comment] 2018-11-07 04:00
I ran into this issue as well and can confirm it's the drush 9.5.2 and config split combo that causes the issue. 

I applied the patch from https://github.com/drush-ops/drush/issues/3572#issuecomment-434651065 and can confirm it works.

**Comment by vrwired** [comment] 2018-11-07 14:46
Yes, I also came back to apply this patch (after my temp fix) and the patch solves the problem on every install/update

**Comment by bircher** [comment] 2018-11-14 08:44
Could people with this issue try updating config_filter to the just released 1.4? (it doesn't do a try catch when deleting but it ensures that filters do not create non unique collection names).

I hope one day the exporting of config will be addressed in core.

**Comment by joergLin** [comment] 2018-11-14 11:59
> Could people with this issue try updating config_filter to the just released 1.4? (it doesn't do a try catch when deleting but it ensures that filters do not create non unique collection names).

No luck for me, still same error as in https://github.com/drush-ops/drush/issues/3572#issuecomment-431896252.

**Comment by danepowell** [comment] 2018-11-17 00:15
I was also experiencing the following error when running `drush cex` using Config Filter 1.3 and Drush 9.5.2. After updating to Config Filter 1.4, it seems to be gone.

> FilesystemIterator::__construct(config/default/language/fr): failed to open dir: No such file or directory

**Comment by matthiasm11** [comment] 2018-11-21 11:41
I can confirm upgrading to Config Filter 1.4 fixes the issue. Using Drush 9.5.2.

**Comment by frederickjh** [comment] 2019-05-15 08:25
Just wanted to report in that now that I am on Drush version 9.6.2  using config_filter 1.4.0 this is no longer an issue. It seems to have been fixed between Drush and the Config Filter module. If this is true for others then this issue could be closed.

**Closed** 2019-05-15 10:16 UTC
