### ISSUE TITLE
declare(strict_types = 1); new in "drush generate" in Drush 12?

### ISSUE THREAD

**Issue by ultimike** [drush-ops/drush#5647] opened 2023-06-10 15:40 UTC
I noticed that `declare(strict_types = 1);` is used in the output of most (all?) `drush generate` commands when using Drush 12. I am comfortable with what it does, but I am curious about the decision to include it as it is not (yet) a best-practice in Drupal (AFAIK). 

I've searched this issue queue for discussion about it and came up empty - can someone point me in the right direction?

I'll all for being forward-looking with this type of stuff - just looking for the back story (if there is one).

Also - the current phpcs Drupal rulesets flag it as an issue. 

thanks,
-mike

**Comment by Sweetchuck** [comment] 2023-06-12 10:20
https://www.drupal.org/project/coding_standards/issues/3303206

Somewhere I read that when a **new file** added to the Drupal core, it must contains `declare(strict_types = 1);`, but I think they still can't agree on the code style.

**Comment by weitzman** [comment] 2023-06-12 11:19
There is no link where this Drush decision is documented. I decided independently.

strict_types is a best practice in PHP. Its not even controversial. I suggest projects ship with an exception for this coding standard violation. And help get Drupal coding standard updated.

Minor decisions like this help move Drupal coding standards into the modern era.

**Comment by Chi-teck** [comment] 2023-06-13 19:02
> Somewhere I read that when a new file added to the Drupal core

Here is the discussion.
https://www.drupal.org/project/drupal/issues/3250827


> Also - the current phpcs Drupal rulesets flag it as an issue.

This format does not violate Drupal coding standards as the are no such standards yet.
https://www.drupal.org/project/coder/issues/3197806

**Comment by Sweetchuck** [comment] 2023-06-13 19:09
That is the core. Contrib modules should have used strict_types much earlier.
Big plus for this feature in Drush. I mean the generated codes already contain strict_type definition. Hopefully it will give a boost for the cause.

---

For example usage of strict_types can prevent bugs like this:
https://www.drupal.org/project/drupal/issues/3364204

**Comment by Chi-teck** [comment] 2023-06-13 19:16
> I'll all for being forward-looking with this type of stuff - just looking for the back story (if there is one).

https://github.com/Chi-teck/drupal-code-generator/issues/87

**Comment by Chi-teck** [comment] 2023-06-13 19:28
Actually Drupal core has already started using strict types. There are more a than hundred examples like [this](https://git.drupalcode.org/project/drupal/-/blob/10.1.0-rc1/core/lib/Drupal/Core/Validation/Plugin/Validation/Constraint/ValidKeysConstraint.php?ref_type=tags#L5
).

**Comment by Sweetchuck** [comment] 2023-06-13 19:30
Sorry for the off topic.
Just because the tooling around the Drupal ecosystem can't keep up with the requirements, developers not allowed to use all the helper tools.

https://www.drupal.org/project/drupal/issues/3323252

The reason we can't use the `@method` annotation is because api.drupal.org would display it in an ugly way. (no line breaks or syntaxhighlight)

I spend 8-12 hours per day using PHPStorm, and it can't provide me proper autocomplete.
I spend 0 minutes on api.drupal.org per month.

**Comment by Sweetchuck** [comment] 2023-06-13 19:46
> Actually Drupal core has already started using strict types

Good to see that. :+1:

Problem is that strict_types was introduced in PHP 7.0 (I think), but 7.3 certainly has this feature.

* PHP 7.0 release date 2015-12
* Today 2023-06

**Comment by Chi-teck** [comment] 2023-06-13 20:12
> https://www.drupal.org/project/drupal/issues/3323252

This can be fixed with phpstorm meta data. For static entity methods we already generate such data. We need just to apply this logic to entity storages.

**Comment by Sweetchuck** [comment] 2023-06-13 20:17
Years ago I played with it, but I don't use it for a while.
* https://github.com/Sweetchuck/drush-ide-helper
* https://www.drupal.org/project/ide_helper

**Comment by Sweetchuck** [comment] 2023-06-13 21:05
> This can be fixed with phpstorm meta data.

Problem is that, it is not easy.
When an entity type **has no** custom storage handler interface, it just uses a class which does not implement a custom storage interface `\Drupal\Core\Entity\Sql\SqlContentEntityStorage`, just uses the common one  `\Drupal\Core\Entity\ContentEntityStorageInterface` then hard to attach extra info/metadata to the `::load()` method.

**Comment by Chi-teck** [comment] 2023-06-14 05:27
I know. That's a limitation of PhpStorm that blocks implementing some cool things like completion properties in in query builders. Probably needs to be reported as feature request for PhpStorm.

**Comment by Chi-teck** [comment] 2023-06-14 05:29
I think all questions raised in the issue summary have been addressed.

**Closed as completed by Chi-teck** 2023-06-14 05:29 UTC
