### ISSUE TITLE
Drush CR removes rest resources on multi site installs

### ISSUE THREAD

**Issue by andrewg211** [drush-ops/drush#3540] opened 2018-04-24 05:25 UTC
Drush 9 is not usable at present on multi site installs that use custom REST Resources.

Easy to replicate, for the sake of simplicity, let's say we are working with 2 sites.

Create 2 basic modules, each with a custom REST resource.

Then run 'drush cr' on either site. The REST resources will no longer be available until you uninstall and re-install the module.

This is not an issue with Drush 8, likewise if you clear the cache through the browser.

Drupal Core 8.5.1
REST UI 8.x-1.15

**Comment by aleksip** [comment] 2018-05-07 07:00
This looks a lot like a duplicate of #3391.

**Closed** 2018-05-07 11:09 UTC
