### ISSUE TITLE
Configure URI for default site

### ISSUE THREAD

**Issue by AdamPS** [drush-ops/drush#4638] opened 2021-01-19 11:49 UTC
**Background/motivation**
Follow on from #4551.  Each Drupal site can respond to many URIs but effectively has a "canonical URI" used in sitemaps, metadata, system mails etc.  It's essential for drush to set the URI correctly especially for running cron.  Cron jobs may send mails, create search indices etc and they need to be done with the right base URI.  For all of the secondary sites, the canonical URI is implicitly defined from the directory name sites/XXX.  For the default site we need another way to set it.  The file sites/all/drush/drush.yml affects all sites so it's no good (unless you have just one site).

**Describe the solution you'd like**
The obvious answer to me is to allow sites/default/drush.yml to set options:uri.   I agree that sites/default/drush.yml is too late to affect which site gets bootstrapped.  However it seems entirely realistic and very convenient to use it to define the URI that gets passed to Drupal for the default site.

**Describe alternatives you've considered**
In 4551 @weitzman suggested to use environment variables, especially when developers are using different hostname.  However it seems like a nightmare for a team of admins trying to manage dozens of small sites .  The canonical site URL of a site should be defined in a single central location not per developer.  When we want to run an operation on a group of sites, the environment would somehow have to be swapped in between each one.  Drush does an excellent job of solving exactly this problem for every other parameter about a site, so it seems a shame if it can't help with

**Comment by AdamPS** [comment] 2021-01-19 11:54
I had a look at trying to create a PR but it's a bit complex.  I guess that immediately after loading the site-specific drush.xml (I didn't yet manage to find the code that does this) we could try to call `Application::selectUri()` again.  However  `DrupalBoot8::bootstrapDrupalSiteValidate()` builds a request even though it won't be used yet.  

If you would support this change and are willing to give me some hints I could try to write a PR.

**Comment by weitzman** [comment] 2021-01-19 14:16
Thanks. This looks like a dupe of many issues. Lets go with #4345

**Closed by weitzman** 2021-01-19 14:16 UTC

**Comment by weitzman** [comment] 2021-01-19 14:25
You can always check in a script that does `DRUSH_OPTIONS_URI=http://example.com drush cron ...`

**Comment by AdamPS** [comment] 2021-01-19 15:01
Thanks
