### ISSUE TITLE
Ignore vendor folders to improve directory search performance

### ISSUE THREAD

**Issue by SebCorbin** [drush-ops/drush#1445] opened 2015-06-18 11:14 UTC
See https://www.drupal.org/node/2329453

This is a critical issue for Windows users where drush does not ignore `node_modules` directory. A `drush cc all` will scan this directory and will find too long paths for Windows (due to node_modules nested tree).

To solve this for drush, an environment option to add some directories like `node_modules`, `bower_components` to the ignore directories passed in `drush_scan_directory()` would be really nice

**Comment by weitzman** [comment] 2015-06-23 19:45
Looks like a dupe of #1347

**Closed by weitzman** 2015-06-23 19:45 UTC
