### ISSUE TITLE
add docs on what traits and interfaces commands can have

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3145] opened 2017-11-06 15:51 UTC
From #3119:

> The best way to get access to the config object is via ConfigAwareInterface / ConfigAwareTrait.

There's no documentation on the various interfaces that you can give a command that then get you extra functionality. Once I knew about this interface, I was able to look for it in the source code and figure it out (and spot all the other interfaces that get detected), but it's not discoverable for developers.

**Comment by weitzman** [comment] 2017-11-06 15:59
A dupe of #2954, but we can leave it open for ... Lets add more links to the docs from places where one might expect to find this (e.g. Command authoring).

**Comment by greg-1-anderson** [comment] 2017-11-06 16:52
Yes; the exact request of this issue was satisfied by https://github.com/drush-ops/drush/pull/3001/files#diff-160a05f682b3f61e075fab3217cd8559R75, but I agree that this could be more discoverable with more cross-references from other parts of the docs.

**Closed** 2017-11-07 14:58 UTC
