### ISSUE TITLE
Could Single Directory Components be generated for modules as well as themes?

### ISSUE THREAD

**Issue by lostcarpark** [drush-ops/drush#6132] opened 2024-10-11 21:19 UTC
**Is your feature request related to a problem? Please describe.**
`drush generate sdc` only offers the option of generating a component in a theme.

It would be nice if it could also generate a component in a module.

**Describe the solution you'd like**
Perhaps the first question could be "theme or module?"

Alternatively there could be a separate generate command (e.g. `drush generate single-directory-component-module`).

**Describe alternatives you've considered**
My current workaround is to generate into a temporary theme, and move the component into my module, but I think it's likely that enough people will want SDCs in modules to be worth supporting.

**Additional context**
None.

**Comment by Chi-teck** [comment] 2024-10-14 19:09
Closing as a duplicate of
https://github.com/Chi-teck/drupal-code-generator/issues/115

**Closed as completed by Chi-teck** 2024-10-14 19:09 UTC
