### ISSUE TITLE
Drush 8.4.10 Deprecation notices with PHP 8.1

### ISSUE THREAD

**Issue by djdevin** [drush-ops/drush#5115] opened 2022-04-06 14:25 UTC
**Describe the bug**

```
Deprecated: Return type of HumbugBox3140\KevinGH\RequirementChecker\RequirementCollection::getIterator() should either be compatible with IteratorAggregate::getIterator(): Traversable, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/drush/.box/src/RequirementCollection.php on line 14

Deprecated: Return type of HumbugBox3140\KevinGH\RequirementChecker\RequirementCollection::count() should either be compatible with Countable::count(): int, or the #[\ReturnTypeWillChange] attribute should be used to temporarily suppress the notice in phar:///usr/local/bin/drush/.box/src/RequirementCollection.php on line 19
```

**To Reproduce**

Run `drush` on PHP 8.1

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.x
| Drupal version? | 7.x
| PHP version     | 8.1
| OS?             | Any Linux, PHP 8.1

**Comment by matthewsherman** [comment] 2022-05-05 18:45
This is also happening with drush 11 as well.  I am using 11.0.9

**Comment by weitzman** [comment] 2022-05-05 18:52
Drush 11 is not packaged as a phar so it cant give this error. I wonder if both reports of this error are misfiled and should be against https://github.com/drush-ops/drush-launcher. Ah yes, this is a dupe of https://github.com/drush-ops/drush-launcher/issues/96 (which is fixed). Please update your launcher, or better yet stop using it.

**Closed by weitzman** 2022-05-05 18:52 UTC
Labels: drush8

**Comment by danepowell** [comment] 2022-08-03 15:02
> Please update your launcher, or better yet stop using it.

Wait, what? Is there something wrong with the launcher? I thought using it has been best practice since... like, forever ago.

**Comment by weitzman** [comment] 2022-08-03 23:30
My preferred alternatives are detailed at https://github.com/drush-ops/drush-launcher#alternatives
