### ISSUE TITLE
Getting SVN errors when updating Drupal core with pm-updatecode and Drush 7

### ISSUE THREAD

**Issue by mortenson** [drush-ops/drush#1056] opened 2014-12-17 18:36 UTC
I'm starting to use Drush 7 with SVN, and noticed an error when updating Drupal core that I never got with Drush 6:

```
$ drush pm-updatecode drupal --version-control=svn --svnsync
Update information last refreshed: Never
 Name    Installed Version  Proposed version  Message
 Drupal  7.26               7.34              SECURITY UPDATE available


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
Destination directory docroot/drupal-7.34 already exists.                                                                                          [error]
Updating project drupal failed. Attempting to roll back to previously installed version.                                                                                       [error]
Drush was unable to get the svn status on docroot/drupal-7.34. Check that you have Subversion                                                      [error]
installed and that this directory is a subversion working copy.
The specific errors are below:
svn: 'docroot' has no ancestry information
```

As I'm not that familiar with how Drush 7 works with SVN, does anyone have any ideas regarding this?

**Comment by jonhattan** [comment] 2015-01-02 13:34
This could be a regression introduced with e999ec. I'll check that.

I'd prefer to not lose code that is already isolated. Perhaps keeping version-control feature, but moving svn and bzr implementations to contrib is an option. I'd be happy to do such extraction --and provide a basic git vcs implementation that I'll use myself.

**Comment by weitzman** [comment] 2015-01-02 14:30
I like that plan, jonhattan.

**Comment by whittaker007** [comment] 2015-01-11 20:29
Excuse me for butting in, but I'm seeing similar issues which I'm not sure is SVN-specific or not. We do have our project version control under SVN, and after updating Drush we are unable to update modules with `svn up`.

What happens is `svn up` lists the available updates and asks for confirmation as usual, but once confirmed it fails on the first module with the message:

````
Destination directory [path to module] already exists.
Updating project [module name] failed. Attempting to roll back to previously installed version.
````
Except it doesn't roll back the module, it deletes it instead.

Updating the modules using `drush dl` works as expected.

**Comment by kgaut** [comment] 2015-01-15 13:46
I'm experiencing the same issue as @whittaker007 when trying to do a pm-update on my drupal 7 project.

Don't know ether if it's related to Subversion but my `.svn` is at the root of my drupal instance.

here's the full output : 
```bash
Update information last refreshed: jeu, 01/15/2015 - 14:33
 Name                                             Installed Version  Proposed version  Message                   
 Administration menu (admin_menu)                 7.x-3.0-rc4        7.x-3.0-rc5       Mise à jour disponible    
 Better Exposed Filters (better_exposed_filters)  7.x-3.0-beta4      7.x-3.0           Mise à jour disponible    
 Context (context)                                7.x-3.5            7.x-3.6           SECURITY UPDATE available 
 Entity Construction Kit (eck)                    7.x-2.0-rc5        7.x-2.0-rc6       Mise à jour disponible    
 Features (features)                              7.x-2.2            7.x-2.3           Mise à jour disponible    
 Rules (rules)                                    7.x-2.7            7.x-2.8           Mise à jour disponible    
 Search API (search_api)                          7.x-1.13           7.x-1.14          Mise à jour disponible    
 Workflow API (workflow)                          7.x-2.4            7.x-2.5           Mise à jour disponible    


Security and code updates will be made to the following projects: Administration menu [admin_menu-7.x-3.0-rc5], Better Exposed Filters [better_exposed_filters-7.x-3.0], Context [context-7.x-3.6], Entity Construction Kit (ECK) [eck-7.x-2.0-rc6], Features [features-7.x-2.3], Rules [rules-7.x-2.8], Search API [search_api-7.x-1.14], Workflow [workflow-7.x-2.5]

Note: A backup of your project will be stored to backups directory if it is not managed by a supported version control system.
Note: If you have made any modifications to any file that belongs to one of these projects, you will have to migrate those modifications after updating.
Do you really want to continue with the update process? (y/n): Y
Do you really want to continue with the update process? (y/n): y
Destination directory /media/vhosts/info-reseaux.fournier-habitat.com/www/sites/all/modules/admin_menu already exists.                                                     [error]
Updating project admin_menu failed. Attempting to roll back to previously installed version.                                                                               [error]
```
I'm using the last 7.0 dev version of drush and subversion in in version 1.8.10.

**Comment by kgaut** [comment] 2015-01-15 14:14
downgrading to drush 6.x fix this issue, so it's a recent commit that cause this problem.

**Comment by MrKuja** [comment] 2015-02-20 10:45
@kgaut I've encountered the same problem (latest Drush version / project with SVN versionning).
I'll hope this will be fixed soon, it's quite annoying for many of my projects (especially ones with a lot of modules).

**Comment by mortenson** [comment] 2015-02-20 16:12
I've been using the steps from my second comment and it's been working o.k. as a temporary fix.

**Comment by whittaker007** [comment] 2015-06-01 23:14
cloning the site and rsyncing every time Drupal is updated is a major pain, especially if you maintain more than one Drupal site. Downgrading Drush to v6.6 is probably the best solution for now until Drush 8 is ready - I think Drush 8 is dropping support for SVN which is preferable to broken support.

**Comment by joachim-n** [comment] 2016-01-05 09:51
This error is especially annoying on OS X El Capitan if svn is not installed, as the absence of the command causes a pop-up window offering to install Xcode.

**Comment by AdamPS** [comment] 2016-02-18 10:23
Update on D8.  I've jumped straight from D6 to D8 and am just hitting this bug.

1) It looks like svnsync is in D8.  I'm happy, I vote to keep it!  It may be a minority, but clearly there are a few of us (presumably dozens of silent bemused users for each one who speaks up here).
2) But the bug is not fixed. Does anyone have any idea how to fix?  Would a patch be accepted or is SVN support really being ditched?

Thanks

**Comment by AdamPS** [comment] 2016-02-18 11:29
Update from some debugging.

1) I still get the error after removing the options for SVN (--version-control=svn --svnsync), i.e. I am just running "drush up".  Aha it looks like D8 is auto-detecting my version engine.  However I can override that by passing --version-control=backup

2) If using backup, it works.  That's because backup.inc pre_update deletes/renames the existing project folder entirely.

3) If using SVN, there is code in pm_update_project that removes all files in the project directory except reserved ones - but leaves the directory itself.  (Arguably this code might be neater also in $engine->pre_update for consistency with 2) but not a big deal).  However the directory itself remains, so when wget.inc package_handler_update_project calls drush_move_dir it fails.

NB It looks like this same bug would apply if using any other version control engine, providing the package-handler is wget.

Not exactly sure how to fix.  Perhaps package_handler_update_project needs to handle an existing directory and move in individual files?

4) The rollback fails because svn.inc rollback function is missing the -R option to svn revert.  That's a separate bug and it seems like an easy fix, just add -R.

**Comment by weitzman** [comment] 2016-03-16 20:07
@jonhattan - the 9.x branch is open. Now might be a good time to move svn and bzr integrations to Contrib

**Comment by AdamPS** [comment] 2016-03-18 22:56
If we could deal with #2083 before doing any refactoring that would be extremely helpful thank you.

**Comment by AdamPS** [comment] 2016-11-07 18:15
I understand that SVN support is being dropped in Drush 9.  However the changes here are not in fact SVN specific.  My patch removes various lines no longer needed in modern VCS and simplifies some other code.  

So yes these changes do fix SVN - but I suggest they are useful even if SVN is no longer supported.

**Comment by andrex-e-schulman** [comment] 2017-05-10 18:00
@mortenson : Confirmed that for our bzr project, temporarily moving the .bzr directory out of the way, updating, and moving .bzr back works around the problem.

**Comment by weitzman** [comment] 2017-06-05 10:49
Closing for lack of activity

**Closed by weitzman** 2017-06-05 10:49 UTC
Labels: area-pm, type-bug
