### ISSUE TITLE
'drush up drupal' deleted my .git file in Drupal root

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#1581] opened 2015-08-29 08:51 UTC
```
joachim$ git push
Counting objects: 154, done.
Delta compression using up to 2 threads.
Compressing objects: 100% (79/79), done.
Writing objects: 100% (79/79), 11.87 KiB | 0 bytes/s, done.
Total 79 (delta 66), reused 0 (delta 0)
To git@bitbucket.org:joachim-n/foo.git
   33e5438..47d8d1c  master -> master
~/Sites/joachim-accounts joachim$ drush up drupal
Update information last refreshed: Sat, 29/08/2015 - 09:39
 Name    Installed Version  Proposed version  Message
 Drupal  7.38               7.39              SECURITY UPDATE available


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
Project drupal was updated successfully. Installed version is now 7.39.
No database updates required                                         [success]
'all' cache was cleared.                                             [success]
Finished performing updates.                                         [ok]
joachim$ git add modules/ themes/ includes/ misc/ profiles/
fatal: Not a git repository (or any of the parent directories): .git
```

The only explanation I can see is that in moving things around to update core, Drush wiped the .git folder!

**Comment by weitzman** [comment] 2015-08-31 15:45
By design. Thats somewhat obtusely referred to in the warning "Updating core will discard any modifications made to Drupal core files".

Related discussion at #83 and #1261

**Comment by jonhattan** [comment] 2015-08-31 18:02
Also #1464. It provides an example to recover a folder from the backup.

**Comment by joachim-n** [comment] 2015-08-31 20:18
By design???
The .git file isn't a modification made to a Drupal core file; it's an extra file.

**Comment by weitzman** [comment] 2015-08-31 20:27
Ok, not By Design. But still this a dupe. See the links posted above.

**Comment by joachim-n** [comment] 2015-08-31 21:01
I don't really follow how #83 and #1261 are related. Those are about having Drush help with managing the git repo for my site.
But this bug is merely about Drush not deleting the git repo. I wasn't expecting Drush to do a git commit or anything fancy -- just not delete my repository, and with that, a number of local branches with work in them.
I've been using 'drush up drupal' for years now, and it's never done this before. I would expect Drush to leave alone files that are non-Drupal.

**Comment by cwarren** [comment] 2015-09-01 18:44
Just ran into exactly this problem. It was totally unexpected and really mucked things up. I don't understand why this is closed as the other tickets referenced don't actually help solve this problem.

**Comment by weitzman** [comment] 2015-09-01 18:56
Can you test earlier versions of Drush and verify that this used to work. To my knowledge, this is how updatecode has worked for years.

**Comment by joachim-n** [comment] 2015-09-01 19:14
I've been using 'drush up drupal' to update core on my work & personal sites for years, and they all have git repos in the Drupal root folder. On the machine where this happened, I had only just got round to upgrading Drush from being a plain git checkout to being managed by composer. On my laptop, it's composer-managed, and doesn't do this -- I'll check the version.

**Comment by cwarren** [comment] 2015-09-01 19:19
Sorry, can't check past behavior - working off other's notes. However, past behavior isn't especially relevant at the moment since that doesn't help me with actually solving the problem described above. I think I did manage to get things back in working shape by looking more closely at the update process messages and pinging some local folks.

Basically, running $ drush up --security-only left me with a .git folder and .gitignore file in my drupal root, but git was able to recognize any repository. Looking inside .git showed some stuff there, but not as much as I was expected. I tracked down the backup that the update process made (which is an AWESOME feature, btw) and compared the .git folder there with the one in my drupal root folder - very different. So, I removed the faulty .git folder and copied back in the one from the backup. I also copied in the .gitignore file and .htaccess file since those two also looked like they got hammered.

SUMMARY:
post update, once this situation is encountered I resolved it using these steps
1. $ cd [drupal root folder]
2. $ rm -r .git
3. A backup folder is given in one of the messages during the update process - it'll be something like /home/[account from which update was run]/drush-backups/[site name]/[timestamp as YYYYMMDDHHMISS]/drupal
4. $ cp [backup folder]/.git .
5. $ cp [backup folder]/.gitignore .
6. $ cp [backup folder]/.htaccess .

At this point I was back in business. Hope this helps whoever else stumbles across this situation.

**Comment by jonhattan** [comment] 2015-09-01 19:27
Drush has never preserved `.git` directory. The code is the same at least since drush 6.x. The only change introduced is adding support for Drupal 8. Reference: here https://github.com/drush-ops/drush/blob/master/commands/pm/updatecode.pm.inc#L158

**Comment by joachim-n** [comment] 2015-09-01 21:22
I've checked my laptop and the current project that I was thinking of has Drupal in a subfolder of the git repo. So that's not affected by this.

However, I *definitely* was doing 'drush up drupal' on a project that finished exactly a year ago, and that had a git repo that was rooted at the Drupal root, and I never had any problems with the .git folder being deleted or damaged.

**Comment by joachim-n** [comment] 2015-09-02 08:00
My old git checkout of drush is on branch 6.x, at commit:

```
commit b9e5666c0e1094117497f26001d91c2b7d5aeff9
Merge: 111937d ec37825
Author: Moshe Weitzman <weitzman@tejasa.com>
Date:   Tue Jul 28 11:10:44 2015 -0400

    Merge pull request #1511 from coldfrontlabs/1292-mimesql

    Fix #1292. Add mime type for .sql files
```

When I use this to update core, the .git folder is untouched:

```
~/Sites/workshop joachim$ /Users/joachim/Sites/_sandbox/drush/drush up drupal -y
Update information last refreshed: Wed, 09/02/2015 - 07:58
 Name    Installed Version  Proposed version  Message
 Drupal  7.38               7.39              SECURITY UPDATE available


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
Project drupal was updated successfully. Installed version is now 7.39.
Backups were saved into the directory                                    [ok]
/Users/joachim/drush-backups/drupal-workshop-7-base/20150902075833/drupal.
No database updates required                                             [success]
'all' cache was cleared.                                                 [success]
Finished performing updates.                                             [ok]
~/Sites/workshop joachim$ git st
# On branch master
# Changes not staged for commit:
#   (use "git add <file>..." to update what will be committed)
#   (use "git checkout -- <file>..." to discard changes in working directory)
#
```

**Comment by weitzman** [comment] 2015-09-02 18:24
I can confirm @joachim-n findings. The .git directory stayed in place, and was not copied to the backup directory.

I suspect that this old behavior was not intentional, but I will let @jonhattan provide a more authoritative answer.

**Comment by jonhattan** [comment] 2015-09-02 20:02
So I have to rectify here. I've done a test and verified that `.git` is preserved, but it is not intentional, and I don't know what the reason is.

Also, I've verified that it is a consistent behaviour for drush 6, 7 and 8, so perhaps the reported problem is due to other reasons.

This is the snippet I've used to test. Tweaking the first line to the drush version to use.

```
DRUSH=drush6
cd /tmp
sudo rm -rf drupal-7.38
$DRUSH dl drupal-7.38
cd drupal-7.38/
$DRUSH site-install minimal --db-url=sqlite://sites/default/files/.ht.sqlite -y
git init .
$DRUSH up drupal -y
ls -d .git
```

**Comment by joachim-n** [comment] 2015-09-03 08:17
My laptop has Drush from composer, but slightly out of date. This commit on 7.x doesn't zap .git:

```
commit 577227cbe0de9496299723cd5428d0e8719987d7
Merge: 8eecb25 2bb6125
Author: Christopher Gervais <chris@ergonlogic.com>
Date:   Wed Apr 8 15:54:57 2015 -0400

    Merge pull request #1327 from drush-ops/dev/1268

    Fix for issue #1268
```

**Comment by damienmckenna** [comment] 2015-09-15 11:39
I've also seen this happen inconsistently across multiple projects - most of them have updated just fine without deleting anything unwanted, whereas one site in particular would delete the .git directory and just about everything else.

**Comment by jenitehan** [comment] 2016-01-28 18:29
The .git directory just went missing for me as well using Drush 8.0.1.  I've never had it go missing with any previous Drush versions, I've only recently upgraded to Drush 8.

**Comment by JeffVeit** [comment] 2016-02-17 05:32
Wow! Drush up just deleted my git folder too. Version 8.0-dev from a few months ago. Definitely new behaviour in 8: I've pulled in updates and then added them to my dev repository like this for years. Lucky that I'd recently synced my git; I was totally not expecting this and ran with --no-backup.

In this project, the git repository was in the Drupal folder.

Although this behaviour is 'by design', I'd class this as a bug because it's a change in how it worked.

**Comment by rootwork** [comment] 2016-05-02 23:48
I've also used `drush up drupal` for years and it has never modified the .git folder. Perhaps that was expected behavior, but it wasn't what actually happened, for several years. I agree with the other folks above that to most people this feels like a bug.

**Comment by joetri** [comment] 2016-06-08 02:45
Ditto that.  Feels like a bug to me too!  I run my own backups then "drush up --no-backup" and it's never touched the .git dir in
root directory.

**Comment by damienmckenna** [comment] 2016-06-17 10:58
I'm just after updating three small sites simultaneously - two worked fine and left their .git directories alone, the third deleted the .git directory, Will see if I can dig into this a bit.

**Comment by damienmckenna** [comment] 2016-06-17 12:22
I seem to have found a reason why it only happens for some codebases. I examined the differences between the three local sites and noticed that the one which destroyed the .git directory happened to have the "no-backup" option set to TRUE in drushrc.php, the other two did not have it set.

To test the theory I reverted one of the other two to a previous release, i.e. to a release of the codebase that had 7.43, and ran "drush upc drupal" again. Sure enough, after it had finished updating everything the .git directory was gone.

So the problem appears to be in how the "no-backup" option is handled.

**Comment by damienmckenna** [comment] 2016-06-17 12:29
The problem appears to be this code:

```
  public function pre_update(&$project, $items_to_test = array()) {
    if (drush_get_option('no-backup', FALSE)) {
      // Delete the project path to clean up files that should be removed
      if (!drush_delete_dir($project['full_project_path'])) {
        return FALSE;
      }
      return TRUE;
    }
```

So basically this file deletion is on purpose.

**Comment by jalama** [comment] 2016-06-17 12:29
I can confirm this I've seen this behavior before and have coded around it in scripts.

**Comment by damienmckenna** [comment] 2016-06-17 12:37
I've uploaded PR #2226 that should fix this problem.

**Comment by damienmckenna** [comment] 2016-06-17 12:55
The PR needs work besides the tests breaking - it doesn't update core anymore and instead results in this output:

```
$ drush upc drupal -y
Update information last refreshed: Fri, 06/17/2016 - 08:42
 Name    Installed Version  Proposed version  Message                   
 Drupal  7.43               7.44              SECURITY UPDATE available


Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files, most noteworthy among these are .htaccess and robots.txt.  If you have made any modifications to these files, please back them up before updating so that you can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to update production sites without prior testing.

Do you really want to continue? (y/n): y
Destination directory /path/to/the/site/drupal-7.44 already exists. [error]
Updating project drupal failed. Attempting to roll back to previously installed version.  [error]
```

**Comment by damienmckenna** [comment] 2016-06-17 14:07
I've added PR #2227 as an alternative, it at least gives a warning that non-core files will be deleted.

**Comment by damienmckenna** [comment] 2016-06-17 14:07
I closed PR #2226 because of the problems, I'll need to dig into it further.

**Comment by weitzman** [comment] 2016-07-12 20:01
Nothing left to do in this issue AFAICT

**Comment by joachim-n** [comment] 2016-07-12 20:36
Has there been a fix?

**Comment by bmunslow** [comment] 2016-07-19 15:50
So my .git file just got deleted after doing:

`drush up drupal -y
`
@joachim-n Were you able to recover your .git directory in some way?

**Comment by joachim-n** [comment] 2016-07-19 16:10
Nope, it was gone. Unless you've pushed it to a remote (but even then you've still lost local branches and stashes).

**Comment by JeffVeit** [comment] 2016-07-19 16:20
I was lucky enough to have a backup. If you are on Windows, I guess there's
a chance you could undelete.

**Comment by joetri** [comment] 2016-07-19 16:35
Me too: Gone Gone Gonzo.  I now just run "drush up" or "drush up drupal" (and have a nervous tick as I hit enter!).  Make sure to push to the external repo before upgrade, then you can always recover.

**Comment by lifenstein** [comment] 2016-07-19 20:43
@bmunslow @joetri If you haven't turned off backups with the drush flag, `drush update` will make a backup, which includes the `.git` directory.

**Comment by javlonbek** [comment] 2016-07-20 16:23
Confirming the same behavior. drush up drupal deleted my .git

**Comment by joachim-n** [comment] 2016-07-20 16:31
If this is with very latest Drush, can this be reopened please @weitzman?

**Comment by RokSiEu** [comment] 2016-07-22 08:16
I can confirm the same behavior. It's time to reopen this issue @weitzman .

**Comment by weitzman** [comment] 2016-07-22 12:50
I committed a warning for the help on --no-backup option. I suggest not using that option.

**Comment by joachim-n** [comment] 2016-07-22 13:00
Surely that option is currently broken?

And if you have your code under version control, then it should be possible to run without Drush making backups, as your version control provides the means to undo a file change.

**Comment by weitzman** [comment] 2016-07-22 13:08
Perhaps a bug. I've reopened this. Would be great if someone looked at what has changed with --no-backup and provided a PR.

**Comment by coredumperror** [comment] 2016-11-18 00:06
PR #797 from Oct 2014 is the culprit. It added a step that runs `drush_delete_directory()` on the project path when --no-backup is used, to "clean up files that don't exist in the newer version".

This makes sense for contrib modules, since those are unlikely to have any non-module files within their project folder. But the Drupal root folder *is* likely to have all kinds of extra stuff in it, especially when it's also the VCS root of the project.

I don't know enough about the drush APIs to make a PR for this, but I think the correct fix would be to not call `drush_delete_directory()` if the `$project` array is Drupal core. 

That will bring back the problem of not removing stale Drupal core files, but I don't know of any way to differentiate said files from those which were never part of Drupal core in the first place.

**Comment by alexymik** [comment] 2017-01-04 18:20
I had various undesired results after Drush got updated without me noticing. I have an automated script that tries to update the Drupal core and checks it into git.

In some cases when using Drush 8, the `.git` folder would be removed. In some lower versions, running the core update would delete everything besides the `sites` and `drupal-(whichever version it was trying to update to)` folders and never finish the core update.

Reverting to Drush 6.2.0 resolved it for me.

**Comment by lifenstein** [comment] 2017-01-18 10:14
A whitelist in drushrc.php could perhaps address the issue of differentiating between deleted files in core and non-drupal files?

**Comment by attheshow** [comment] 2017-03-16 19:39
I'm running into this as well and have been since I started working with Drupal 8. Trying to think of an easy fix that would work.

**Comment by RokSiEu** [comment] 2017-03-16 19:57
Revert to older version of drush. This is the easiest and cleanest way for
now.
I know this issue is old but it seems that most of the users can not
reproduce it.

**Comment by attheshow** [comment] 2017-03-16 19:59
Another option that appears to work is to temporarily move the .git directory to another location such as your home directory during the update and then move it back.

`mv .git ~/.git && drush up drupal -y && mv ~/.git .git`

**Comment by RokSiEu** [comment] 2017-03-16 20:01
This works as long as you are not in a team

**Comment by attheshow** [comment] 2017-03-16 20:04
Sorry, I didn't follow that one.

**Comment by lifenstein** [comment] 2017-03-17 02:58
Why would your local repo changes affect your team?

**Comment by RokSiEu** [comment] 2017-03-17 06:28
Because they have to have the same instructions if they can do the update.
Like said before, this are all dirty workarounds

**Comment by damiankloip** [comment] 2017-03-17 07:23
If you structure your repo in a better way, this isn't a problem. I.e. Don't have your drupal installation at the top level.

**Comment by lifenstein** [comment] 2017-03-17 11:20
In some instances, I have my .git directory outside of webroot, which avoids this issue. Just need to do clone as a bare repo, then set core.bare to false, followed by core.worktree set to the docroot. You could do this for your team, @RokSiEu. There is a drawback: you'll have to switch between the two dir.s for git commands and drush commands.

**Comment by parkerjgit** [comment] 2017-04-30 22:16
Wow, Drush just vaporized my git folder. These workarounds are really insufficient.  Drush 8.3.1

**Comment by coredumperror** [comment] 2017-05-01 17:43
Until this gets fixed (I described exactly what's wrong in my comment from November 2016, but I don't know how to fix it), the easiest workaround is to not use the `--no-backup` option. Exclude it from your `~/.drush/drushrc.php file`, if you put it there thinking that having your own backups (i.e. your code being in git) was sufficient.

**Comment by parkerjgit** [comment] 2017-05-01 23:46
I see, but thinking about user who hasn't already learned this the hard way. Perhaps a much more conspicuous/explicit ALL CAPS!! warning until it is fixed.

**Comment by laradevitt** [comment] 2017-05-07 17:53
Just ran `drush pm-update drupal-8.3.2` on a local repo (Windows) and .git folder is mostly obliterated. Not gone, just *mostly* gone with a few files remaining. Otherwise the update seems to have been successful. I ran it on two other installations last week and everything was fine. I am not using --no-backup.

```
$ drush core-status
 Drupal version                  :  8.3.2
 Site URI                        :  http://default
 Database driver                 :  mysql
 Database hostname               :  localhost
 Database port                   :  3306
 Database username               :  root
 Database name                   :  d8_dev1
 Drupal bootstrap                :  Successful
 Drupal user                     :
 Default theme                   :  bartik
 Administration theme            :  seven
 PHP configuration               :  C:\wamp\bin\php\php5.6.13RC1\php.ini
 PHP OS                          :  WINNT
 Drush script                    :  C:\Users\xxx\AppData\Roaming\Composer\vendor\drush\drush\drush
 Drush version                   :  8.0.0
 Drush temp directory            :  C:\Users\xxx\AppData\Local\Temp
 Drush configuration             :  C:\Users\xxx\.drush\drushrc.php
 Drush alias files               :  C:\Users\xxx/.drush/aliases.drushrc.php C:\Users\xxx/.drush/example.aliases.drushrc.php C:/wamp/www/d8_dev1/.drush/aliases.drushrc.php
 Install profile                 :  standard
 Drupal root                     :  C:\wamp\www\d8_dev1
 Site path                       :  sites/default
 File directory path             :  sites/default/files
 Temporary file directory path   :  c:\windows\temp
 Sync config path                :  sites/default/files/config_XZ4lLcDGh0UKipNg17Hnqe84tAgwazbPWOClwlQTQDFGiAtbI9bJ949WLmxM94cYP1sy_3n7ww/sync
```

**Comment by greg-1-anderson** [comment] 2018-07-16 02:42
`pm-*` commands are maintenance only; closing.

**Closed by greg-1-anderson** 2018-07-16 02:42 UTC
Labels: area-pm, type-bug

**Comment by JeffVeit** [comment] 2018-07-16 11:36
Seriously? Closed? Wiping out git is a pretty big thing, and how does 'pm-* commands are maintenance only' justify closing this?

**Comment by greg-1-anderson** [comment] 2018-07-16 13:49
We have no one maintaining the pm or make commands. That hasn't changed in > 1 year, so I'm closing all of the issues which are never going to get fixed anyway. Maybe closing the issue might draw enough attention that someone will decide to pick up the pm commands.

**Comment by joachim-n** [comment] 2018-07-16 14:39
I am sorely tempted to pick up the pm commands, because I find them tremendously useful, and even on D8 / Drush 9, I think it's extremely valuable to be able to do 'drush dl foo' and quickly try out foo module to see if it does what I need, without having to a) figure out which version number to tell Composer and how to say it b) having to wait 5 minutes while Composer thinks about things, and c) run the risk that Composer decides to delete half of my codebase (this has happened to me several times. I actually get quite anxious at the thought of doing ANYTHING with Composer).

The problem, as ever, is time and energy.

Consider me putting my name down to help, at least?

**Comment by greg-1-anderson** [comment] 2018-07-16 15:11
Maybe if we got multiple maintainers, we could solve some of the `pm-*` problems. If we did have community support for working on this, I would be down for reviewing PRs and providing guidance. There might be some open PRs waiting for review and/or tests. (#2227 provides a warning for this issue, but no fix; there may be other PRs that fix other pm issues that might be worth searching for.)

The first thing that would need to happen, once we had an estimate of how many engineering-hours we have volunteers for, is decide on the scope:

a) Critical fixes only just for Drush 8 and Drupal 7
b) Continue to support pm-* for use with Drush 9 and Drupal 8 as @joachim-n suggested above

If we're only doing `a`, then we could just merge critical bug fixes into the 8.x branch and make some `8.1.x` Drush releases to publish them. To continue `pm` with Drupal 8 would be another matter, though. The `pm` commands have not been ported to Drush 9, and in fact are out of scope for Drush 9. That will not change, and at some point in the future, Drush 8 will stop working with Drupal 8. There is potentially going to be an isp-supported fork of Drush 8 to extend its life for Drupal 8, but I wouldn't recommend attaching the pm commands to this effort either. Instead, I'd recommend using [g1a/starter](https://github.com/g1a/starter) to make a new project (maybe `drush-ops/pm`) that is a new standalone command, not a Drush extension.

The potential lifespan of `pm` on Drupal 8 is limited, though, and option `b` would be a lot of work. I'd recommend starting with option `a` (which might "happen to work" with Drupal 8 for a while), and consider higher-effort operations if successful with critical fixes, bearing in mind that in a year or two (maybe longer, who knows?), the pm commands will become completely useless on Drupal 8, because at some point it will be required to use composer to add any contrib module to Drupal.
