### ISSUE TITLE
drush up doesn't check that new requirements are satisfied

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2835] opened 2017-07-14 14:30 UTC
I used drush up to update search_api from an alpha version to the current stable, on Drupal core 8.2.

In between the alpha I had installed and the stable (1.2), the requirement for core was changed -- in the git log for Search API:

```
-  - system (>=8.2)
+  - system (>=8.3)
```
However, Drush didn't check for this and went ahead and installed the update.

**Comment by weitzman** [comment] 2018-09-02 14:45
pm commands that manage code are maint only, as drush9 no longer does any of that.

**Comment by weitzman** [comment] 2018-09-02 14:46
Also, dupe of #1285

**Closed by weitzman** 2018-09-02 14:45 UTC
Labels: area-pm, drupal8, type-feature
