### ISSUE TITLE
Update UpdateDBCommands::updateDoOne() to match changes in core

### ISSUE THREAD

**Issue by mdlutz24** [drush-ops/drush#6070] opened 2024-07-23 14:06 UTC
**Describe the solution you'd like**
In https://www.drupal.org/project/drupal/issues/3108658 Core made changes to the update_do_one function to support the situation where an update hook might be backported to some previous versions and not others. A new service was introduced to allow update hooks to declare that in some future version an equivalant update hook with a different number will exist and should not be run.  While core currently invokes this service and check in update_do_one, drush does not. As such current policy is to also do the check inside any potentially backportable update hook as well, until such time as the check can be executed in drush as well, and we can guarantee compatible versions of drush and core.

**Describe alternatives you've considered**

**Additional context**

**Comment by weitzman** [comment] 2024-07-23 14:08
Dupe of #6056

**Closed as completed by weitzman** 2024-07-23 14:08 UTC
