### ISSUE TITLE
Infinite loop with certain modules

### ISSUE THREAD

**Issue by rubenvarela** [drush-ops/drush#402] opened 2014-01-22 19:39 UTC
I'm running version 6.2.0.

I just ran into this issue, and I'm not sure if it's been reported before. 

    $:dr en cnr
    cnr was not found.                                                                                                                                                     [warning]
    The following projects provide some or all of the extensions not found:                                                                                                [ok]
    cnr
    Would you like to download them? (y/n): y
    Project cnr (7.x-4.22) downloaded to sites/all/modules/cnr.                                                                                                            [success]
    Project cnr contains a module named corresponding_node_references.
    cnr was not found.                                                                                                                                                     [warning]
    The following projects provide some or all of the extensions not found:                                                                                                [ok]
    cnr
    Would you like to download them? (y/n): y
    Install location sites/all/modules/cnr already exists. Do you want to overwrite it? (y/n): y
    Project cnr (7.x-4.22) downloaded to sites/all/modules/cnr.                                                                                                            [success]
    Project cnr contains a module named corresponding_node_references.
    cnr was not found.                                                                                                                                                     [warning]
    The following projects provide some or all of the extensions not found:                                                                                                [ok]
    cnr
    Would you like to download them? (y/n): n
    There were no extensions that could be enabled.                                                                                                                        [ok]

From what I can see and imagine how Drush works, the problem is that the `cnr` module doesn't have a `cnr`. The module in the project is called `corresponding_node_references`.

Just putting this out here in case someone wants to take a look.

**Comment by nignatov** [comment] 2015-06-01 12:59
I also have an infinite loop with version 6.2.0 and devel module.
I was able to represent the bug by changing the permission status of the sites/all/modules to 555. 
After that I execute the following command, without having the devel module into codebase: 

drush pm-enable devel --yes

output:
.....
devel was not found.                                                   [warning]
The following projects provide some or all of the extensions not            [ok]
found:
devel
devel was not found.                                                   [warning]
The following projects provide some or all of the extensions not            [ok]
found:
devel
devel was not found.                                                   [warning]
....

This caused the infinite loop.
I've changed the permissions because some of the hosting providers restrict the code base with only read permissions and if you forget for some reason to add a module but you add it for enablement in a custom distribution for example, you will start getting this error.
Instead of this infinite loop, it should be better to break the execution with error.

**Comment by weitzman** [comment] 2015-06-01 13:06
Your Drush is old. Please retry with latest.

**Comment by nignatov** [comment] 2015-06-01 13:12
I've just tried with 6.6 and get the same loop.
Do I need to try with 7.0 or?

**Comment by nignatov** [comment] 2015-06-01 13:18
As we wrote, I also tried with 7.0 and get the same loop.

**Comment by jonhattan** [comment] 2015-07-13 19:20
Duplicate of #5

**Closed by jonhattan** 2015-07-13 19:20 UTC
