### ISSUE TITLE
Unknown option: --uninstall on step 12-a while site-upgrade

### ISSUE THREAD

**Issue by petiar** [drush-ops/drush#1351] opened 2015-04-24 13:41 UTC
Hi everybody, I am trying to upgrade my site from Drupal 6 to Drupal 7 using drush, however, on step 12-a I am getting this error:

Unknown option: --uninstall.

right after disabling modules. The upgrade process stops. The drush version is 6.1.

Any help will be much appreciated. Thanks.

**Comment by greg-1-anderson** [comment] 2015-04-24 15:26
Duplicate of https://www.drupal.org/node/2074781

**Closed by greg-1-anderson** 2015-04-24 15:26 UTC
