### ISSUE TITLE
Drush sql-dump breaks for environments without bash

### ISSUE THREAD

**Issue by floretan** [drush-ops/drush#4009] opened 2019-03-22 12:13 UTC
**Describe the bug**
#3875 introduced a call to `bash` even when using another shell. For environments without bash (typically all docker-based environments with alpine-based images come with `sh`), existing call to `drush sql-dump --gzip` are now failing with the error `> sh: bash: not found` – an error that's quite confusing when working on a system with no bash.

**To Reproduce**
Call `drush sql-dump --gzip` on an environment without `bash installed.

**Expected behavior**
No fatal error.

**Actual behavior**
We get a fatal error: `> sh: bash: not found`

**Workaround**
It would be possible to set `sh.pipefail` in the configuration, but that shouldn't be needed to prevent fatal errors. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.x
| Drupal version? | 8.x
| PHP version     | 7.1
| OS             | Linux

**Comment by greg-1-anderson** [comment] 2019-03-22 13:34
Duplicate of #3874. See #3816 for background.

It is inconvenient for Drush to query the capabilities of remote machines; a PR to detect and automatically disable pipefail if the local machine does not include bash could be considered.

Note that if you do not have pipefail disabled in configuration, you can also disable it on the commandline:
```
drush -Dssh.pipefail='' sql-dump --gzip
```

**Closed by greg-1-anderson** 2019-03-22 13:34 UTC

**Comment by ceesgeene** [comment] 2022-12-05 20:38
Note that the option was rename from ssh.pipefail to sh.pipefail in #3874 ( https://github.com/drush-ops/drush/commit/7a4265ccf96373ede33c68ffd0e7f717861121d8 )

@greg-1-anderson was this a typo or intentional?
