### ISSUE TITLE
Can't get drush 9 aliases back to work after composer install

### ISSUE THREAD

**Issue by rotemreiss** [drush-ops/drush#3273] opened 2017-12-27 09:26 UTC
We have added some drush aliases for a multi-site project, the aliases were converted from the previous syntax to the Drush 9 syntax (.yml files).

I went over the [documentation][1], and also saw the previous issues, notes and changes on [this GitHub issue][2].

For some reason the aliases didn't work inside `$ROOT/../drush/sites` as documented, but did work inside `$ROOT/drush/sites`, and I also had to use the format of `[site].alias.yml` and not `[site].site.yml` as on the documentation.

Another thing is that @greg-1-anderson wrote on [his comment][3] that 

> Only ~/.drush/sites et. al. are searched now.

So now I am really lost between the documentation, the comments, and the aliases that **worked last week** and were broken now after composer install.

Can someone please tell me what am I missing here?

** I've also tried to place the aliases in `~/.drush/sites/` (which didn't work).

  [1]: https://github.com/drush-ops/drush/blob/master/examples/example.site.yml
  [2]: https://github.com/drush-ops/drush/issues/3107#issuecomment-340040803
  [3]: https://github.com/drush-ops/drush/issues/3107#issuecomment-346429143

**Comment by weitzman** [comment] 2017-12-27 16:36
What version of drush are you using? Please paste output of `composer show
drush/drush`

**Comment by greg-1-anderson** [comment] 2017-12-27 16:55
Duplicate of [aliases stop working after composer install](https://drupal.stackexchange.com/questions/252751/aliases-stop-working-after-composer-install/252775#252775) on Drupal Stack Exchange. Saw this there first.

**Closed** 2017-12-27 16:56 UTC
