### ISSUE TITLE
Drush fails with cryptic database error, if database client binary isn't in PATH

### ISSUE THREAD

**Issue by dorianmuthig** [drush-ops/drush#1471] opened 2015-07-03 22:54 UTC
When running any command which requires accessing the database, the command fails with a cryptic error, if the command line client for the database engine used isn't available in the current path.

```bash
$ drush up
Command pm-update needs a higher bootstrap level to run - you will   [error]
need to invoke drush from a more functional Drupal environment to run
this command.
The drush command 'up' could not be executed.                        [error]
Drush was not able to start (bootstrap) the Drupal database.         [error]
Hint: This may occur when Drush is trying to:
 * bootstrap a site that has not been installed or does not have a
configured database. In this case you can select another site with a
working database setup by specifying the URI to use with the --uri
parameter on the command line. See `drush topic docs-aliases` for
details.
 * connect the database through a socket. The socket file may be
wrong or the php-cli may have no access to it in a jailed shell. See
http://drupal.org/node/1428638 for details.

Drush was attempting to connect to: 
 Drupal version         :  7.38                                     
 Site URI               :  http://default                           
 Database driver        :  mysql                                    
 Database hostname      :  127.0.0.1                                
 Database port          :  3306                                     
 Database username      :  drupal7                              
 Database name          :  drupal7                              
 PHP executable         :  /usr/local/bin/php                       
 PHP configuration      :  /usr/local/etc/php/5.6/php.ini           
 PHP OS                 :  Darwin                                   
 Drush script           :  /usr/local/Cellar/drush/7.0.0/libexec/dr 
                           ush.php                                  
 Drush version          :  7.0.0                                    
 Drush temp directory   :  /tmp                                     
 Drush configuration    :                                           
 Drush alias files      :                                           
 Drupal root            :  /Library/WebServer/Documents/drupal7  
 Site path              :  sites/default                            

$
```

The error message provided is further rather cryptic and directs the user to visit [an old post on the official Drupal "Issues" site](https://www.drupal.org/node/1428638), where there is talk of jail shells, which have the binary available but no access to system sockets. Not only is this not helpful, but I found it to be quite strange, that no attempt was made to locate the `mysql` binary in typical install locations (it was present on the system) when the installers from https://dev.mysql.com/downloads/ have been used ([homebrew](https://github.com/Homebrew/homebrew) sets up the paths and links properly, though).

I would propose adding a list of common install locations to the scripts which can be tried to locate binaries which do not appear in PATH nor have been otherwise made available in the shell's current context.
I would also suggest changing the error message and/or distinctly making sure to handle the errors the shell system or run applications return instead of blindly guessing what went wrong, and spitting out an "unknown error" message with more detailed diagnostic information about what commands have failed and/or were last run, if the specific error case wasn't precisely handled this way.

**Comment by weitzman** [comment] 2015-07-06 14:38
Dupe of #1042

**Closed by weitzman** 2015-07-06 14:38 UTC

**Comment by dorianmuthig** [comment] 2015-07-07 20:39
Not really a duplicate. Similar, sure...
Binary *was present* in my case, so discovery would've been possible.

**Comment by emb03** [comment] 2015-07-29 17:39
I am experiencing this error and nothing I have found so far fixes it. Can you update the error text with links on this post so we can try to locate the right scripts as you suggest: 
> "adding a list of common install locations to the scripts which can be tried to locate binaries which do not appear in PATH nor have been otherwise made available in the shell's current context."

Thanks
