### ISSUE TITLE
Alias config merging/issues.

### ISSUE THREAD

**Issue by dpagini** [drush-ops/drush#4424] opened 2020-05-28 20:23 UTC
**Describe the bug**
I have been having a lot of trouble trying to configure drush to work for multisite, while trying to only have "config keys" specified in one single place.
I've learned I can have a `common` key for each `*.site.yml` file to share common config that way. That's great, but if I have 5 sites, I need 5 `common` entries.

One thing I noticed is that my `common` key in my `self.site.yml` file is being shared to my other sites. So take for example...

self.site.yml:
```yml
common:
  test: dave

dev:
  uri: example.com
```

my.site.yml
```yml
test:
  uri: sub.example.com
```

When I run `$ drush sa @my.test`, the output I get is:
```
'@my.test':
  test: dave
  uri: sub.example.com
```

So you can see that `test: dave` shouldn't really be there (or is that by design?). 

If it's by design GREAT! That's what I want. However, instead of `test: dave` let's pretend that's the host key, and when I run `$ drush @my.test ssh` it won't connect. It seems like it doesn't use the keys, even though the `$ drush sa` command is reporting they're there.

So I think it's important to answer the above "by design" question first... if it's by design, then `$ drush sa` is properly reporting the properties, but the drush commands don't seem to be using them correctly.
If it's not by design, it seems like `$ drush sa` shouldn't be reporting those key/values.
Additionally, it would be great to make values a little more "shareable". I know I can set variables, but those seem to me to be simple values (strings/integers) and not an entire configure tree at once.

Thoughts?

**Workaround**
??

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.2.2
| Drupal version? | 8.8
| PHP version     | 7.2
| OS?             | Linux

**Comment by greg-1-anderson** [comment] 2020-05-28 21:17
It is by design that you can, without cwd set, use `@my.test`, and Drush will find the root from the alias `my.site.yml` and the url from the `test` entry in self.site.yml.

The thing that isn't exactly by design is merging `common` between my.site.yml and `self.site.yml`. If both files have `common` entries, how are they merged? Should my.site.yml be more important than self.site.yml, or visa-versa?

The answer to how well defined all of this is can be found in the tests of consolidation/site-alias. PRs welcome there.

**Comment by dpagini** [comment] 2020-05-28 21:54
Thanks for the quick reply @greg-1-anderson! I'm not entirely sure I understand what you're saying here though...?

First, I'll admit I'm not sure what "setting cwd" means...?

> use @my.test, and Drush will find the root from the alias my.site.yml

What do you mean here? This is drush auto-detecting where Drupal is installed? Or a config option named `root`? I'm not sure what you mean....

---

So what I'm a little confused about is my last sentences, and where I think the bug is. While I'm "debugging" these aliases with `$ drush sa @my.test` I can see options that are set, but those options are ignored/not used when running actual commands. There's a bug somewhere there, right?

**Comment by greg-1-anderson** [comment] 2020-05-28 22:51
"without cwd set" means not using `cd` to change your working directory to your Drupal root. Drush will find aliases e.g. `my.site.yml` in your `~/.drush/sites` directory.

If your `my.site.yml` has set a `root` attribute in its default environment, AND you have an environment `foo` in the `self.site.yml` file, AND you use `@my.foo`, then Drush will use `root` from `my.site.yml` and the `foo` record from `self.site.yml` and give you a `my.foo` record.

This is the ONLY cross-yml file merging that is done by design (and the only thing that's really merged is the `root` attribute from the `my.site.yml` file). Any merging that happens between different site.yml files, e.g. the `common` attribute, is a side effect of the expressed code, which only intends to merge common from within the same file.

The `parent` concept from the earlier implementation of aliases was deliberately removed to reduce complexity. If we re-introduce merging as a supported feature, we should be clear on how it works and what the priority scheme and use cases are.

**Comment by dpagini** [comment] 2020-06-08 15:11
I just feel like there's still a lot of merging happening (and I cant figure out if it's accidental or not). I want to edit what I said in the original, which is confusing me even more...

self.site.yml:
```yml
common:
  name: dave

dev:
  uri: example.com

test:
  uri: someurl.org
```

my.site.yml
```yml
test:
  uri: sub.example.com
```

When I run `$ drush sa @my.test`, the output I get is:
```
'@my.test':
  name: dave
  uri: someurl.org
```

**Notice that the URI is being picked up from the `@self` file, and I can't override this from `@my` alias file!**

**Comment by greg-1-anderson** [comment] 2020-06-08 15:27
Looks like precedence is reversed during the merge.

**Closed** 2021-09-21 00:18 UTC
