### ISSUE TITLE
pm-update under Windows 8, IIS & SQL Server

### ISSUE THREAD

**Issue by virusakos** [drush-ops/drush#596] opened 2014-04-22 18:51 UTC
I'm trying to update drupal core 7.26 to 7.27 with pm-update but it fails.
My environment is Windows 8, IIS & SQL Server.

Here is the command output:
 Name    Installed Version  Proposed version  Message
 Drupal  7.26               7.27              SECURITY UPDATE available

Update information last refreshed: Tue, 04/22/2014 - 21:20
Code updates will be made to drupal core.
WARNING:  Updating core will discard any modifications made to Drupal core files
, most noteworthy among these are .htaccess and robots.txt.  If you have made an
y modifications to these files, please back them up before updating so that you
can re-create your modifications in the updated version of the file.
Note: Updating core can potentially break your site. It is NOT recommended to up
date production sites without prior testing.

Do you really want to continue? (y/n): y
Project drupal was updated successfully. Installed version is now 7.27.
Backups were saved into the directory                                       [ok]

C:\Users\Charis/drush-backups/acquiadrupal7909/20140422184056/drupal.
require_once(C:/Users/Charis/Documents/acquia-drupal7/includes/database/sqlsrv/d
atabase.inc):  [warning]
failed to open stream: No such file or directory database.inc:1685
Drush command terminated abnormally due to an unrecoverable error.       [error]

Error: require_once(): Failed opening required
'C:/Users/Charis/Documents/acquia-drupal7/includes/database/sqlsrv/database.inc'

(include_path='.;C:\php\pear') in
C:\Users\Charis\Documents\acquia-drupal7\includes\database\database.inc,
line 1685
The external command could not be executed due to an application         [error]

error.
Backups were restored successfully.                                         [ok]

Anyone knows what is going wrong?

**Comment by liezie** [comment] 2015-02-26 12:56
I can confirm the same problem. 
Drush removes the database includes when updating core and then fails because it can't find them. 
At this point the site is completely broken and you have to manually copy the drupal files on the server.

**Comment by llayman** [comment] 2015-02-26 14:44
this issue has been open for 10 months now... would it be possible to get some sort of response from dev?

**Comment by virusakos** [comment] 2015-06-25 15:52
Still no luck with this issue

**Comment by jonhattan** [comment] 2015-06-25 20:06
Please test #1464.

I don't know how a clean workflow to test the PR on windows looks like. Hope you can figure it out. 

Note also that the PR doesn't fixes the issue by itself. It provides an example command (examples/pm_update.drush.inc) you must copy to one of drush commandfiles locations. Once again, I don't know which locations are valid on windows. After placing the commandfile, perform `drush cc drush` before trying to update again.

**Comment by jonhattan** [comment] 2015-06-26 09:50
The PR was merged

**Closed by jonhattan** 2015-06-26 09:50 UTC
Labels: area-pm
