### ISSUE TITLE
Drush SQL commands should ignore psqlrc

### ISSUE THREAD

**Issue by Chi-teck** [drush-ops/drush#5585] opened 2023-05-23 08:33 UTC
### Problem
Most of drush sql:* commands wrongly expect psql to have default configuration.

For example, I have the following psqlrc config.
```
\set QUIET on

\t off
\pset linestyle unicode
\pset border 2
\pset null 'null'
\pset format wrapped

\set PROMPT1 '%[%033[1;93;1m%]%n%m:%>%[%033[0m%]/%[%033[1;92;1m%]%/%[%033[0m%]%[%033[1;91;1m%]%x%[%033[0m%]%[%033[1;90;1m%]%#%[%033[0m%] '
\set PROMPT2 '%[%033[1;90;1m%]%#%[%033[0m%] '

\set HISTCONTROL ignoreboth
\set HISTSIZE 50000

\timing on

\set QUIET off
```

The above config adds some decorations to psql output that may break some SQL commands that Drush executes internally.

```
┌─────┬──────────────────────────────────────┬──────────┐
│ uid │                 uuid                 │ langcode │
├─────┼──────────────────────────────────────┼──────────┤
│   0 │ 96dd3481-1c31-4ecf-a63c-3158828122b2 │ en       │
│   1 │ 2fab5b86-915e-4b8a-9c3d-abe3801aacf7 │ en       │
└─────┴──────────────────────────────────────┴──────────┘
(2 rows)

Time: 0.305 ms
```

For instance `drush:sql-drop` fails because it cannot obtain list of tables to drop.

### Proposed solution
The quick fix seems trivial. Just add `-X` (`--no-psqlrc`) to [psql command](https://github.com/drush-ops/drush/blob/12.0.0-rc1/src/Sql/SqlPgsql.php#L47).

However, for commands like `drush:sql-query` or `drush:sql-cli` (interactive mode) it might still make sense to keep the user defined psqlrc configuration.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 12.x
| Drupal version? | 10.x
| PHP version     | 8.x
| OS?             | Linux

**Comment by weitzman** [comment] 2023-05-23 11:46
Dupe of #5545.

**Closed as completed by weitzman** 2023-05-23 11:46 UTC
