### ISSUE TITLE
multisite with symlink confuses drush

### ISSUE THREAD

**Issue by agnarodegard** [drush-ops/drush#221] opened 2013-10-29 14:10 UTC
I've migrated a site to a new multisite installation. I've got

<pre>
sites/default
sites/all
sites/mysite
</pre>

Master site is installed in default and for mysite to work I need to make a symlink in drupal root

<pre>
ln -s . mysite
</pre>

However, when I try to make an archive-dump it seems to just loop and go on forever. Removing the symlinks creates the dump as expected, but I hope there is another way.

**Comment by JGrubb** [comment] 2015-09-21 13:39
I've been having this issue as well, which I've been working around by creating remote aliases for the sites on my local machine.  If you need to do something on the server, this problem strikes.  If you try running the whole site group from anywhere on the server, it strikes.

`drush @sites # hangs`

If you specify which site to run the command on (from outside the Drupal directory, ie your home dir), it'll work

`drush @sites.which_site # works`

If you `cd` into the Drupal sites/* directory for that site, it'll hang.

`jgrubb@690elwb04:/var/www/docroot/sites/site.net$ drush ucrt --help # hangs`

If however, you use the alias from the same place, it works.

jgrubb@690elwb04:/var/www/docroot/sites/site.net$ drush @sites.site ucrt --help # works`

I ran an strace on the drush pid when it's hanging and it looks like drush is looping over all the files in the sites/*/files directory every time you try to run it.

~~~
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/177271", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/177271", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
getdents(8, /* 3 entries */, 32768)     = 72
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/177271/meta", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/177271/meta", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
getdents(9, /* 2 entries */, 32768)     = 48
getdents(9, /* 0 entries */, 32768)     = 0
close(9)                                = 0
getdents(8, /* 0 entries */, 32768)     = 0
close(8)                                = 0
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/64226", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/64226", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
getdents(8, /* 3 entries */, 32768)     = 72
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/64226/meta", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/64226/meta", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
getdents(9, /* 2 entries */, 32768)     = 48
getdents(9, /* 0 entries */, 32768)     = 0
close(9)                                = 0
getdents(8, /* 0 entries */, 32768)     = 0
close(8)                                = 0
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/63256", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/63256", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
getdents(8, /* 3 entries */, 32768)     = 72
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/63256/meta", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/63256/meta", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
getdents(9, /* 2 entries */, 32768)     = 48
getdents(9, /* 0 entries */, 32768)     = 0
close(9)                                = 0
getdents(8, /* 0 entries */, 32768)     = 0
close(8)                                = 0
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/25071", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/25071", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 8
getdents(8, /* 3 entries */, 32768)     = 72
stat("/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/25071/meta", {st_mode=S_IFDIR|0775, st_size=4096, ...}) = 0
openat(AT_FDCWD, "/var/www/cascade/prod/brandsites_multi.com/htdocs/docroot/sites/manufacturing.net/files/Wall_Charts/25071/meta", O_RDONLY|O_NONBLOCK|O_DIRECTORY|O_CLOEXEC) = 9
getdents(9, /* 2 entries */, 32768)     = 48
getdents(9, ^CProcess 4217 detached
~~~

**Comment by mariagwyn** [comment] 2015-10-20 18:44
Confirming this as an issue, at least in Drush 8. If a site has a symlink in the docrook, like this:
```multisitename -> .```

The following command hangs:
```drush8 sa @sites```

The same on drush7 works without error.

However, removing @sites from 'sa' works without error. That won't solve it for everyone, but ```sa --local ``` works.

**Comment by agnarodegard** [comment] 2015-10-20 18:46
feeds
feeds_et
feeds_ex

Mvh
Agnar Ødegård
Norweb AS

----- Opprinnelig melding -----
Fra: "Maria McDowell" <notifications@github.com>
Til: "drush-ops/drush" <drush@noreply.github.com>
Kopi: "Agnar Ødegård" <agnar@norweb.no>
Sendt: 20. oktober 2015 20:44:59
Emne: Re: [drush] multisite with symlink confuses drush (#221)



Confirming this as an issue, at least in Drush 8. If a site has a symlink in the docrook, like this: 
multisitename -> . 

The following command hangs: 
drush8 sa @sites 

The same on drush7 works without error. 

However, removing @sites from 'sa' works without error. That won't solve it for everyone, but sa --local works.

**Comment by weitzman** [comment] 2015-10-22 18:00
My understanding is that this is a bug when you have a symlink in the root dir and you use @sites. Thats such an oddball combination that I dont think the maintainers will pursue it. PRs welcome.

Note that Drush recursing into the files dir was fixed in RC1.

**Comment by JGrubb** [comment] 2015-11-20 17:09
I can confirm that this bug is fixed in the current master.

**Comment by pdecat** [comment] 2016-01-18 14:13
Hi,

passing `--preserve-symlinks` to `archive-dump` works fine with drush 7.1.0.

**Comment by pdscti** [comment] 2016-09-15 14:51
I've added a PR for a simple change that will prevent Drush infinitely looping through symlinks: don't know if this solution has been suggested and rejected before.

#2343

**Comment by richardbporter** [comment] 2016-10-04 13:57
I think this is a pretty common use case considering it is the recommended approach for subdirectory multisites: https://www.drupal.org/docs/7/multisite-drupal/multi-site-in-subdirectories

Oddly, it doesn't happen when running drush commands through an alias, even though the alias for a multisite has the same root path. 

Is there any combination of global options that will prevent this from happening? I tried search-depth=0 but that did not seem to work.

**Comment by kcolwell** [comment] 2016-10-17 13:24
Hi,

I just ran into this problem and it's moderately ouchy. I've been using this setup for years as it was the recommended way of configuring a multisite.

Running drush @sites status <--- just results in a giant looping php process

with something like this appearing after a long time: 

opendir(/web/webstu.onu.edu/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/asme/ama/ncpa/asme/asme/asme/asme/asme/asce/rose/sites/all/modules/ctools/js):[warning]
failed to open dir: No such file or directory filesystem.inc:685

Setting up an drush alias file and adding each site as an alias and then calling the following now works as an alternative: drush @webstu status

**Comment by humansky** [comment] 2016-12-02 04:15
Don't mean to bring up an old issue, but I've been struggling with this issue for some time now and figured out a workaround without having to create a alias for each site. I used the **--exclude** option with drush and it ignored the symlinked site. For example:

```bash
$ drush @sites --exclude=subdir1,subdir2,subdir3 status
```

Or if you are like me and forget to add that option every time you run drush, you can add this snippet to your global drush config file. In the ~/.drush/drushrc.php file, add the following option:

```php
<?php

$options['exclude'] = 'subdir1,subdir2,subdir3';
```

Hope this helps!

**Comment by richardbporter** [comment] 2016-12-05 21:07
@humansky Thanks, that works!

**Comment by Loguercio** [comment] 2017-10-05 16:11
@kcolwell would you mind elaborating on your site alias solution?

**Comment by kcolwell** [comment] 2017-10-05 16:36
Here is kind of what I'm doing: https://praxent.com/blog/drush-aliases-what-why-and-how

I created a file in ~/.drush named webstu.aliases.drushrc.php 

It contains a giant list that looks like this:

/*
* Instead of drush @sites which doesn't work anymore use drush @webstu
*/
$root = '/web/webstu.onu.edu';
$aliases['aasu'] = array('root' => $root,'uri' => 'webstu.onu.edu.aasu');
$aliases['acm'] = array('root' => $root,'uri' => 'webstu.onu.edu.acm');
$aliases['affp'] = array('root' => $root,'uri' => 'webstu.onu.edu.affp');

Then you run the alias by using drush @webstu status or rush @webstu up 

Thanks and good luck!

kc

**Comment by joachim-n** [comment] 2018-11-14 14:54
I use the same setup as the OP, with a symlink in the docroot to itself to make the browser think the subsite is in a subfolder.

Drush works fine with this for me, and has done for some time (since Drupal 7 at least).

**Closed** 2023-09-14 09:03 UTC
Labels: type-bug, pri-low, stat-needs-work
