### ISSUE TITLE
sql-sync throwing a PHP Fatal Error

### ISSUE THREAD

**Issue by rickysarraf** [drush-ops/drush#2520] opened 2016-12-27 18:20 UTC
Just from the looks of this error, it gives no clue of the actual cause of the failure. In fact, it'll mislead on why mysql ssl is in the picture. The issue is with php-mysql being unavailable.

```
rrs@learner:~$ drush.phar rsync --delete --verbose @staging_rhut @dev_rhut
You will delete files in /home/rrs/public_html/drush/rhut_dev/ and replace with data from /home/rrs/public_html/drush/rhut_staging//
Do you really want to continue? (y/n): y
sending incremental file list

sent 110 bytes  received 14 bytes  248.00 bytes/sec
total size is 0  speedup is 0.00
2016-12-27 / 23:38:23 ♒♒♒  ☺  
rrs@learner:~$ drush.phar sql-sync @staging_rhut @dev_rhut
You will destroy data in rhut_dev and replace with data from rhut_staging.
Do you really want to continue? (y/n): y
Starting to dump database on Source.                                               [ok]
PHP Fatal error:  Uncaught Error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/Sqlmysql.php:56
Stack trace:
#0 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/SqlBase.php(164): Drush\Sql\Sqlmysql->creds()
#1 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/Sqlmysql.php(115): Drush\Sql\SqlBase->query('SHOW TABLES;')
#2 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/SqlBase.php(318): Drush\Sql\Sqlmysql->listTables()
#3 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/SqlBase.php(62): Drush\Sql\SqlBase->get_expanded_table_selection()
#4 phar:///home/rrs/bin/drush.phar/commands/sql/sql.drush.inc(262): Drush\Sql\SqlBase->dump(true)
#5 phar:///home/rrs/bin/drush.phar/includes/command.inc(422): drush_sql_dump()
#6 phar:///home/rrs/bin/drush.phar/includes/command.inc(231): _drush_invoke_hooks(Array, Array)
#7 phar:///home/rrs/bin/drush.phar/includes/command.inc(199): drush_command()
#8 phar:///home/rrs/bin/drush.phar/lib/Drush/Boot/BaseBoot.php(67): drush_dispatch(Array)
#9 phar:///home/rrs/bin/ in phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/Sqlmysql.php on line 56
Drush command terminated abnormally due to an unrecoverable error.                 [error]
Error: Uncaught Error: Undefined class constant 'MYSQL_ATTR_SSL_CA' in
phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/Sqlmysql.php:56
Stack trace:
#0 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/SqlBase.php(164):
Drush\Sql\Sqlmysql->creds()
#1 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/Sqlmysql.php(115):
Drush\Sql\SqlBase->query('SHOW TABLES;')
#2 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/SqlBase.php(318):
Drush\Sql\Sqlmysql->listTables()
#3 phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/SqlBase.php(62):
Drush\Sql\SqlBase->get_expanded_table_selection()
#4 phar:///home/rrs/bin/drush.phar/commands/sql/sql.drush.inc(262):
Drush\Sql\SqlBase->dump(true)
#5 phar:///home/rrs/bin/drush.phar/includes/command.inc(422): drush_sql_dump()
#6 phar:///home/rrs/bin/drush.phar/includes/command.inc(231):
_drush_invoke_hooks(Array, Array)
#7 phar:///home/rrs/bin/drush.phar/includes/command.inc(199): drush_command()
#8 phar:///home/rrs/bin/drush.phar/lib/Drush/Boot/BaseBoot.php(67):
drush_dispatch(Array)
#9 phar:///home/rrs/bin/ in
phar:///home/rrs/bin/drush.phar/lib/Drush/Sql/Sqlmysql.php, line 56
sql-dump failed.                                                                   [error]
2016-12-27 / 23:38:34 ♒♒♒  ☹  => 1  
```

**Comment by weitzman** [comment] 2016-12-27 18:21
Dupe of #1371

**Closed by weitzman** 2016-12-27 18:21 UTC
