### ISSUE TITLE
Drush 8 compatibility warning with PHP 8.0

### ISSUE THREAD

**Issue by lesleyfernandes** [drush-ops/drush#5275] opened 2022-10-14 12:15 UTC
**Describe the bug**
I am getting these warnings when running drush updatedb on PHP8:
`Deprecated: Required parameter $args follows optional parameter $command in /var/www/html/vendor/drush/drush/commands/core/drupal/batch_7.inc on line 19`

`PHP Deprecated:  Required parameter $options follows optional parameter $command in /var/www/html/vendor/drush/drush/commands/core/drupal/batch_7.inc on line 19
`

**To Reproduce**
- Install PHP 8
- Install Drush Version:  8.4.10 
- Run drush updatedb

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 8.4.10
| Drupal version? | 7.92
| PHP version     | 8.0.21
| OS?             | Linux

**Comment by mbomb007** [comment] 2022-10-20 13:59
Basically a duplicate of https://github.com/drush-ops/drush/issues/5196. Consider adding the error messages or +1 there.

**Comment by greg-1-anderson** [comment] 2023-01-21 18:44
Fixed in 73ecb31e2e

**Closed as completed by greg-1-anderson** 2023-01-21 18:44 UTC
Labels: drush8
