### ISSUE TITLE
Drush uses incorrect PHP version on updatedb command

### ISSUE THREAD

**Issue by imyaro** [drush-ops/drush#4936] opened 2021-12-17 07:03 UTC
**Describe the bug**
I’m using multiple PHP versions on my server (Running Linux)
1. /usr/bin/php - php 7.1
2. /usr/bin/php7.4 - php 7.4

When I’m trying to run drush with the specific 7.4 version, `drush status` shows:

```
> /usr/bin/php7.4 ./bin/drush status
 Drupal version   : 9.3.0
 PHP binary       : /usr/bin/php7.4
 PHP config       : /etc/php/7.4/cli/php.ini
```

So - when I’m running drush from `/usr/bin/php7.4 drush` it uses php 7.4 version - it works correct

But when I’m trying to run `/usr/bin/php7.4 drush updb` I get:

```>/usr/bin/php7.4 ./bin/drush updb
In Process.php line 269:
  The command "/path/to/site/root/vendor/drush/drush/drush updatedb:status --no-entity-updates --uri=default --root=/path/to/site/root
  web" failed.
  Exit Code: 255(Unknown error)
  Working directory:

  Error Output:
  ================
  Composer detected issues in your platform:

  Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.1.33.

  PHP Fatal error:  Composer detected issues in your platform: Your Composer dependencies require a PHP version ">= 7.3.0". You are running 7.1.33 in /path/to/site/root/vendor/composer/platform_check.php on line 24
``` 

**To Reproduce**
1. Install several PHP versions in the system
2. Try to run `drush updb` commandusing from php which is not in location from `which php`

**Expected behavior**
Drush should use the specified version of PHP or path to the php executable could be defined in the arguments.

**Actual behavior**
Drush uses default pph version

**Workaround**
I didn’t find a workaround for it. Also I didn’t find any woking solutions on stackoverflow.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 9.3.0
| PHP version     | 7.1 / 7.3
| OS?             | Linux

**Comment by ivnish** [comment] 2021-12-17 07:17
Same problem. Only with "updb"

**Comment by Chi-teck** [comment] 2021-12-17 08:50
> To use a non-default PHP, edit ~/.bashrc so that the desired PHP is in front of your $PATH. If that is not desirable, you can change your PATH for just one request: PATH=/path/to/php:$PATH drush status ...`

https://www.drush.org/latest/install/

Closing as duplicate of #4532.

**Closed by Chi-teck** 2021-12-17 08:50 UTC

**Comment by imyaro** [comment] 2021-12-24 13:00
What if I cannot change the PHP version in `.bashrc` file?
I have several sites running different PHP versions at the single server. And I cannot just change version for all the sites or use different linux user to have different `.bashrc` files.

**Comment by ramonibuildings** [comment] 2022-01-27 09:48
@imyaro I had the same question, but the [latest documentation](https://www.drush.org/latest/install/) told me this: 

> If that is not desirable, you can change your PATH for just one request: PATH=/path/to/php:$PATH drush status ...`

**Comment by drastik** [comment] 2022-07-19 05:16
Same issue persists in Drush 11.

This is not merely an issue of specifying PATH (side note: that doesn't work on this specific command 'updb' either).

You can specify PHP version per drush command with others, such as cim, uli, and so forth.  Only updb throws this error of the handful I've tried.  The other commands successfully obey your specified PHP version.

More examples of commands for clarity:
```
/usr/bin/php8.1 ./vendor/drush/drush/drush updb
/usr/bin/php8.1 /usr/local/bin/drush updb
```
etc

I will create a new issue because these are being closed without looking into the specifics being discussed that it is ONLY for updb command.
