### ISSUE TITLE
FAILL `MISS TABLE COLUMN_STATISTICS` mysqldump Ver 8.0+ on ubuntu0.20.04

### ISSUE THREAD

**Issue by politsin** [drush-ops/drush#4426] opened 2020-05-29 12:37 UTC
**Describe the bug**

Fail on `drush sql:dump` and have no opportunity to work around with `mysqldump --column-statistics=0 `

See https://serverfault.com/questions/912162/mysqldump-throws-unknown-table-column-statistics-in-information-schema-1109

drush does-not support MySQL config file, such as /etc/my.cnf or ~/.my.cnf.
```
[mysqldump]
column-statistics=0
```

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.2
| Drupal version? | 8.x
| PHP version     | 7.4
| OS?             | Ubuntu 20.4

**Comment by weitzman** [comment] 2020-06-30 19:54
Dupe of #4440 

> drush does-not support MySQL config file, such as /etc/my.cnf or ~/.my.cnf.

Yes it does.

**Closed by weitzman** 2020-06-30 19:54 UTC

**Comment by politsin** [comment] 2020-06-30 23:20
problem still exists.
No way to make a sql-dump.

**Comment by politsin** [comment] 2020-06-30 23:23
Duplicate of #4410, not #4440
