### ISSUE TITLE
Drush fails to detect sites other than default when a site-local drush is installed

### ISSUE THREAD

**Issue by fago** [drush-ops/drush#2285] opened 2016-07-21 09:33 UTC
Similar as reported in #2070, detecting multi-site directories does not work when a site-local drush is in use. The reason is that a global drush 8 automatically picks the site-local drush up, but loses the directory context while doing so.

Steps to reproduce:
- Install site-local drush via composer
- Install global drush 8.*
- Go into a working multi-site directory, like sites/my-site and run "drush st".

**Expected:**
A output of  `Drupal Settings File          :  sites/my-site/settings.php`  
**Actual behaviour:**
`Drupal Settings File          :  sites/default/settings.php`

**Comment by fago** [comment] 2016-07-21 09:48
Looks like there is simply a chdir() call causing that. It looks like thes chdir() is even unnecessary, in my tests removing it did not cause any troubles and fixed the problem.

See PR2286

**Comment by weitzman** [comment] 2016-07-21 20:46
I'm working on a D8 multisite now, and I have not experienced this problem. I also call a global Drush which hands off to a site-local Drush. On D8 a sites.php is required in order for multisite to work. I mention that in case you are running D8.

Any chance you can zip up your site and send to me? Don't think I need the DB or uploaded files. If not, running with --debug might provide insights.

**Comment by fago** [comment] 2016-07-22 07:35
The problem appears on a Drupal 7 site. Unfortunately I cannot share the site, but it has sites.php configured as well. I can check whether this is redrocuable on a plain drupal 7, but I very much think so.

Here is the drush st --debug output in case it helps:

```
drush st --debug 
Using the Drush script found at /path/to/drupal/root/vendor/drush/drush/drush.launcher using pcntl_exec
Loading drushrc "/home/fago/.drush/drushrc.php" into "home.drush" scope. [0 sec, 3.79 MB]                                        [bootstrap]
Loading drushrc "/home/fago/.drush/drudrush/drushrc.php" into "custom" scope. [0.01 sec, 3.79 MB]                                [bootstrap]
Cache HIT cid: 8.0.5-commandfiles-0-26b8001111e3480fa6c27b7b14ecc42c [0.01 sec, 3.87 MB]                                             [debug]
Loading drushrc "/path/to/drupal/root/web/sites/all/drush/drushrc.php" into "drupal" scope. [0.03 sec, 7.96 MB]          [bootstrap]
Bootstrap to phase 0. [0.17 sec, 10.85 MB]                                                                                       [bootstrap]
Trying to bootstrap as far as we can. [0.17 sec, 10.86 MB]                                                                           [debug]
Drush bootstrap phase : bootstrap_drupal_root() [0.18 sec, 11.31 MB]                                                             [bootstrap]
Loading drushrc "/path/to/drupal/root/web/sites/all/drush/drushrc.php" into "drupal" scope. [0.18 sec, 11.31 MB]         [bootstrap]
Initialized Drupal 7.44 root directory at /path/to/drupal/root/web [0.18 sec, 11.31 MB]                                  [bootstrap]
Find command files for phase 1 (max=7) [0.18 sec, 8.48 MB]                                                                           [debug]
Cache HIT cid: 8.0.5-commandfiles-1-07aead10e03a07e47ed30ffa3962a7bf [0.19 sec, 8.49 MB]                                             [debug]
Drush bootstrap phase : bootstrap_drupal_site() [0.22 sec, 8.52 MB]                                                              [bootstrap]
Initialized Drupal site default at sites/default [0.22 sec, 8.52 MB]                                                             [bootstrap]
Find command files for phase 2 (max=7) [0.22 sec, 8.52 MB]                                                                           [debug]
Drush bootstrap phase : bootstrap_drupal_configuration() [0.22 sec, 8.52 MB]                                                     [bootstrap]
Find command files for phase 3 (max=7) [0.23 sec, 8.62 MB]                                                                           [debug]
sql-query: SELECT 1; [0.23 sec, 8.75 MB]                                                                                            [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_knT2V6 --database=.. --host=...local --silent  < /tmp/drush_HmcG93
  1
sql-query: SHOW TABLES; [0.23 sec, 8.76 MB]                                                                                         [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_6B8bxc --database=.. --host=...local --silent  < /tmp/drush_a9CBJ9
  actions
  authmap
  batch
  block
  block_custom
  block_node_type
  block_role
  blocked_ips
  cache
  cache_admin_menu
  cache_block
  cache_bootstrap
  cache_entity_comment
  cache_entity_file
 ....
Drush bootstrap phase : bootstrap_drupal_database() [0.28 sec, 8.88 MB]                                                          [bootstrap]
Successfully connected to the Drupal database. [0.28 sec, 9.49 MB]                                                               [bootstrap]
Find command files for phase 4 (max=7) [0.28 sec, 9.49 MB]                                                                           [debug]
Drush bootstrap phase : bootstrap_drupal_full() [0.28 sec, 9.49 MB]                                                              [bootstrap]
Cache HIT cid: 8.0.5-install_profile-66ecfeb9791a023150773849f1550c5d [0.66 sec, 58.74 MB]                                           [debug]
Find command files for phase 5 (max=7) [0.66 sec, 58.74 MB]                                                                          [debug]
Cache HIT cid: 8.0.5-install_profile-66ecfeb9791a023150773849f1550c5d [0.66 sec, 58.74 MB]                                           [debug]
Cache HIT cid: 8.0.5-commandfiles-5-ec91674843f7c2ecd5049a194fa8c46b [0.67 sec, 58.8 MB]                                             [debug]
Drush bootstrap phase : bootstrap_drupal_login() [0.67 sec, 59.92 MB]                                                            [bootstrap]
Find command files for phase 6 (max=7) [0.67 sec, 59.94 MB]                                                                          [debug]
Found command: core-status (commandfile=core) [0.67 sec, 59.94 MB]                                                               [bootstrap]
Loading outputformat engine. [0.81 sec, 63.61 MB]                                                                                   [notice]
Calling hook drush_core_status [0.81 sec, 63.74 MB]                                                                                  [debug]
Returned from hook drush_core_status [0.84 sec, 63.82 MB]                                                                            [debug]
 Drupal version                :  7.44                                                                                                
 Site URI                      :  http://default                                                                                      
 Database driver               :  mysql                                                                                               
 Database hostname             :  project.local                                                                                          
 Database port                 :                                                                                                      
 Database username             :  root                                                                                                
 Database name                 :  project
                                                                                    
 Drupal bootstrap              :  Successful                                                                                          
 Drupal user                   :                                                                                                      
 Default theme                 :  project                                                                                       
 Administration theme          :  project_admin                                                                                 
 PHP executable                :  /usr/bin/php                                                                                        
 PHP configuration             :  /etc/php5/cli/php.ini                                                                               
 PHP OS                        :  Linux                                                                                               
 Drush script                  :  /path/to/drupal/root/vendor/drush/drush/drush.php                                           
 Drush version                 :  8.0.5                                                                                               
 Drush temp directory          :  /tmp                                                                                                
 Drush configuration           :  /home/fago/.drush/drudrush/drushrc.php /path/to/drupal/root/web/sites/all/drush/drushrc.php 
                                  /home/fago/.drush/drushrc.php                                                                       
 Drush alias files             :  /home/fago/.drush/clients.aliases.drushrc.php           
                                  /path/to/drupal/root/web/sites/all/drush/aliases.drushrc.php                                
 Install profile               :  standard                                                                                            
 Drupal root                   :  /path/to/drupal/root/web                                                                    
 Drupal Settings File          :  sites/default/settings.php                                                                          
 Site path                     :  sites/default                                                                                       
 File directory path           :  files                                                                                               
 Private file directory path   :  sites/default/private                                                                               
 Temporary file directory      :  /tmp                                                                                                
 path                                                                                                                                 

Command dispatch complete [0.85 sec, 63.96 MB]                                                                                      [notice]
 Timer  Cum (sec)  Count  Avg (msec) 
 page   0.63       1      629.82
```

**Comment by weitzman** [comment] 2016-07-22 13:55
I used the following commands (adjust for your DB server as needed) but could not reproduce the problem. It would be great if you tried with latest Drush (8.x or master, both global and site-local).

```
composer create-project drupal-composer/drupal-project:7.x-dev d7composer --stability dev --no-interaction
cd d7composer
composer require drush/drush dev-8.x
composer install
cd web
drush si --db-url=mysql://root:@127.0.0.1:33067/d7composer -v
drush si --db-url=mysql://root:@127.0.0.1:33067/d7c2 -v  --sites-subdir=d7c2
cd sites/d7c2
drush status
```

My output has `Site path                       :  sites/d7c2  ` as expected.

**Comment by fago** [comment] 2016-10-12 13:27
Coming back to this one after running into the applied patch. Sry for not responding earlier, I missed your update.

I tested the problem with your commands, just slightly adapted to use my fitting db-credentials and drush in version "8.x-dev".  When I ran drush status from sites/d7c2 I get:

```
 drush status | grep "Site path"
 Site path                       :  sites/default
```

Thus, I can reproduce the problem with above steps. I've no idea why this problem is not there for you though. I made sure I've got drush 8.x-dev 72494ac installed both globally and at project level  still same results.

Then, after applying the changes from PR-#2286 it works as it should:

```
cd ~/.composer/vendor/drush/drush/
curl https://patch-diff.githubusercontent.com/raw/drush-ops/drush/pull/2286.patch | patch -p1 
cd path/to/web/sites/d7c2
drush status | grep "Site path"
 Site path                       :  sites/d7c2
```

**Comment by fago** [comment] 2016-10-12 13:28
Can we re-open this? Looks like I cannot.

**Comment by fago** [comment] 2016-10-19 15:53
Thanks moshe! What's needed to move on with this issue? PR #2286 still works and resolves the issue for me.

**Comment by weitzman** [comment] 2016-10-19 16:38
Can you reproduce the problem with the steps I posted? If not, what steps are needed? I need to see the bug to know if thats a good fix.

**Comment by fago** [comment] 2016-10-19 17:09
Yes, as written above I was able to reproduce with the steps that you provided:
>I tested the problem with your commands, just slightly adapted to use my fitting db-credentials and drush in version "8.x-dev".
-> The only thing that I had to change was the drush version - I used "8.x-dev" what shoud be fine.
I tested it on Ubuntu 16.04 with its default PHP environment, which is PHP 7.

**Comment by miromichalicka** [comment] 2016-11-10 00:02
I can reproduce error as well. Tested on multiple environments (OS X + PHP7, Debian8 + PHP5.6, Ubuntu 16.04 + PHP5.6). Workaround is to use -l option which is quite inconvenient.
Patch from #2286 is not working for me unfortunately.

**Comment by PatrickBauer** [comment] 2016-11-10 11:01
I can report the same issue. We're using a multi-site environment without a default site and any drush command (with our without --uri='' and in root or in a sites folder), returns:

`The specified database connection is not defined: default`

Because the default site doesn't have any configuration.

**Comment by dakkusingh** [comment] 2017-04-10 16:30
I also have the same issue..

cd into the site folder
```
[dakku@server mysite.com]$ pwd
/var/www/html/d8/web/sites/mysite.com
```

Drush st in my site folder
```
[dakku@server mysite.com]$ drush st
 Drupal version         :  8.3.0                                         
 Site URI               :  http://default                                
 PHP executable         :  /usr/bin/php                                  
 PHP configuration      :  /etc/php.ini                                  
 PHP OS                 :  Linux                                         
 Drush script           :  /var/www/html/d8/vendor/drush/drush/drush.php 
 Drush version          :  8.1.10                                        
 Drush temp directory   :  /tmp                                          
 Drush configuration    :                                                
 Drush alias files      :                                                
 Drupal root            :  /var/www/html/d8/web                          
 Drupal Settings File   :  sites/default/settings.php                    
 Site path              :  sites/default                                 
 Sync config path       :  ../config/sync                                

```
Checking drush path
```
[dakku@server mysite.com]$ which drush
~/.composer/vendor/bin/drush
```

**Comment by carlosmirandalevy** [comment] 2017-07-03 20:15
I keep having the same problem on Drupal 8 installed with composer, which includes drush.
My Drupal installed without composer works fine.
And an Open Social distribution installed via composer also works fine.

I removed the drush 8.1.12 installed by composer, doing `composer remove drush/drush` and my non-composer installed drush 8.1.3 works fine from any multisite directory.

This on Ubuntu 16.04 multisite standard installation on all 3 cases.

**Comment by BR0kEN-** [comment] 2017-07-31 22:27
A new PR which also solves the problem but keeping a possibility to seek the launcher in different directories (https://github.com/drush-ops/drush/pull/2860).

**Comment by oraculi** [comment] 2018-01-19 23:19
I believe I'm encountering the same situation(s) described above.

1. Drupal 8 installed via Composer 
  ```composer create-project drupal-composer/drupal-project:8.x-dev d8-4-test --stability dev --no-interaction```
2. Configure Drupal multisite with no actual site configured in /sites/default
3. ```Drush st``` shows Site URI as http://default
4. ```Drush -l sitename.org st``` displays the expected Site URI

This is on a Debian "Jessie" server with php 5.6. The same version of Drush ( 8.1.15) is installed globally and locally as part of the Drupal install.

Removing the local version of drush via ```composer remove drush/drush```  and relying on the global version of Drush restores everything to the expected functionality and is my current workaround.

Happy to help with testing or provide more info about my setup.

**Comment by weitzman** [comment] 2018-01-20 02:51
Are you located in the sites subdirectory when you make the cli request?

Are you using any symlinks?

**Comment by oraculi** [comment] 2018-01-22 21:47
I'm in /composer-root/web/sites/sitename.org/ when running ```drush st```

I don't have any symlinks in the Drupal directory structure. My global install of drush does rely on a symlink: /usr/local/bin/drush is a symlink to /home/myusername/.composer/vendor/bin/drush

**Comment by rthideaway** [comment] 2018-02-01 09:58
Actually, today I also run into this issue. My global drush version is 8.1.15 and I currently have multisite Drupal instance with two sites. When trying to run `drush st` from within the second site, it is incorrectly displaying status of `default` site.

However, by applying patch from this https://github.com/drush-ops/drush/pull/2286 the issue got fixed.

**Comment by darrenoh** [comment] 2018-03-12 18:51
With Drush 9.2.1, neither an alias nor the _--uri_ option can make Drush use a directory other than _sites/default_ as the site path.

**Comment by Pederytter** [comment] 2018-03-13 14:41
Yeah I had the same issue as @darrenoh, not sure if there is a fix currently.

My solution was going back to drush 8

**Comment by markdorison** [comment] 2018-04-28 18:08
> With Drush 9.2.1, neither an alias nor the --uri option can make Drush use a directory other than sites/default as the site path.

I am experiencing the same issue.

**Comment by gregharvey** [comment] 2018-05-07 11:40
Same here - multisite deployments are broken by drush 9, as we've always assumed if you're in the correct sites directory then drush will use the correct site settings to do things like clear cache and update the db - it's definitely not doing that. Here's the CLI output from a drush 9 test I ran just now:

```
jenkins@dev4:/var/www/live.example-drupal.8.x-multisite/www$ cd sites/siteb/
jenkins@dev4:/var/www/live.example-drupal.8.x-multisite/www/sites/siteb$ drush -y cr --debug
Using the Drush script found at /var/www/example-drupal_8.x-multisite_build_9/www/vendor/drush/drush/drush using pcntl_exec
 [preflight] Config paths: /var/www/example-drupal_8.x-multisite_build_9/www/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /var/www/example-drupal_8.x-multisite_build_9/www/drush/sites,/var/www/example-drupal_8.x-multisite_build_9/www/drush/sites
 [preflight] Commandfile search paths: /var/www/example-drupal_8.x-multisite_build_9/www/vendor/drush/drush/src
 [bootstrap] Bootstrap to site [0.24 sec, 12.64 MB]
 [bootstrap] Drush bootstrap phase 2 [0.24 sec, 12.65 MB]
 [bootstrap] Try to validate bootstrap phase 2 [0.24 sec, 12.65 MB]
 [bootstrap] Try to validate bootstrap phase 2 [0.24 sec, 12.65 MB]
 [bootstrap] Try to bootstrap at phase 2 [0.24 sec, 12.88 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.24 sec, 12.88 MB]
 [bootstrap] Change working directory to /var/www/example-drupal_8.x-multisite_build_9/www [0.24 sec, 12.88 MB]
 [bootstrap] Initialized Drupal 8.3.3 root directory at /var/www/example-drupal_8.x-multisite_build_9/www [0.24 sec, 12.88 MB]
 [bootstrap] Try to validate bootstrap phase 2 [0.24 sec, 12.88 MB]
 [bootstrap] Try to bootstrap at phase 2 [0.25 sec, 13.86 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.25 sec, 13.86 MB]
 [bootstrap] Initialized Drupal site default at sites/default [0.25 sec, 13.86 MB]
 [success] Cache rebuild complete. [3.05 sec, 49.87 MB]
```

Note specifically `Initialized Drupal site default at sites/default` <- that's a whole lot of 'nope' right there! Without the `-l` option at the moment drush 9 is basically not usable for multisites.

Be good to know if the drush team consider this a bug and are fixing, or I should start the refactor of code so it expects to use `-l` rather than assuming if you've `cd`ed to the correct directory it will be fine?

Thanks,

Greg

**Comment by weitzman** [comment] 2018-05-07 12:29
In your drush9 log, you are calling `drush`. What is that pointing to? The
drush-launcher? Thats the recommended way to have a global drush these
days. See install docs. We could eliminate global drush from the discussion
by calling `vendor/bin/drush` instead of `drush`

**Comment by weitzman** [comment] 2018-05-07 13:54
I posted a fix for Drush 8 to #3550. Please test that and let me know how it there how it goes. Sorry it took so long. I didn't think of just doing another chdir() when I last looked at this.

I still can't reproduce this on Drush9. If folks could post STR that would be helpful. Start with `composer create-project drupal-composer/drupal-project:8.x-dev some-dir --stability dev --no-interaction`

**Comment by gregharvey** [comment] 2018-05-07 14:15
For drush 8 I patched `vendor/drush/drush/includes/startup.inc` with #3550 (is that correct?) but I'm still seeing the same behaviour.

**Comment by weitzman** [comment] 2018-05-07 14:25
Thanks. Whats the value passed to the new chdir(). Can you echo that? At same time would be helpful if you posted a new debug log.

**Comment by gregharvey** [comment] 2018-05-07 14:32
Of course, sorry! Just letting a test build finish then I'll re-patch and post something more meaningful for you!

**Comment by weitzman** [comment] 2018-05-07 15:35
When you use a global Drush like `/usr/local/bin/drush`, one of the first things it does is look for a project-specific Drush and if found, hand control to it. So thats why you are seeing reporting that looks like a site local Drush. The global Drush has already handed control. 

I wonder if others who are reporting problems with Drush9 are similarly confused. If they are using Drush8 as a global launcher, the problem would be drush8 (and now fixed). ping @darrenoh, @markdorison, @Pederytter to learn if you are using a global launcher. 

I suspect if you patch your global Drush, you won't need to patch project-specific one or pass in an absolute path. So, you have a few options on how to proceed.

I've just merged #3550. We can reopen this issue if there is indeed a Drush9 problem too.

**Closed** 2018-05-07 15:35 UTC
Labels: stat-needs-work

**Comment by weitzman** [comment] 2018-05-07 16:15
Thanks @darrenoh. I assume you have created a sites.php? Thats a pre-requisite for multisite in D8. What is the contents of that file?

**Comment by weitzman** [comment] 2018-05-07 16:26
startup.inc is before the handoff.

**Comment by gregharvey** [comment] 2018-05-07 16:27
Hmm, OK - point remains though, sometimes it's handing off, sometimes it isn't, and I have no idea why. Probably another issue entirely though.

**Comment by darrenoh** [comment] 2018-05-07 16:28
@weitzman, the sites.php file is a copy of example.sites.php. Multisite is working without trouble in Drupal.

**Comment by weitzman** [comment] 2018-05-07 21:50
@darrenoh - when you say "a copy of example.sites.php", I assume you mean it also has `$sites['home.darren.oh.name.drupal.8'] = 'home.darren.oh.name.drupal.8';` in it. Otherwise I don't see how your multi-site could be working.

When that line is present, then I am seeing your bug fixed when I use #3166. I'll work on fixing its test fails tomorrow. Lets move discussion there.

**Comment by darrenoh** [comment] 2018-05-08 22:39
Drupal checks site directories as long as _sites.php_ is present. _sites.php_ is not required to have content unless you want to use an alias for the site directory name.

**Comment by gaelg** [comment] 2018-09-26 16:18
I had the same problem because of an uppercase character in the subdir : sites/mySite. Changing to lowercase fixed it.

**Comment by Mark-Kiss** [comment] 2018-12-18 15:42
**sites.php** indeed can be empty but must be there.
Here is the following issue about detection:
If I write `drush status` in drupal directory the global detects the local.
However if I write `drush @myalias status` it already handled by the global drush.
Please someone explain this to me, why aliasing has such an impact on detection.

**Comment by greg-1-anderson** [comment] 2018-12-18 16:41
@Mark-Kiss `drush @myalias status` should be equivalent to `drush --root=/path --uri=subsite status` for canonical aliases. If there is a site-local Drush, then Drush should always use it, regardless of how the site is specified. Are you getting different results than that?

**Comment by greenfuture110** [comment] 2022-10-10 10:36
would it be reopen ?!
.
I encountered same error with drush:^11.2.1
whatever command I use, I encounter this error !

`DRUSH VERSION: 11
DRUPAL ROOT: /var/www/html/yass/web
COMPOSER ROOT: /var/www/html/yass
VENDOR ROOT: /var/www/html/yass/vendor
 [preflight] Config paths: /var/www/html/yass/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /var/www/html/yass/web/drush/sites,/var/www/html/yass/drush/sites
 [preflight] Commandfile search paths: /var/www/html/yass/vendor/drush/drush/src,/var/www/html/yass/web/drush
 [info] Starting bootstrap to site [0.16 sec, 8.99 MB]
 [info] Drush bootstrap phase 2 [0.16 sec, 9.05 MB]
 [info] Try to validate bootstrap phase 2 [0.16 sec, 9.05 MB]
 [info] Try to validate bootstrap phase 2 [0.16 sec, 9.05 MB]
 [info] Try to bootstrap at phase 2 [0.16 sec, 9.05 MB]
 [info] Drush bootstrap phase: bootstrapDrupalRoot() [0.16 sec, 9.05 MB]
 [info] Change working directory to /var/www/html/yass/web [0.17 sec, 9.05 MB]
 [info] Initialized Drupal 9.4.8 root directory at /var/www/html/yass/web [0.17 sec, 9.05 MB]
 [info] Try to validate bootstrap phase 2 [0.17 sec, 9.05 MB]
 [info] Try to bootstrap at phase 2 [0.17 sec, 9.06 MB]
 [info] Drush bootstrap phase: bootstrapDrupalSite() [0.17 sec, 9.06 MB]
 [debug] Loaded Drush config file at sites/default/drush.yml. [0.17 sec, 9.24 MB]
 [info] Initialized Drupal site 360.yass.com at sites/default [0.17 sec, 9.24 MB]

In Connection.php line 196:

  [Drupal\Core\Database\DatabaseAccessDeniedException (1045)]
  SQLSTATE[HY000] [1045] Access denied for user 'fake'@'localhost' (using password: YES)


Exception trace:
  at /var/www/html/yass/web/core/modules/mysql/src/Driver/Database/mysql/Connection.php:196
 Drupal\mysql\Driver\Database\mysql\Connection::open() at /var/www/html/yass/core/lib/Drupal/Core/Database/Database.php:464
 Drupal\Core\Database\Database::openConnection() at /var/www/html/yass/core/lib/Drupal/Core/Database/Database.php:189
 Drupal\Core\Database\Database::getConnection() at n/a:n/a
 call_user_func_array() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:258
 Drupal\Component\DependencyInjection\Container->createService() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:176
 Drupal\Component\DependencyInjection\Container->get() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:437
 Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:240
 Drupal\Component\DependencyInjection\Container->createService() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:176
 Drupal\Component\DependencyInjection\Container->get() at /var/www/html/yass/core/lib/Drupal/Core/Cache/ChainedFastBackendFactory.php:89
 Drupal\Core\Cache\ChainedFastBackendFactory->get() at /var/www/html/yass/core/lib/Drupal/Core/Cache/CacheFactory.php:83
 Drupal\Core\Cache\CacheFactory->get() at n/a:n/a
 call_user_func_array() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:258
 Drupal\Component\DependencyInjection\Container->createService() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:176
 Drupal\Component\DependencyInjection\Container->get() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:437
 Drupal\Component\DependencyInjection\Container->resolveServicesAndParameters() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:240
 Drupal\Component\DependencyInjection\Container->createService() at /var/www/html/yass/core/lib/Drupal/Component/DependencyInjection/Container.php:176
 Drupal\Component\DependencyInjection\Container->get() at /var/www/html/yass/core/lib/Drupal/Core/DrupalKernel.php:587
 Drupal\Core\DrupalKernel->preHandle() at /var/www/html/yass/web/core/includes/utility.inc:35
 drupal_rebuild() at /var/www/html/yass/vendor/drush/drush/src/Commands/core/CacheCommands.php:227
 Drush\Commands\core\CacheCommands->rebuild() at n/a:n/a
 call_user_func_array() at /var/www/html/yass/vendor/consolidation/annotated-command/src/CommandProcessor.php:257
 Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback() at /var/www/html/yass/vendor/consolidation/annotated-command/src/CommandProcessor.php:212
 Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter() at /var/www/html/yass/vendor/consolidation/annotated-command/src/CommandProcessor.php:176
 Consolidation\AnnotatedCommand\CommandProcessor->process() at /var/www/html/yass/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:350
 Consolidation\AnnotatedCommand\AnnotatedCommand->execute() at /var/www/html/yass/vendor/symfony/console/Command/Command.php:255
 Symfony\Component\Console\Command\Command->run() at /var/www/html/yass/vendor/symfony/console/Application.php:1027
 Symfony\Component\Console\Application->doRunCommand() at /var/www/html/yass/vendor/symfony/console/Application.php:273
 Symfony\Component\Console\Application->doRun() at /var/www/html/yass/vendor/symfony/console/Application.php:149
 Symfony\Component\Console\Application->run() at /var/www/html/yass/vendor/drush/drush/src/Runtime/Runtime.php:124
 Drush\Runtime\Runtime->doRun() at /var/www/html/yass/vendor/drush/drush/src/Runtime/Runtime.php:51
 Drush\Runtime\Runtime->run() at /var/www/html/yass/vendor/drush/drush/drush.php:72
 require() at /var/www/html/yass/vendor/drush/drush/includes/preflight.inc:18
 drush_main() at phar:///usr/local/bin/drush/bin/drush.php:143
 require() at /usr/local/bin/drush:14
`
I have a multisite, 
1. site/default => yass.com
2. site/360 => 360.yass.com

my sites.php looks like this :
`$sites['360.yass.com'] = '360';
`
I tried other naming method but nothing changed !
1. site/default => yass.com
2. site/360.yass.com => 360.yass.com
sites.php  >>>> `$sites['360.yass.com'] = '360.yass.com';`
.
result of "drush st" in deferent locations :
1. with site/360.yass.com
/var/www/html/yass# drush -l 360.yass.com st
`Site URI       : http://360.yass.com
DB driver      : mysql
DB hostname    : localhost
DB port        : 3306
DB username    : fake
DB name        : fake
PHP binary     : /usr/bin/php7.4
PHP config     : /etc/php/7.4/cli/php.ini
PHP OS         : Linux
PHP version    : 7.4.30
Drush script   : /usr/local/bin/drush
Drush version  : 11.2.1
Drush temp     : /tmp
Drush configs  : /var/www/html/yass/vendor/drush/drush/drush.yml
                 sites/default/drush.yml
Drupal root    : /var/www/html/yass/web
Site path      : sites/default
`
/var/www/html/yass/web/sites/360.yass.com# drush st
`Drupal version : 9.4.8
Site URI       : http://360.yass.com
DB driver      : mysql
DB hostname    : localhost
DB port        : 3306
DB username    : fake
DB name        : fake
PHP binary     : /usr/bin/php7.4
PHP config     : /etc/php/7.4/cli/php.ini
PHP OS         : Linux
PHP version    : 7.4.30
Drush script   : /usr/local/bin/drush
Drush version  : 11.2.1
Drush temp     : /tmp
Drush configs  : /var/www/html/yass/vendor/drush/drush/drush.yml
                 sites/default/drush.yml
Drupal root    : /var/www/html/yass/web
Site path      : sites/default`
 
2. with site/360
/var/www/html/yass# drush -l 360.yass.com st
`Drupal version : 9.4.8
Site URI       : http://360.yass.com
DB driver      : mysql
DB hostname    : localhost
DB port        : 3306
DB username    : fake
DB name        : fake
PHP binary     : /usr/bin/php7.4
PHP config     : /etc/php/7.4/cli/php.ini
PHP OS         : Linux
PHP version    : 7.4.30
Drush script   : /usr/local/bin/drush
Drush version  : 11.2.1
Drush temp     : /tmp
Drush configs  : /var/www/html/yass/vendor/drush/drush/drush.yml
                 sites/default/drush.yml
Drupal root    : /var/www/html/yass/web
Site path      : sites/default`

/var/www/html/yass/web/sites/360# drush st
`Drupal version : 9.4.8
**Site URI       : http://360**
DB driver      : mysql
DB hostname    : localhost
DB port        : 3306
DB username    : fake
DB name        : fake
PHP binary     : /usr/bin/php7.4
PHP config     : /etc/php/7.4/cli/php.ini
PHP OS         : Linux
PHP version    : 7.4.30
Drush script   : /usr/local/bin/drush
Drush version  : 11.2.1
Drush temp     : /tmp
Drush configs  : /var/www/html/yass/vendor/drush/drush/drush.yml
                 sites/default/drush.yml
Drupal root    : /var/www/html/yass/web
Site path      : sites/default`

DB username and DB name which is fake, is the result of "drush st" command. and I did not change that ?!
any help ?!
