### ISSUE TITLE
YAML file recognised as INI

### ISSUE THREAD

**Issue by thewilkybarkid** [drush-ops/drush#1479] opened 2015-07-07 14:48 UTC
The following YAML Make file is recognised as an INI:

``` yaml
api: 2
core: '7.x'

projects:
  date_facets:
    version: '1.0-beta2'
    patch:
      - 'http://cgit.drupalcode.org/date_facets/patch/?id=17b2758128b201fcc83100df9da6a1f8160be836'
```

The equals sign inside the patch URL is the trigger.

**Comment by nlisgo** [comment] 2015-07-07 14:49
Perhaps if certain file extensions are detected that should determine how to parse the contents of the file.

**Comment by jonhattan** [comment] 2015-07-12 13:00
I was to suggest that we sould use `ParserInterface::supportedFile` but it was already there, and discarded in #983. Related commits: 4b4c23c612cebde975219119c3c00fc65b6fd38c and e28a45f996c9dc89f84af6863de03a44b74a2f94

I advocate requiring Yaml's [document separator](http://yaml.org/spec/1.0/#id2561718) (`---`) as the first line of the yaml makefiles.
It is easy to detect and we avoid messing with file extensions, neither perform the parsing twice - https://github.com/drush-ops/drush/blob/master/commands/make/make.utilities.inc#L607

**Comment by danepowell** [comment] 2015-09-15 15:58
I was just bit by this bug as well, and was baffled when drush exited with status 0 without actually building anything. In addition to fixing the root cause, we should add some downstream validation that catches garbage files (such as YML misinterpreted as INI).

As to the root cause: what's the problem with just using the file extension? Seems like way less processing / overhead... The document separator might be technically superior but it's a breaking change.

**Comment by jhedstrom** [comment] 2015-09-15 17:09
> As to the root cause: what's the problem with just using the file extension? Seems like way less processing / overhead... The document separator might be technically superior but it's a breaking change.

We originally went with the file extension as the detection method, but that broke support for piping input.

**Comment by danepowell** [comment] 2015-09-16 16:46
I see. I think the ideal approach would be to suggest a document separator, and fall back to standard detection if it's not found (and possibly throw a warning in the process).

But practically, I think #1386 will solve this.

**Comment by greg-1-anderson** [comment] 2018-07-16 02:37
Make is maintenance only; closing.

**Closed by greg-1-anderson** 2018-07-16 02:37 UTC
Labels: area-make
