### ISSUE TITLE
DrushCommands::printFile() can get picked up as a command

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#2919] opened 2017-08-30 20:49 UTC
This is a weird one.

In an attempt to keep going on work on my own command while https://github.com/drush-ops/drush/issues/2918 is being figured out, I tried brutally hacking in my command's file into DrupalBoot::commandfileSearchpaths(), like this:

```
            case DRUSH_BOOTSTRAP_DRUPAL_ROOT:
                $drupal_root = Drush::bootstrapManager()->getRoot();
                $searchpath[] = $drupal_root . '/../drush';
                $searchpath[] = $drupal_root . '/drush';
                $searchpath[] = $drupal_root . '/sites/all/drush';
                $commandFiles = $discovery->discover($searchpath, '\Drupal');
                
                // DIRTY HACK!
                $commandFiles["/Users/joachim/Sites/8-drupal/drush/contrib/drupal-code-builder-drush/CodeBuilderCommands.php"] 
                  = "\Drush\Commands\CodeBuilder\CodeBuilderCommands";
                
                break;
```

This now gets analysed for commands. But Drush crashes, with a Symfony's Command class saying it has a command with no name.

Consolidation AC is getting this in createSelectedCommandsFromClassInfo():

```
array:3 [
  "printFile" => Consolidation\AnnotatedCommand\Parser\CommandInfo {#612
    #reflection: ReflectionMethod {#765
      +name: "printFile"
      +class: "Drush\Commands\DrushCommands"
      parameters: {
        $file: ReflectionParameter {#825
          +name: "file"
          position: 0
        }
      }
      modifiers: "public static"
    }
    #docBlockIsParsed: true
    #name: ""
    #description: "Print the contents of a file."
    #help: ""
    #options: Consolidation\AnnotatedCommand\Parser\DefaultsWithDescriptions {#702
      #values: []
      #hasDefault: []
      #descriptions: []
      #defaultDefault: false
    }
    #arguments: Consolidation\AnnotatedCommand\Parser\DefaultsWithDescriptions {#701
      #values: array:1 [
        "file" => null
      ]
      #hasDefault: []
      #descriptions: array:1 [
        "file" => "Full path to a file."
      ]
      #defaultDefault: null
    }
    #exampleUsage: []
    #otherAnnotations: Consolidation\AnnotatedCommand\AnnotationData {#700
      flag::STD_PROP_LIST: false
      flag::ARRAY_AS_PROPS: false
      iteratorClass: "ArrayIterator"
      storage: []
    }
    #aliases: []
    #inputOptions: null
    #methodName: "printFile"
    #returnType: null
  }
  "commandUpdateDefinitions" => Consolidation\AnnotatedCommand\Parser\CommandInfo {#628
    #reflection: ReflectionMethod {#39
      +name: "commandUpdateDefinitions"
      +class: "Drush\Commands\CodeBuilder\CodeBuilderCommands"
      modifiers: "public"
    }
    #docBlockIsParsed: true
    #name: "cb-update"
    #description: "Updates Drupal component definitions."
    #help: ""
    #options: Consolidation\AnnotatedCommand\Parser\DefaultsWithDescriptions {#596
      #values: []
      #hasDefault: []
      #descriptions: []
      #defaultDefault: null
    }
    #arguments: Consolidation\AnnotatedCommand\Parser\DefaultsWithDescriptions {#600
      #values: []
      #hasDefault: []
      #descriptions: []
      #defaultDefault: null
    }
    #exampleUsage: array:3 [
      "cb-update" => "Update data on Drupal components, storing in the default location."
      "cb-update --location=relative/path" => "Update data on hooks, storing data in public://relative/path."
      "cb-update --location=/absolute/path" => "Update data on hooks, storing data in /absolute/path."
    ]
    #otherAnnotations: Consolidation\AnnotatedCommand\AnnotationData {#367
      flag::STD_PROP_LIST: false
      flag::ARRAY_AS_PROPS: false
      iteratorClass: "ArrayIterator"
      storage: array:3 [
        "command" => "cb-update"
        "bootstrap" => "DRUSH_BOOTSTRAP_DRUPAL_FULL"
        "code_builder" => ""
      ]
    }
    #aliases: array:1 [
      0 => "cbu"
    ]
    #inputOptions: null
    #methodName: "commandUpdateDefinitions"
    #returnType: null
  }
  "commandListDefinitions" => Consolidation\AnnotatedCommand\Parser\CommandInfo {#611
    #reflection: ReflectionMethod {#599
      +name: "commandListDefinitions"
      +class: "Drush\Commands\CodeBuilder\CodeBuilderCommands"
      modifiers: "public"
    }
    #docBlockIsParsed: true
    #name: "cb-list"
    #description: "Lists stored Drupal component definitions."
    #help: ""
    #options: Consolidation\AnnotatedCommand\Parser\DefaultsWithDescriptions {#595
      #values: []
      #hasDefault: []
      #descriptions: []
      #defaultDefault: null
    }
    #arguments: Consolidation\AnnotatedCommand\Parser\DefaultsWithDescriptions {#667
      #values: []
      #hasDefault: []
      #descriptions: []
      #defaultDefault: null
    }
    #exampleUsage: array:1 [
      "cb-list" => "List stored analysis data on Drupal components."
    ]
    #otherAnnotations: Consolidation\AnnotatedCommand\AnnotationData {#40
      flag::STD_PROP_LIST: false
      flag::ARRAY_AS_PROPS: false
      iteratorClass: "ArrayIterator"
      storage: array:3 [
        "command" => "cb-list"
        "bootstrap" => "DRUSH_BOOTSTRAP_DRUPAL_FULL"
        "code_builder" => ""
      ]
    }
    #aliases: array:1 [
      0 => "cbl"
    ]
    #inputOptions: null
    #methodName: "commandListDefinitions"
    #returnType: null
  }
]
```

It seems to think that printFile() is in *my* command class! If I delete DrushCommands::printFile() then it works.

So... how does the analysis of \Drush\Commands\CodeBuilder\CodeBuilderCommands find a function in a totally different class that's not even annotated as a @command?

**Comment by greg-1-anderson** [comment] 2017-08-30 21:39
Try making `printFile()` protected, perhaps. There is some code in Robo that takes all public methods, and interprets them as commands. Drush should have disabled this mode, but maybe there is some bug in this area.

**Comment by joachim-n** [comment] 2017-08-30 21:55
Ah of course, DrushCommands is the parent class of my commands class! So that's why it's getting picked up.

Changing it to be protected works ok. 

So either Drush should disable that mode in Robo, or printFile() should be made protected. It's only called with self:: so that should be ok.

(BTW though, shouldn't a static method be skipped as a potential command, even if it's public?)

**Comment by greg-1-anderson** [comment] 2017-08-30 22:27
Yeah, static methods should also be skipped.

**Comment by joachim-n** [comment] 2017-08-31 06:13
>  There is some code in Robo that takes all public methods, and interprets them as commands. 

It occurs to me... there's a problem with this behaviour, because AC picks up a public command with no annotation, then passes it to Symfony with a name of '', which crashes Symfony. If AC is willing to pick up a command that has no name due to having no annotation, it shouldn't then cause Symfony to crash. It should maybe use the method name as the command name?

**Comment by joachim-n** [comment] 2017-08-31 06:14
> Yeah, static methods should also be skipped.

Is that a bug in robo or AC? The method is static at the moment, and not skipped!

**Comment by greg-1-anderson** [comment] 2017-09-12 17:07
That's a bug in annotated commands. If a method has no @command annotation, then its method should be used to generate a command name (unless this feature is disabled). Commands with no name should never be passed to Symfony. Annotated commands should skip static methods.

**Comment by joachim-n** [comment] 2017-09-25 19:31
This is still a problem with latest version of both drush and AC.

Is there a reason printFile() can't be changed to protected? It's the simplest fix.

**Comment by greg-1-anderson** [comment] 2017-09-25 21:36
I've seen a couple of people report this bug, but I haven't been able to reproduce it. Could you copy the output of `composer show` here?

**Comment by joachim-n** [comment] 2017-09-25 21:47
```
asm89/stack-cors                              1.1.0              Cross-origin resource sharing library and ...
behat/mink                                    dev-master 9ea1ceb Browser controller/emulator abstraction fo...
behat/mink-browserkit-driver                  v1.3.2             Symfony2 BrowserKit driver for Mink framework
behat/mink-goutte-driver                      v1.2.1             Goutte driver for Mink framework
chi-teck/drupal-code-generator                1.19.0             Drupal code generator
composer/installers                           v1.4.0             A multi-framework Composer library installer
composer/semver                               1.4.2              Semver library that offers utilities, vers...
consolidation/annotated-command               2.4.13             Initialize Symfony Console commands from a...
consolidation/config                          1.0.1              Provide configuration services for a comma...
consolidation/log                             1.0.3              Improved Psr-3 / Psr\Log logger based on S...
consolidation/output-formatters               3.1.11             Format text by applying transformations pr...
consolidation/robo                            1.1.2              Modern task runner
container-interop/container-interop           1.2.0              Promoting the interoperability of containe...
dflydev/dot-access-data                       v1.1.0             Given a deep data structure, access data b...
dnoegel/php-xdg-base-dir                      0.1                implementation of xdg base directory speci...
doctrine/annotations                          v1.4.0             Docblock Annotations Parser
doctrine/cache                                v1.6.2             Caching library offering an object-oriente...
doctrine/collections                          v1.4.0             Collections Abstraction library
doctrine/common                               v2.7.3             Common Library for Doctrine projects
doctrine/inflector                            v1.2.0             Common String Manipulations with regard to...
doctrine/instantiator                         1.0.5              A small, lightweight utility to instantiat...
doctrine/lexer                                v1.0.1             Base library for a lexer that can be used ...
drupal-code-builder/drupal-code-builder       3.0.0
drupal-code-builder/drupal-code-builder-drush 9.x-dev 830d1ad    Provides Drush commands for generating Dru...
drupal/coder                                  8.2.12             Coder is a library to review Drupal code.
drush/drush                                   9.0.0-beta4        Drush is a command line shell and scriptin...
easyrdf/easyrdf                               0.9.1              EasyRdf is a PHP library designed to make ...
egulias/email-validator                       1.2.14             A library for validating emails
fabpot/goutte                                 v3.2.1             A simple PHP Web Scraper
grasmash/yaml-expander                        1.1.1              Expands internal property references in a ...
guzzlehttp/guzzle                             6.3.0              Guzzle is a PHP HTTP client library
guzzlehttp/promises                           v1.3.1             Guzzle promises library
guzzlehttp/psr7                               1.4.2              PSR-7 message implementation that also pro...
jakub-onderka/php-console-color               0.1
jakub-onderka/php-console-highlighter         v0.3.2
jcalderonzumba/gastonjs                       v1.2.0             PhantomJS API based server for webpage aut...
jcalderonzumba/mink-phantomjs-driver          v0.3.3             PhantomJS driver for Mink framework
league/container                              2.4.1              A fast and intuitive dependency injection ...
masterminds/html5                             2.2.2              An HTML5 parser and serializer.
mikey179/vfsStream                            v1.6.5             Virtual file system to mock the real file ...
nikic/php-parser                              v3.1.0             A PHP parser written in PHP
paragonie/random_compat                       v2.0.10            PHP 5.x polyfill for random_bytes() and ra...
pear/console_table                            v1.3.0             Library that makes it easy to build consol...
phpdocumentor/reflection-docblock             2.0.5
phpspec/prophecy                              v1.7.0             Highly opinionated mocking framework for P...
phpunit/php-code-coverage                     2.2.4              Library that provides collection, processi...
phpunit/php-file-iterator                     1.4.2              FilterIterator implementation that filters...
phpunit/php-text-template                     1.2.1              Simple template engine.
phpunit/php-timer                             1.0.9              Utility class for timing
phpunit/php-token-stream                      1.4.11             Wrapper around PHP's tokenizer extension.
phpunit/phpunit                               4.8.36             The PHP Unit Testing framework.
phpunit/phpunit-mock-objects                  2.3.8              Mock Object library for PHPUnit
psr/container                                 1.0.0              Common Container Interface (PHP FIG PSR-11)
psr/http-message                              1.0.1              Common interface for HTTP messages
psr/log                                       1.0.2              Common interface for logging libraries
psy/psysh                                     v0.8.11            An interactive shell for modern PHP.
sebastian/comparator                          1.2.4              Provides the functionality to compare PHP ...
sebastian/diff                                1.4.3              Diff implementation
sebastian/environment                         1.3.8              Provides functionality to handle HHVM/PHP ...
sebastian/exporter                            1.2.2              Provides the functionality to export PHP v...
sebastian/global-state                        1.1.1              Snapshotting of global state
sebastian/recursion-context                   1.0.5              Provides functionality to recursively proc...
sebastian/version                             1.0.6              Library that helps with managing the versi...
squizlabs/php_codesniffer                     2.9.1              PHP_CodeSniffer tokenizes PHP, JavaScript ...
stack/builder                                 v1.0.4             Builder for stack middlewares based on Htt...
symfony-cmf/routing                           1.4.1              Extends the Symfony2 routing component for...
symfony/browser-kit                           v3.3.6             Symfony BrowserKit Component
symfony/class-loader                          v3.3.6             Symfony ClassLoader Component
symfony/config                                v3.3.6             Symfony Config Component
symfony/console                               v3.3.6             Symfony Console Component
symfony/css-selector                          v3.3.6             Symfony CssSelector Component
symfony/debug                                 v3.3.6             Symfony Debug Component
symfony/dependency-injection                  v3.3.6             Symfony DependencyInjection Component
symfony/dom-crawler                           v3.3.6             Symfony DomCrawler Component
symfony/event-dispatcher                      v3.3.6             Symfony EventDispatcher Component
symfony/filesystem                            v3.3.6             Symfony Filesystem Component
symfony/finder                                v3.3.6             Symfony Finder Component
symfony/http-foundation                       v3.3.6             Symfony HttpFoundation Component
symfony/http-kernel                           v3.3.6             Symfony HttpKernel Component
symfony/phpunit-bridge                        v3.3.8             Symfony PHPUnit Bridge
symfony/polyfill-iconv                        v1.5.0             Symfony polyfill for the Iconv extension
symfony/polyfill-mbstring                     v1.5.0             Symfony polyfill for the Mbstring extension
symfony/process                               v3.3.6             Symfony Process Component
symfony/psr-http-message-bridge               v1.0.0             PSR HTTP message bridge
symfony/routing                               v3.3.6             Symfony Routing Component
symfony/serializer                            v3.3.6             Symfony Serializer Component
symfony/translation                           v3.3.6             Symfony Translation Component
symfony/validator                             v3.3.6             Symfony Validator Component
symfony/var-dumper                            v3.3.6             Symfony mechanism for exploring and dumpin...
symfony/yaml                                  v3.3.6             Symfony Yaml Component
twig/twig                                     v1.34.4            Twig, the flexible, fast, and secure templ...
webflo/drupal-finder                          1.0.0              Helper class to locate a Drupal installati...
webmozart/assert                              1.2.0              Assertions to validate method input/output...
webmozart/path-util                           2.3.0              A robust cross-platform utility for normal...
wikimedia/composer-merge-plugin               v1.4.1             Composer plugin to merge multiple composer...
zendframework/zend-diactoros                  1.5.0              PSR HTTP Message implementations
zendframework/zend-escaper                    2.5.2
zendframework/zend-feed                       2.8.0              provides functionality for consuming RSS a...
zendframework/zend-stdlib                     3.1.0
```

Though I should say I've set my local install to use git clones for packages in the Drush stack, and since hackily used git manually to update them... there's probably a right way to do that with composer but I have lost too many hours headdesking with composer issues.

**Comment by greg-1-anderson** [comment] 2017-09-25 22:16
I don't think that any of your work practices are causing problems here, and nothing really jumps out at me from your versions list.

Try to test with https://github.com/consolidation/annotated-command/pull/127 and see if that fixes your problem, as I still cannot reproduce. If that does not work, I also made https://github.com/drush-ops/drush/pull/2960

**Comment by greg-1-anderson** [comment] 2017-09-26 01:06
The other thing you could try if you think it's somehow messed up is, save any of your modifications and then remove your composer.lock and vendor directory, and run `composer install` again. It looks like it's been a week or so since you've done that; some sort of corruption may have crept in.

**Comment by greg-1-anderson** [comment] 2017-09-27 03:34
Did those PRs work at all for you? Others who had this problem found that it cleared up by removing vendor and composer.lock, and re-installing. Would be good to know if something more than that is going on here.

**Comment by greg-1-anderson** [comment] 2017-09-27 03:34
Wrong button.

**Comment by joachim-n** [comment] 2017-09-27 14:06
Haven't had a chance to try this yet, sorry.

It's going to need an evening when I've got enough mental energy to look at it AND the baby doesn't wake up every 15 minutes...

**Comment by greg-1-anderson** [comment] 2017-10-01 02:30
Fixed by #2960

**Closed by greg-1-anderson** 2017-10-01 02:30 UTC
Labels: area-annotated

**Comment by joachim-n** [comment] 2017-10-06 20:17
I've updated all my sources and I was going to have a go at this, but my hacks to Drush to get my command file picked up don't apply any more, and I've no idea where command file discovery has moved to.

**Comment by greg-1-anderson** [comment] 2017-10-06 20:19
@weitzman claimed to have seen this bug again recently, but I was not able to reproduce it. I still suspect it is fixed. Commandfile discovery and instantiation happens in the annotated-command library.

**Comment by joachim-n** [comment] 2017-10-06 20:34
I've just got my command to register using my hacks that get it picked up as a Drupal module, and making printFile() public again has no untoward effects.

However, probably best to revisit this once https://github.com/drush-ops/drush/issues/2918 is fixed and my command is getting picked up the way it's designed to be.
