### ISSUE TITLE
drush updatedb with postgresql?

### ISSUE THREAD

**Issue by 9034725985** [drush-ops/drush#3637] opened 2018-08-02 17:04 UTC
**Describe the bug**
I can't run drush updatedb 

**To Reproduce**
I installed drush 
I ran drush updatedb 

**Expected behavior**
updates database 

**Actual behavior**
```

cl-pur-w7-04:~ student$ cd ~/src/kushalexperimental/cantelope/
cl-pur-w7-04:cantelope student$ composer install drush/drush
Invalid argument drush/drush. Use "composer require drush/drush" instead to add packages to your composer.json.
cl-pur-w7-04:cantelope student$ composer require drush/drush
Using version ^9.3 for drush/drush
./composer.json has been updated
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 23 installs, 0 updates, 0 removals
  - Installing webmozart/path-util (2.3.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing webflo/drupal-finder (1.1.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/var-dumper (v3.4.14): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/finder (v3.4.14): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/filesystem (v3.4.14): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing symfony/config (v3.4.14): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing nikic/php-parser (v4.0.3): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing jakub-onderka/php-console-color (0.1): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing jakub-onderka/php-console-highlighter (v0.3.2): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dnoegel/php-xdg-base-dir (0.1): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing psy/psysh (v0.9.6): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing container-interop/container-interop (1.2.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing league/container (2.4.1): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing dflydev/dot-access-data (v1.1.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing grasmash/yaml-expander (1.4.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing consolidation/output-formatters (3.2.1): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing consolidation/log (1.0.6): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing consolidation/annotated-command (2.8.4): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing grasmash/expander (1.0.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing consolidation/config (1.0.11): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing consolidation/robo (1.3.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing chi-teck/drupal-code-generator (1.25.1): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
  - Installing drush/drush (9.3.0): Loading from cache
> Drupal\Core\Composer\Composer::vendorTestCodeCleanup
symfony/var-dumper suggests installing ext-symfony_debug ()
psy/psysh suggests installing ext-pdo-sqlite (The doc command requires SQLite to work.)
psy/psysh suggests installing hoa/console (A pure PHP readline implementation. You'll want this if your PHP install doesn't already support readline or libedit.)
consolidation/robo suggests installing pear/archive_tar (Allows tar archives to be created and extracted in taskPack and taskExtract, respectively.)
consolidation/robo suggests installing henrikbjorn/lurker (For monitoring filesystem changes in taskWatch)
consolidation/robo suggests installing patchwork/jsqueeze (For minifying JS files in taskMinify)
consolidation/robo suggests installing natxet/CssMin (For minifying CSS files in taskMinify)
Writing lock file
Generating autoload files
> Drupal\Core\Composer\Composer::preAutoloadDump
> Drupal\Core\Composer\Composer::ensureHtaccess
cl-pur-w7-04:cantelope student$ vendor/bin/drush cr
 [success] Cache rebuild complete.
cl-pur-w7-04:cantelope student$ vendor/bin/drush updatedb
 [warning] The command 'PGPASSFILE=/private/tmp/drush_8E5DVe psql -q' is required for preflight but cannot be found. Please install it and retry.

In BootstrapHook.php line 32:

  Bootstrap failed. Run your command with -vvv for more information.


updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]] [--no-cache-clear] [--no-post-updates] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify] [--xh-link XH-LINK] [--] <command>

cl-pur-w7-04:cantelope student$ vendor/bin/drush updatedb -vvv
 [preflight] Config paths: /Users/student/src/kushalexperimental/cantelope/vendor/drush/drush/drush.yml
 [preflight] Alias paths: /Users/student/src/kushalexperimental/cantelope/drush/sites,/Users/student/src/kushalexperimental/cantelope/drush/sites
 [preflight] Commandfile search paths: /Users/student/src/kushalexperimental/cantelope/vendor/drush/drush/src
 [bootstrap] Bootstrap to full [0.06 sec, 7.97 MB]
 [bootstrap] Drush bootstrap phase 5 [0.06 sec, 7.97 MB]
 [bootstrap] Try to validate bootstrap phase 5 [0.06 sec, 7.97 MB]
 [bootstrap] Try to validate bootstrap phase 5 [0.06 sec, 7.98 MB]
 [bootstrap] Try to bootstrap at phase 5 [0.06 sec, 8.1 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalRoot() [0.06 sec, 8.11 MB]
 [bootstrap] Change working directory to /Users/student/src/kushalexperimental/cantelope [0.06 sec, 8.11 MB]
 [bootstrap] Initialized Drupal 8.6.0-dev root directory at /Users/student/src/kushalexperimental/cantelope [0.06 sec, 8.11 MB]
 [bootstrap] Try to validate bootstrap phase 5 [0.06 sec, 8.11 MB]
 [info] Undefined index: scheme DrupalBoot8.php:121 [0.06 sec, 8.11 MB]
 [bootstrap] Try to bootstrap at phase 5 [0.07 sec, 8.63 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalSite() [0.07 sec, 8.63 MB]
 [bootstrap] Initialized Drupal site default at sites/default [0.07 sec, 8.63 MB]
 [bootstrap] Try to validate bootstrap phase 5 [0.07 sec, 8.63 MB]
 [bootstrap] Try to bootstrap at phase 5 [0.07 sec, 8.63 MB]
 [bootstrap] Drush bootstrap phase: bootstrapDrupalConfiguration() [0.07 sec, 8.63 MB]
 [debug] Add service modifier [0.07 sec, 8.81 MB]
 [bootstrap] Try to validate bootstrap phase 5 [0.07 sec, 8.81 MB]
 [warning] The command 'PGPASSFILE=/private/tmp/drush_WQVSPP psql -q' is required for preflight but cannot be found. Please install it and retry. [0.08 sec, 8.96 MB]
 [bootstrap] Could not bootstrap at phase 5 [0.08 sec, 8.96 MB]

In BootstrapHook.php line 32:

  [Exception]
  Bootstrap failed. Run your command with -vvv for more information.


Exception trace:
 Drush\Boot\BootstrapHook->initialize() at /Users/student/src/kushalexperimental/cantelope/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:34
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->callInitializeHook() at /Users/student/src/kushalexperimental/cantelope/vendor/consolidation/annotated-command/src/Hooks/Dispatchers/InitializeHookDispatcher.php:27
 Consolidation\AnnotatedCommand\Hooks\Dispatchers\InitializeHookDispatcher->initialize() at /Users/student/src/kushalexperimental/cantelope/vendor/consolidation/annotated-command/src/CommandProcessor.php:117
 Consolidation\AnnotatedCommand\CommandProcessor->initializeHook() at /Users/student/src/kushalexperimental/cantelope/vendor/consolidation/annotated-command/src/AnnotatedCommand.php:391
 Consolidation\AnnotatedCommand\AnnotatedCommand->initialize() at /Users/student/src/kushalexperimental/cantelope/vendor/symfony/console/Command/Command.php:217
 Symfony\Component\Console\Command\Command->run() at /Users/student/src/kushalexperimental/cantelope/vendor/symfony/console/Application.php:964
 Symfony\Component\Console\Application->doRunCommand() at /Users/student/src/kushalexperimental/cantelope/vendor/symfony/console/Application.php:248
 Symfony\Component\Console\Application->doRun() at /Users/student/src/kushalexperimental/cantelope/vendor/symfony/console/Application.php:148
 Symfony\Component\Console\Application->run() at /Users/student/src/kushalexperimental/cantelope/vendor/drush/drush/src/Runtime/Runtime.php:112
 Drush\Runtime\Runtime->doRun() at /Users/student/src/kushalexperimental/cantelope/vendor/drush/drush/src/Runtime/Runtime.php:41
 Drush\Runtime\Runtime->run() at /Users/student/src/kushalexperimental/cantelope/vendor/drush/drush/drush.php:66
 require() at /Users/student/src/kushalexperimental/cantelope/vendor/drush/drush/drush:4

updatedb [--cache-clear [CACHE-CLEAR]] [--entity-updates] [--post-updates [POST-UPDATES]] [--no-cache-clear] [--no-post-updates] [-h|--help] [-q|--quiet] [-v|vv|vvv|--verbose] [-V|--version] [--ansi] [--no-ansi] [-n|--no-interaction] [-d|--debug] [-y|--yes] [--no] [--remote-host REMOTE-HOST] [--remote-user REMOTE-USER] [-r|--root ROOT] [-l|--uri URI] [--simulate] [--pipe] [-D|--define DEFINE] [--druplicon] [--notify [NOTIFY]] [--xh-link XH-LINK] [--] <command>

cl-pur-w7-04:cantelope student$


```

**Workaround**
Is there another way to do the desired action?

I can run http://cantelope.test/update.php and that works fine. 
It says no pending updates. 

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.3.0
| Drupal version? | 8.6
| PHP version     | 7.1.20
| OS?             | Mac

**Additional information**
The postgresql database is on a remote server

**Comment by weitzman** [comment] 2018-08-02 17:48
Dupe of #2973

**Closed by weitzman** 2018-08-02 17:48 UTC
