### ISSUE TITLE
sql-create not working

### ISSUE THREAD

**Issue by petruisfan** [drush-ops/drush#1844] opened 2015-12-07 13:57 UTC
When I run `drush sql-create` nothing happens. Running with '-d' flag tells me that I have an error in my sql syntax because drush doesn't wrap the database name in "`" quotes. My db name is "drupal7_4.48.1-970d98c", and the "." causes the error.

**Comment by weitzman** [comment] 2015-12-19 02:26
Do other sql-commands work on a database whose name contains periods? trying to see if the problem is wider than sql-create. Also, are you using mysql?

**Comment by lmeurs** [comment] 2016-02-07 10:54
Same here using Drush v8.0.3, MySQL and a database name like `my-database` containing a dash.

`drush_sql_create()` does not support optional quoted database names (https://github.com/drush-ops/drush/blob/master/commands/sql/sql.drush.inc#L256). And if it did, `createdb()` does not pass the `$quoted` argument (https://github.com/drush-ops/drush/blob/master/lib/Drush/Sql/SqlBase.php#L245).

Ie. command `sql-dump` does work without problems.

**Comment by weitzman** [comment] 2016-02-12 16:04
Would be great to see a PR for this, and ideally a test.

**Comment by weitzman** [comment] 2016-04-05 04:19
Fixed in 483149e

**Closed by weitzman** 2016-04-05 04:19 UTC
Labels: area-sql, stat-needs-work
