### ISSUE TITLE
Error with locale-update

### ISSUE THREAD

**Issue by torfsen** [drush-ops/drush#2060] opened 2016-03-07 12:53 UTC
This is on Drupal 8.0.4 and Drush 8.0.3.

```
$ drush locale-update
Argument 4 passed to locale_translation_batch_status_check() must be of the type array, object given locale.batch.inc:39  [error]
Drush command terminated abnormally due to an unrecoverable error.                                                        [error]
The external command could not be executed due to an application error.                                                   [error]
```

Please tell me if you need further information.

**Comment by tstoeckler** [comment] 2016-03-07 15:27
This is a duplicate of #1930. It will (hopefully) be fixed upstream in Drupal core 8.0, it has already been fixed in latest 8.1 and 8.2

**Closed by tstoeckler** 2016-03-07 15:27 UTC
