### ISSUE TITLE
config-set value with starting minus

### ISSUE THREAD

**Issue by politsin** [drush-ops/drush#4331] opened 2020-02-21 12:32 UTC
**Describe the bug**
Error with config-set value with starting minus

**To Reproduce**
```sh
drush config-set foo.settings latitude "-74.04" -y
$ The "-7" option does not exist
drush config-set foo.settings latitude "74.04" -y 
$ OK
```

**Expected behavior**
Expect nornal usage =)

**Actual behavior**
Error `The "-7" option does not exist.`

**Workaround**
The (ugly) work-around is:
```sh
echo "-74.04791312088358" | drush config-set foo.settings latitude - -y
```
https://drupal.stackexchange.com/questions/241633/how-to-pass-negative-values-to-config-set/242820

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | Drush Commandline Tool 9.7.2
| Drupal version? | 8.8.2 
| PHP version     | 7.2
| OS?             | Linux

**Comment by weitzman** [comment] 2020-02-21 12:58
Dupe of https://github.com/drush-ops/drush/issues/378

**Closed by weitzman** 2020-02-21 12:58 UTC

**Comment by politsin** [comment] 2020-02-21 14:04
So the previous ticket is also closed. о.О
Like the problem's not on our side?

**Comment by weitzman** [comment] 2020-02-21 15:45
Its a known issue that we don't intend to fix, given there is a workaround.
