### ISSUE TITLE
drush updb seems automatically re-execute failing post-updates forever

### ISSUE THREAD

**Issue by Berdir** [drush-ops/drush#3176] opened 2017-11-16 12:11 UTC
We had a project where we tested the 8.4 update and the deployment to platform.sh got stuck, because we were running drush updb inside it and it was running for hours, trying again and again to execute a post update function that died with an exception.

I don't think it can be expected that re-running a post update function will just work the second time, so this doesn't seem very useful?

**Comment by Berdir** [comment] 2017-11-16 12:34
Output looks like this:

```
 [ok] Folgeverarbeitungen nach der Aktualisierung von dblog werden ausgeführt
 [ok] Folgeverarbeitungen nach der Aktualisierung von dynamic_entity_reference werden ausgeführt
 [ok] Folgeverarbeitungen nach der Aktualisierung von field werden ausgeführt
 [ok] Folgeverarbeitungen nach der Aktualisierung von language werden ausgeführt
 [ok] Folgeverarbeitungen nach der Aktualisierung von system werden ausgeführt
 [ok] Folgeverarbeitungen nach der Aktualisierung von system werden ausgeführt
 [ok] Folgeverarbeitungen nach der Aktualisierung von views werden ausgeführt
 [notice] Failed:core.entity_form_display.commerce_order_item.default.default does not exist in active storage
 [notice] The watchdog view has been created.
 [error]  Failed: InvalidArgumentException: The configuration property display.default.display_options.filters.type_1.value.image doesn&#039;t exist. in Drupal\Core\Config\Schema\ArrayElement-&gt;get() (Zeile 76 in /web/core/lib/Drupal/Core/Config/Schema/ArrayElement.php). 
 [notice] Failed:core.entity_form_display.commerce_order_item.default.default does not exist in active storage
 [notice] The watchdog view has been created.
 [error]  Failed: InvalidArgumentException: The configuration property display.default.display_options.filters.type_1.value.image doesn&#039;t exist. in Drupal\Core\Config\Schema\ArrayElement-&gt;get() (Zeile 76 in /web/core/lib/Drupal/Core/Config/Schema/ArrayElement.php). 
 [notice] Failed:core.entity_form_display.commerce_order_item.default.default does not exist in active storage
 [notice] The watchdog view has been created.
 [error]  Failed: InvalidArgumentException: The configuration property display.default.display_options.filters.type_1.value.image doesn&#039;t exist. in Drupal\Core\Config\Schema\ArrayElement-&gt;get() (Zeile 76 in /web/core/lib/Drupal/Core/Config/Schema/ArrayElement.php). 
 [notice] Failed:core.entity_form_display.commerce_order_item.default.default does not exist in active storage
 [notice] The watchdog view has been created.]
```

And then it goes on forever like that. Strangely, it also repeats output messages.

**Comment by weitzman** [comment] 2017-11-16 19:37
Perhaps a dupe of #2762. It would be great to get a reproducible use case for this.

**Comment by weitzman** [comment] 2018-01-21 18:08
Possibly fixed y recent updb merges. /cc @pfrenssen

**Comment by pfrenssen** [comment] 2018-01-24 08:46
Yes we recently overhauled the way post-updates are being executed, it would be great to know if the most recent version of the `master` branch still exhibits the failure.

**Comment by weitzman** [comment] 2018-01-26 17:47
Please post here if still a problem.

**Closed by weitzman** 2018-01-26 17:47 UTC
Labels: area-updatedb
