### ISSUE TITLE
Infinite loop because of symbolic links

### ISSUE THREAD

**Issue by jurgenhaas** [drush-ops/drush#3143] opened 2017-11-06 08:31 UTC
This is a report about Drush 9 Beta 8 on a Ubuntu 16.04 server. I crashed my own live server because Drush called itself in an infinite loop over and over again until there haven't been any resources left and only a hard rebbot got me out of that.

So here is what happend - and by the way this can be reproduced and wasn't a problem until and including beta 4:

The command I was running is `/jails/SITE/var/www/vendor/drush/drush/drush '--uri=www.example.com' '--root=/jails/SITE/var/www/web' 'status'` and that command called itself over and over again.

The directory `/jails` is a symbolic link to `/mnt/storage/jails` and that is causing the issue. When I call `/jails/SITE/var/www/vendor/drush/drush/drush '--uri=www.example.com' '--root=/mnt/storage/jails/SITE/var/www/web' 'status'` instead, drush behaves as expected. So what's different is that I'm providing the pfysical path for the root parameter instead of the one that needs to be resolved following the symbolic link.

What's interesting is that when I use an alias which has the root path configured to the symbolic link location, then Drush works OK as well.

I assume that the alias handling is resolving realpath where the root parameter is not. And Drush seems to detect that it cds into a different directory than given as root paramater and therefore launches an additional instance - which then finds itself in the same situation again. Is that possible?

**Comment by weitzman** [comment] 2017-11-06 12:40
Dupe of #3110. Help wanted.

**Closed by weitzman** 2017-11-06 12:40 UTC
