### ISSUE TITLE
drush make does not overwrite root core files

### ISSUE THREAD

**Issue by lumini-git** [drush-ops/drush#1468] opened 2015-06-29 09:03 UTC
When running drush make inside the installation folder, root core files are not overwritten. Is this intended behavior ?

I am currently digging into the code, and I will update this issue if I find something, but in the meantime, if anybody knows about this particular issue, I would appreciate any help.

**Comment by ergonlogic** [comment] 2015-09-16 20:50
It looks like this is a duplicate of #1450.

**Closed by ergonlogic** 2015-09-16 20:50 UTC
Labels: area-make
