### ISSUE TITLE
TypeError - Drush config-export not working on 11.2.1

### ISSUE THREAD

**Issue by jaybabak** [drush-ops/drush#5260] opened 2022-10-04 21:56 UTC
**Describe the bug**
Following an update to a new version of Drupal 9.3.22 drush export command does not work as expected

**To Reproduce**
Run drush cex or drush config-export

**Expected behavior**
Configuration to be exported in the configuration directory.

**Actual behavior**
Received a TypeError.

` [error]  TypeError: Drush\Drupal\Commands\config\ConfigExportCommands::getConfigStorageSync(): Return value must be of type Drupal\Core\Config\StorageInterface, null returned in Drush\Drupal\Commands\config\ConfigExportCommands->getConfigStorageSync() (line 68 of /var/www/vendor/drush/drush/src/Drupal/Commands/config/ConfigExportCommands.php) #0 /var/www/vendor/drush/drush/src/Drupal/Commands/config/ConfigExportCommands.php(121): Drush\Drupal\Commands\config\ConfigExportCommands->getConfigStorageSync()
#1 /var/www/vendor/drush/drush/src/Drupal/Commands/config/ConfigExportCommands.php(109): Drush\Drupal\Commands\config\ConfigExportCommands->doExport(Array, '/var/www/config...')
#2 [internal function]: Drush\Drupal\Commands\config\ConfigExportCommands->export(Array)
#3 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(257): call_user_func_array(Array, Array)
#4 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(212): Consolidation\AnnotatedCommand\CommandProcessor->runCommandCallback(Array, Object(Consolidation\AnnotatedCommand\CommandData))
#5 /var/www/vendor/consolidation/annotated-command/src/CommandProcessor.php(176): Consolidation\AnnotatedCommand\CommandProcessor->validateRunAndAlter(Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#6 /var/www/vendor/consolidation/annotated-command/src/AnnotatedCommand.php(350): Consolidation\AnnotatedCommand\CommandProcessor->process(Object(Symfony\Component\Console\Output\ConsoleOutput), Array, Array, Object(Consolidation\AnnotatedCommand\CommandData))
#7 /var/www/vendor/symfony/console/Command/Command.php(255): Consolidation\AnnotatedCommand\AnnotatedCommand->execute(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#8 /var/www/vendor/symfony/console/Application.php(1027): Symfony\Component\Console\Command\Command->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#9 /var/www/vendor/symfony/console/Application.php(273): Symfony\Component\Console\Application->doRunCommand(Object(Consolidation\AnnotatedCommand\AnnotatedCommand), Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#10 /var/www/vendor/symfony/console/Application.php(149): Symfony\Component\Console\Application->doRun(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#11 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(124): Symfony\Component\Console\Application->run(Object(Symfony\Component\Console\Input\ArgvInput), Object(Symfony\Component\Console\Output\ConsoleOutput))
#12 /var/www/vendor/drush/drush/src/Runtime/Runtime.php(51): Drush\Runtime\Runtime->doRun(Array, Object(Symfony\Component\Console\Output\ConsoleOutput))
#13 /var/www/vendor/drush/drush/drush.php(72): Drush\Runtime\Runtime->run(Array)
#14 /var/www/vendor/drush/drush/drush(4): require('/var/www/vendor...')
#15 {main}. 
`

**Workaround**
Downgrade the Drush version to 11.1.1

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 11.2.1
| Drupal version? | 9.3.22
| PHP version     | 8.0.15
| OS?             | Linux

**Additional information**
This happened after updating to a new version of Drupal core (9.3.22)

**Comment by amcgowanca** [comment] 2022-10-04 23:38
_Ya_ broke something Mr. Malik.

**Comment by weitzman** [comment] 2022-10-05 01:35
@DieterHolvoet @bircher any thoughts?

**Comment by DieterHolvoet** [comment] 2022-10-05 07:53
I cannot reproduce this using Drupal 9.3.22 and Drush 11.2.1. Tried with `$settings['config_sync_directory']` in settings.php, without it and with a non-existing path. I did find [another related issue](https://github.com/drush-ops/drush/pull/5261), 

@jaybabak maybe you could try to apply [the patch](https://patch-diff.githubusercontent.com/raw/drush-ops/drush/pull/5261.diff) and check if that fixes it? What's the exact command you're running? What's the value of `$settings['config_sync_directory']` in your settings.php? What config related modules do you have installed?

**Comment by mazz0016** [comment] 2022-10-06 18:02
Hello, I am also receiving this error after upgrading my drush to 11.2.1. I am also running Drupal core version 9.3.22. I am currently running my site through a docker container on my Mac running Monterey.

I tried the above patch and it did not resolve my issue. I also tried specifying the directory I wish to export to: `drush cex --destination="../config/sync"` as well without success. I removed my `$settings['config_sync_directory']` from my settings.php as well and still encountered the error.

I have installed Config Split and Config Filter previously to my site and removed both in the hopes it would fix this error, but no dice.

I run `drush cex` to receive the error. My `$settings['config_sync_directory']` is `../config/sync`.

I have downgraded my version of drush to 11.1.1 and that has completely resolved the issue, however if I update again, I continue to receive the error. Any guidance would be appreciated. Thank you.

EDIT:
I have tried some additional things to resolve my problem. I printed out `$this->configStorageSync` set in the `setConfigStorageSync()` function of ConfigExportCommands.php. The object was returned with the expected values. However, when printing out the `$this->configStorageSync` again in `getConfigStorageSync()` it is null.

I added:
```
if (isset($this->configStorageExport)) { 
        return $this->configStorageExport;
}
        return $this->configStorage;
```
to the getConfigStorageSync() function and commented out `return $this->configStorageSync;`. I then ran `drush cex` again and had no errors. That resolved my issue.
I do not know if this solution is viable as there must be a reason for using `configStorageSync` as opposed to `configStorage`. But using the `configStorage` in place of `configStorageSync` works for me.
Thank you again for your guidance.

**Comment by sylus** [comment] 2022-10-10 01:23
Ran into the same problem as well but on Drupal Core 9.4.8 and Drush 11.2.1

@mazz0016 workaround worked for me too.

**Comment by gitressa** [comment] 2022-10-10 11:13
It works well for me, with these versions and settings:
```
$ lando version
v3.6.4

$ drush core:status
Drupal version   : 9.4.8
PHP version      : 8.1.10                            
Drush version    : 11.2.1                            
Drupal root      : /app/web                          

# In settings.php
$settings['config_sync_directory'] = '../config/sync';

$ drush config:export
 [notice] The active configuration is identical to the configuration in the export directory (../config/sync).
../config/sync
```

**Comment by mazz0016** [comment] 2022-10-11 12:40
@sylus I did create a little patch with my work-around and put it here: https://gist.githubusercontent.com/mazz0016/cfb1874f40cf862ff40edabe72765dae/raw/9e9bcb033c434be3f194b1015ad64d7f9aae79f9/5260-typeerror-config-export-not-working.patch

The site I am using it on is actually a WxT-based site. I also have a vanilla WxT site that I run locally for testing purposes and I have added it there as well.

After some more investigating, it was realized that the get() function to get the values for `configStorageSync` was running before the set() function was running to assign the value. So I change my workaround to accommodate for this new information. 

EDIT: I have noticed now another issue, but I don't know if it is caused by the patch or not. The issue could have been present before but I didn't notice it as I was always getting the TypeError.

Config needing to be exported from my active config to my `../config/sync` directory does not show any changes. As the condition statement in ConfigExportCommands.php: `if (!$config_comparer->createChangelist()->hasChanges()) {` always validates to false. So if there are some config changes in the active queue that need export, the message that the config is identical will always display.

**Comment by Nasr2013** [comment] 2022-10-13 12:39
I did try the patch - but it doesn't work for me - this command work for me
**drush cex --destination="../config/sync"**
$settings['config_sync_directory'] = '../config/sync'; is defined in setting.php 
**./docker/bin/drush core:status**
Drupal version   : 9.3.22                                
Site URI         : http://default                        
DB driver        : mysql                                 
DB port          : 3306                                  
DB username      : root                                  
DB name          : wxt                                   
Database         : Connected                             
Drupal bootstrap : Successful                            
Default theme    : wxt_bootstrap                         
Admin theme      : claro                                 
PHP binary       : /usr/local/bin/php                    
PHP config       : /usr/local/etc/php/php.ini            
PHP OS           : Linux                                 
PHP version      : 8.0.24                                
Drush script     : /var/www/vendor/drush/drush/drush     
**Drush version    : 11.2.1**                                
Drush temp       : /tmp                                  
Drush configs    : /var/www/vendor/drush/drush/drush.yml 
Install profile  : wxt                                   
Drupal root      : /var/www/html                         
Site path        : sites/default                         
Files, Public    : sites/default/files                   
Files, Temp      : /tmp

**Comment by smulvih2** [comment] 2022-10-17 18:02
@mazz0016's patch worked for me using drush/drush 11.2.1

**EDIT**: Applying the patch fixed the error message I was seeing, but didn't export any config. I was in the middle of updating Drupal WxT (core and a bunch of contrib modules) and after applying this patch and exporting config I was getting "The active configuration is identical to the configuration in the export directory (../config/sync)". After downgrading to drush/drush 11.1.1 and exporting config I get the expected output (400+ config file changes).

**Comment by weitzman** [comment] 2022-10-17 22:42
I wonder if folks did not do a cache:rebuild after upgrading Drush version. Thats needed.

**Comment by DieterHolvoet** [comment] 2022-10-18 09:15
I just tested and after updating from 11.1.1 to 11.2.0, without doing a `drush cr`, I get the following error:
```
 [error]  TypeError: Drush\Drupal\Commands\config\ConfigImportCommands::__construct(): Argument #3 ($configCache) must be of type Drupal\Core\Cache\CacheBackendInterface, Drupal\Core\Config\FileStorage given
```
So I don't think that's going to be the problem.

**Comment by DieterHolvoet** [comment] 2022-10-18 09:38
I'm able to reproduce the issue after following the above steps on a fresh install of the [WxT distribution](https://github.com/drupalwxt/wxt-project). Will report back if I find a fix.

**Comment by DieterHolvoet** [comment] 2022-10-18 10:32
Okay, I found the issue. Because `Drupal\wxt_ext_config\Commands\Wxtcex` ([source](https://github.com/drupalwxt/wxt/blob/4.3.x/modules/custom/wxt_ext/wxt_ext_config)) is extending `Drush\Drupal\Commands\config\ConfigExportCommands`, Drush thinks `Drupal\wxt_ext_config\Commands\Wxtcex` is providing the `config:export` command through `Drupal\wxt_ext_config\Commands\Wxtcex::export` (the method on the parent class).

A workaround would be to rename `Drupal\wxt_ext_config\Commands\Wxtcex::wxtConfigExport` to `Drupal\wxt_ext_config\Commands\Wxtcex::export` to match the parent command method name. This way, the annotation of the parent class is not read and the `Wxtcex` command is not associated with the default config export command.

The real fix IMO would be to consider not reading annotations from parent classes in `Consolidation\AnnotatedCommand\AnnotatedCommandFactory::createCommandInfoListFromClass`.

**Comment by DieterHolvoet** [comment] 2022-10-18 10:34
There's also an issue in the WxT repo on Drupal.org: https://www.drupal.org/project/wxt/issues/3315821

**Comment by DieterHolvoet** [comment] 2022-10-18 10:42
This change in [`consolidation/annotated-command`](https://github.com/consolidation/annotated-command) also fixes the issue. I'd like some feedback before creating a PR there, not sure if this would be the way to go.

```
diff --git a/src/AnnotatedCommandFactory.php b/src/AnnotatedCommandFactory.php
index 0545f60..7406ed0 100644
--- a/src/AnnotatedCommandFactory.php
+++ b/src/AnnotatedCommandFactory.php
@@ -281,11 +281,15 @@ class AnnotatedCommandFactory implements AutomaticOptionsProviderInterface
 
         // Ignore special functions, such as __construct and __call, which
         // can never be commands.
+        $commandClass = get_class($commandFileInstance);
         $commandMethodNames = array_filter(
             get_class_methods($commandFileInstance) ?: [],
-            function ($m) use ($commandFileInstance) {
+            function ($m) use ($commandFileInstance, $commandClass) {
                 $reflectionMethod = new \ReflectionMethod($commandFileInstance, $m);
                 $name = $reflectionMethod->getFileName();
+                if ($reflectionMethod->getDeclaringClass()->getName() !== $commandClass) {
+                    return false;
+                }
                 if ($reflectionMethod->isStatic() || preg_match('#^_#', $m)) {
                     return false;
                 }
```

**Comment by weitzman** [comment] 2022-10-18 10:48
Thanks. Lets see what @greg-1-anderson thinks about that diff

An alternative solution is to add `final` to our command classes like DCG already does https://github.com/drush-ops/drush/issues/5260#issuecomment-1282186102

**Comment by claudiu-cristea** [comment] 2022-10-18 13:37
I just got the error from https://github.com/drush-ops/drush/issues/5260#issuecomment-1282072669 while deploying a new release. So unpleasant.

**Comment by DieterHolvoet** [comment] 2022-10-18 13:47
@claudiu-cristea that's probably because you didn't do a `drush cr` before `drush cim`

**Comment by claudiu-cristea** [comment] 2022-10-18 13:50
@DieterHolvoet don't think so:

```
 [Exec] Running ./vendor/bin/drush deploy --yes
 [notice] Database updates start.
 ----------------- ------------- --------------- ---------------------------
  Module            Update ID     Type            Description
 ----------------- ------------- --------------- ---------------------------
  search_api_solr   8414          hook_update_n   8414 - Configure
                                                  language-specific field
                                                  usage individually per
                                                  index.
  ctools            remove_enti   post-update     Invalidate the service
                    tybundlecon                   container to force
                    straint                       EntityBundleConstriant is
                                                  Removed.
 ----------------- ------------- --------------- ---------------------------

 // Do you wish to run the specified pending updates?: yes.

> >  [notice] Update started: search_api_solr_update_8414
> >  [notice] Update completed: search_api_solr_update_8414
> >  [notice] Update started: ctools_post_update_remove_entitybundleconstraint
> >  [notice] Update completed: ctools_post_update_remove_entitybundleconstraint
>  [success] Finished performing updates.
 [success] Cache rebuild start.
>  [success] Cache rebuild complete.
 [success] Config import start.
+------------+---------------------------------------------------------------------------+-----------+
| Collection | Config                                                                    | Operation |
+------------+---------------------------------------------------------------------------+--------–-+
```

**Comment by DieterHolvoet** [comment] 2022-10-18 13:51
Did it happen at the very start of the `drush deploy` command or did it happen when the command got to the `drush cim` part?

**Comment by claudiu-cristea** [comment] 2022-10-18 13:58
@DieterHolvoet I'm looking now. But normally you should not run anything before `drush deploy` because the database may be very out-of-sync with the code

**Comment by DieterHolvoet** [comment] 2022-10-18 14:00
I'm not saying that, I mean the error, when did that happen. At the very start of the `drush deploy` command or did it happen when the command got to the `drush cim` part. Might be that `drush deploy` fails at the very start when bootstrapping Drupal because a `drush cr` didn't happen yet. But that would be an issue separate from this one.

**Comment by weitzman** [comment] 2022-10-18 14:15
Perhaps this is an instance of https://www.drupal.org/project/drupal/issues/2918906. Drush commands that bootstrap drupal are currently stored as Drupal tagged services (might change in #4685) so they can fall victim to that issue, I think.

**Comment by claudiu-cristea** [comment] 2022-10-18 18:45
@DieterHolvoet I confirm, I had a Drush command just before `drush deploy`:

```
./vendor/bin/drush state:set system.maintenance_mode 1 --input-format=integer –yes
```

Removed and is fixed now

**Comment by weitzman** [comment] 2022-10-18 19:42
Hmmm. I have deploy script that does that too. Lets try to think of a way to survive this.

**Comment by DieterHolvoet** [comment] 2022-10-18 19:42
Doing a `drush cr` before `drush state:set` would work.

**Comment by weitzman** [comment] 2022-10-18 20:47
Yeah, but @alexpott has warned about that  - its not safe.

I see that mass.gov [does its state:set while still using the old codebase](https://github.com/massgov/openmass/blob/develop/drush/Commands/DeployCommands.php#L241-L398) so thats an option for some sites. Another approach is temporarily putting an index.html maintainence page into the codebase (or an alternate index.php front controller).

**Comment by greg-1-anderson** [comment] 2022-10-18 20:50
Annotated command classes are not intended to be extended; the suggested addition in https://github.com/drush-ops/drush/issues/5260#issuecomment-1282186102 would be a welcome change to guard against undesirable side effects when folks try this.

**Comment by claudiu-cristea** [comment] 2022-10-18 21:27
> Doing a `drush cr` before `drush state:set` would work.

@DieterHolvoet 

No drush (or other command involving the database and/or the cache) should be run before `drush deploy` (particularly `drush updb`). Because until hook_update_N() runs, the system is broken. Specifically, there’s new code but the old database. The mission of hook_update_N() is to update the DB (and cache) to be compatible with the new code.

**Comment by weitzman** [comment] 2022-10-19 01:48
To summarize, don't extend command classes and don't run drush commands before a drush updatedb (or drush deploy)

**Closed as completed by weitzman** 2022-10-19 01:48 UTC
Labels: area-config

**Comment by DieterHolvoet** [comment] 2022-10-19 09:49
I created a PR to stop inherited methods from being registered as commands: https://github.com/consolidation/annotated-command/pull/272

**Comment by DieterHolvoet** [comment] 2022-10-20 11:30
This issue was fixed upstream. It should be fixed after running the following command and rebuilding your caches:
```
composer update consolidation/annotated-command
```

**Comment by smulvih2** [comment] 2022-10-20 17:22
Updating consolidation/annotated-command to 4.5.7 fix the issue for me, thanks @DieterHolvoet!!!

**Comment by latden** [comment] 2022-10-20 17:24
great! composer update consolidation/annotated-command is wortking!! thank you!

**Comment by mazz0016** [comment] 2022-10-20 17:25
This command works for me as well. Thank you!
