### ISSUE TITLE
Inconceivable error when the sqlite3 binary is missing

### ISSUE THREAD

**Issue by tstoeckler** [drush-ops/drush#1042] opened 2014-12-08 12:21 UTC
When installing a Drupal site into SQLite and then trying to bootstrap that site with Drush when Drush validates the `DRUSH_BOOTSTRAP_DRUPAL_DATABASE`, `drush_valid_db_credentials()` performs an SQL query which ends up calling the `sqlite3` binary in this case.

If the `sqlite3` binary is not installed, however, this fails and the ever so cryptic
> Drush was not able to start (bootstrap) the Drupal database.

message is displayed. It would be nice to show a more explicit error in this case.

**Comment by jonhattan** [comment] 2015-07-12 12:43
Duplicate of #1371

**Closed by jonhattan** 2015-07-12 12:43 UTC
