### ISSUE TITLE
Drush 9 uli works but leads to an error page

### ISSUE THREAD

**Issue by gaelg** [drush-ops/drush#3044] opened 2017-10-09 15:43 UTC
When calling "drush uli", I am directed to something like http://localdocker:8000/user/reset/1/1507563534/DzFCRbb8G7gZe7p5_xETeeZARInqPK_0MNoVtUHhDhw/login?destination=1

There is "destination=1" in the URL query part, which generates this error:
`Le site Web a rencontré une erreur inattendue. Veuillez essayer de nouveau plus tard.</br></br><em class="placeholder">InvalidArgumentException</em>: The URI &#039;base:1&#039; is invalid. You must use a valid URI scheme. Use base: for a path, e.g., to a Drupal file that needs the base path. Do not use this for internal paths controlled by Drupal. in <em class="placeholder">Drupal\Core\Utility\UnroutedUrlAssembler-&gt;assemble()</em> (line <em class="placeholder">64</em> of <em class="placeholder">core/lib/Drupal/Core/Utility/UnroutedUrlAssembler.php</em>).`

I tried passing a path like "drush uli /node/add" but the destination is still 1.

Anyway, if I go to another page of my site (such as home), I am successfully logged in.

**Comment by greg-1-anderson** [comment] 2017-10-09 15:56
Could you please check and see if this is a duplicate of https://github.com/drush-ops/drush/pull/2868?

**Comment by gaelg** [comment] 2017-10-09 16:24
It's another problem (and somehow bigger because it's "broken", not just "not backward compatible"), but it looks like fixing #2868 would fix this.

**Comment by weitzman** [comment] 2017-10-13 00:55
likely fixed by 3c433fcf89183c600f57fa558b312d7cb2858542

**Closed by weitzman** 2017-10-13 00:55 UTC

**Comment by gaelg** [comment] 2017-10-19 09:25
Yes, it works. Thank you!
