### ISSUE TITLE
Parsing of db-url parameter breaks if # in any field (specifically, password)

### ISSUE THREAD

**Issue by et304383** [drush-ops/drush#2773] opened 2017-05-23 17:29 UTC
https://github.com/drush-ops/drush/blob/master/includes/sitealias.inc#L1680

Just wasted hours trying to figure this out.  Turns out, parse_url doesn't properly handle a URL with a # character contained within.

Drush should handle this since clearly PHP isn't going to fix this.

Tested with Drush 8.1.11 and PHP 5.6

**Comment by weitzman** [comment] 2017-06-05 10:45
Maybe preprocess the url to escape the #?

**Comment by eric-tucker** [comment] 2017-06-05 11:00
I suspect '@' and ':' would also need to be handled.

**Comment by weitzman** [comment] 2022-08-31 10:47
dupe of #1134

**Closed by weitzman** 2022-08-31 10:47 UTC
