### ISSUE TITLE
Running 'drush field-info' and select any of the options returns error

### ISSUE THREAD

**Issue by tadityar** [drush-ops/drush#1080] opened 2015-01-05 02:50 UTC
using 'field-info' command returns an error
if 'types' is selected the error is : Fatal error: Call to undefined function field_info_field_types() in /usr/local/bin/drush/commands/core/field.drush.inc on line 316

if 'fields' is selected the error is : Fatal error: Call to undefined function field_info_fields() in /usr/local/bin/drush/commands/core/field.drush.inc on line 301

**Comment by weitzman** [comment] 2016-04-25 15:40
Dupe of #1194

**Closed by weitzman** 2016-04-25 15:40 UTC
