### ISSUE TITLE
Site aliases not working

### ISSUE THREAD

**Issue by mikeyp** [drush-ops/drush#1241] opened 2015-03-10 01:42 UTC
Site aliases stopped working sometime between 7.0.0-alpha3 and 7.0.0-alpha4. Please see my example output at https://gist.github.com/mikeyp/641f78ef0060cbdb2d74.

I can try to bisect if that would help figure out what caused this regression.

**Comment by mikeyp** [comment] 2015-03-10 01:48
My test breaks at c7ea4b1d8ee29b467b3233b320e779535a9d0b8f.

**Comment by mikeyp** [comment] 2015-03-10 01:50
I wonder if this same issue affected #1237.

**Comment by weitzman** [comment] 2015-03-11 16:21
Drush is at alpha9.

**Comment by mikeyp** [comment] 2015-03-11 17:32
Alpha9 and dev-master were both broken as well when I reported this.

**Comment by mikeyp** [comment] 2015-03-18 18:03
Here's a debug log from today's dev-master https://gist.github.com/mikeyp/87de4235d61187c5360d

**Comment by weitzman** [comment] 2015-03-18 18:31
I see that your alias file is stored at `/Users/mdp/git/example/drupal/sites/default/aliases.drushrc.php'`. Thats no longer supported, as we redispatch to the remote-host before we look into Drupal's site-specific directories. You have to put your site alias files into one of the global locations, and not a site specific one. You could consider sites/all/drush if you want to keep it within drupal's docroot.

**Comment by weitzman** [comment] 2015-03-18 18:34
3. Inside the sites folder of any bootstrapped Drupal site,
    or any local Drupal site indicated by an alias used as
    a parameter to a command

@greg-1-anderson  - should we just remove this from https://github.com/drush-ops/drush/blob/master/examples/example.aliases.drushrc.php#L50

**Comment by mikeyp** [comment] 2015-03-18 18:37
Looks like there's more to it than just documentation, as `drush sa` should not be able to find aliases in the sites folder, but that still works.

**Comment by greg-1-anderson** [comment] 2015-03-18 19:08
I'm cleaning up the Drush bootstrap again.  One thing that bothered me about the symptoms here is that Drush just says "command not found" when it means "maybe I couldn't find the alias, or maybe I couldn't find the command."  It was always clear here that it was the alias that was not found, but the bootstrap was still a little confused around this issue, so I felt it needed cleaning up.

Almost done here; when I get the refactor working, I'll figure out why sa sees the alias that the bootstrap does not.

**Comment by greg-1-anderson** [comment] 2015-03-18 21:23
Okay, the Drush bootstrap cleanup has been committed.  I don't have time to test aliases in sites/default right now; give it a spin on HEAD of master, and see if it works better for you now.

**Closed** 2015-03-25 16:19 UTC

**Comment by MegaChriz** [comment] 2015-04-08 11:43
I think I also experience this issue or at least a similar one. Though with me the commit where things failed is since fbd73501. I found this out using git bisect.

I have a multisite environment with Drupal 7. The site "default" is connected to database "drupal_default" and the site "7311" is connected to database "drupal_7311".
When I go to the root of the Drupal installation and execute this command:
<code>drush use 7311;drush sql-drop</code>
I get this in return:
<code>Do you really want to drop all tables in the database drupal_default? (y/n):</code>
If I say "y", the database drupal_default is emptied, drupal_7311 is not emptied.

Before commit fbd73501 I get this in return instead (expected behaviour):
<code>Do you really want to drop all tables in the database drupal_7311? (y/n):</code>

Contents of sites.php:
<?php
for ($i = 7311; $i <= 7313 ; $i++) {
  $sites[$i . '.192.168.0.203'] = $i;
}
?>

Sites folder structure:
- 7311
  - files
  - settings.php
- all
- default
  - default.settings.php
  - files
  - settings.php
- example.sites.php
- sites.php

I have tried if emptying the ~/.drush folder helped, but it didn't.

I have experienced this issue on multiple computers, all with Mac OS X.

These reported issues look similar: #1302, #1199, #1325

**Comment by greg-1-anderson** [comment] 2015-04-08 14:10
I'm pretty sure that your issue is different than this one, which I am pretty sure was fixed by the commit that closed it.

If you skip `drush use`, and try `drush 7311 sql-drop`, does it work?  If so, please open a new issue.  If not, I'll re-open this one.

**Comment by MegaChriz** [comment] 2015-04-08 15:09
The problem is not with just sql-drop, other commands also operate on the site "default". The issue have could be different though, as I did not work with aliases.drushrc.php (or at least not by my knowledge).

If I enter <code>drush 7311 sql-drop</code> on latest dev of drush I get:
<code>The drush command '7311 sql-drop' could not be found.  Run `drush cache-clear drush` to clear the commandfile cache if you have installed [error]
new extensions.</code>

With drush 7.0.0-alpha8 I get:
<code>Do you really want to drop all tables in the database drupal_7311? (y/n):</code>

The drush constant DRUSH_DRUPAL_SITE keeps being "default". I added a drush command with the following contents to a module:

```php
function drush_mymodule_test() {
  $site = drush_get_context('DRUSH_DRUPAL_SITE', 'none');
  drupal_set_message($site);
}
```
When executing this command after <code>drush use 7311</code> I get the following answer:
<code>default</code>
With drush 7.0.0-alpha8 this is:
<code>7311</code>

I ran <code>composer update --no-dev</code> after checking out the latest drush dev.

Can drush commands provided by contributed Drupal-modules have influence on drush core commands? If so, I can retry with a fresh install of Drupal with no contrib modules enabled.

**Comment by weitzman** [comment] 2015-04-08 15:37
Sorry, I think greg meant `drush --uri=7311 sql-drop`. The --uri is important.

The example here uses a sites.php. Maybe we mucked up support for that in the bootstrap refactor.

**Comment by greg-1-anderson** [comment] 2015-04-08 16:27
No, Drush actually does have a feature where you can use the name of the sites folder as an alias, so `drush 7311 sql-drop` *should* work -- although `drush --uri=7311 sql-drop` or at least `drush #7311 sql-drop` would be better.  I considered dropping support for the sites-folder-name as an alias, and require the '#', but in the end I left it in.

Now, though, as I am reading the error message 2U again, I realize that I did inadvertently mostly disable that feature, because the command dispatcher now expects that a site-alias parameter must start with an '@' or a '#' or look like a site spec.  This cleaned up command dispatching quite a bit.  '7311' is alphanumeric, and no longer fits this mold.  This is probably what broke 'use' as well.

@MegaChriz:  Try `drush #7311 sql-drop` and see if that works.  I think my inclination is to officially remove support for the sitename-is-an-alias feature, and require the --uri or leading '#'.

**Comment by weitzman** [comment] 2015-04-08 18:21
Yes, lets deprecate that syntax. I didn't know about it, nor did I know
about # (which I would be fine with killing as well)

**Comment by MegaChriz** [comment] 2015-04-08 19:22
<code>drush #7311 sql-drop</code> seems to work on latest dev, I get:
<code>Do you really want to drop all tables in the database drupal_7311? (y/n):</code>
<code>drush --uri=7311 sql-drop</code> has the same effect.

Something interesting to note:
With <code>drush use #7311</code> I get <code>Site set to #7311</code> when using Zsh, but <code>Site set to @none</code> when using Bash. <code>drush use 7311</code> gives <code>Site set to 7311</code> for both Zsh and Bash. <code>Site set to @7311</code> gives <code>Could not find a site definition for @7311.</code>. In all cases, the site is not switched to 7311.
I am using Zsh by default.

If I remove the sites.php I notice the same behaviour (at least for the commands <code>drush #7311 sql-drop</code>, <code>drush use 7311</code> and <code>drush use #7311</code>), so I guess the sites.php is not really involved in the process.

On an other multisite I also have a sitename.local and when executing <code>drush use sitename.local</code> drush reported <code>Site set to sitename.local</code>, but the site did not switch.

@weitzman Do you mean with "deprecate that syntax" that <code>drush use [site folder name]</code> is supposed to not work or were you only referring to <code>drush [site folder name] sql-drop</code>?
In case <code>drush use [site folder name]</code> should still be supported, should I now open a new issue for it?

**Comment by greg-1-anderson** [comment] 2015-04-08 20:15
Well, # is a comment character in Bash.  Try `drush use '#7311'`.  As Moshe said above, we'll be removing `drush use 7311` syntax before the next release of Drush 7.x.
