### ISSUE TITLE
Segmentation fault

### ISSUE THREAD

**Issue by illepic** [drush-ops/drush#1095] opened 2015-01-13 04:38 UTC
* Drush 7.0.0-alpha7
* Ubuntu 14.04 x64
* PHP 5.6

Running any Drush command results in the error:

    Segmentation fault
    /usr/bin/drush: 124: [: -le: unexpected operator

The command still appears to run successfully (using mostly for Drush make).

**Comment by illepic** [comment] 2015-01-16 17:15
Updating: on Drush 7.0.0-alpha8 and running `drush cc all` results in:

    $ drush cc all
    zend_mm_heap corrupted
    /usr/bin/drush: 129: [: -le: unexpected operator
    'all' cache was cleared.

**Comment by mkhamash** [comment] 2015-03-15 22:19
You can check this post on [stackoverflow] (http://stackoverflow.com/questions/2247977/what-does-zend-mm-heap-corrupted-mean). 
if the problem was solve by using "USE_ZEND_ALLOC=0" solution, most probably you have something wrong in you PHP-cli config, mine was thet xdebug autostart even in cli mode.

**Comment by weitzman** [comment] 2015-05-18 16:51
Dupe of #1378

**Closed by weitzman** 2015-05-18 16:51 UTC
