### ISSUE TITLE
hook_init has a different bootstrap level for global commands and module commands

### ISSUE THREAD

**Issue by joachim-n** [drush-ops/drush#3058] opened 2017-10-11 15:20 UTC
I've been running my command as a module command to get around #2918, and it's been working ok.

Now I'm testing the PR to fix that issue, https://github.com/drush-ops/drush/pull/3052, and my command crashes.

The reason is that my call to drush_drupal_version() in my command's hook_init gets a FALSE, where before it got a version number.

Here's some test code:

```
  /**
   * Test hello.
   *
   * @command cb-hi
   * @bootstrap DRUSH_BOOTSTRAP_DRUPAL_FULL
   */
  public function commandHi() {
    dump(drush_drupal_version());
    dump('hello!');
  }

  /**
   * Initialize Drupal Code Builder before a command runs.
   *
   * @hook init cb-hi
   */
  public function initHi() {
    dump(drush_drupal_version());
    dump('init');
  }
```

The output running that as a global command is is:

```
false
"init"
"8.4.0-dev"
"hello!"
```

Whereas if running as a module command, the Drupal core version number would be output both times.

**Comment by greg-1-anderson** [comment] 2017-10-11 15:28
Add a `@bootstrap full` annotation to your command(s).

**Comment by joachim-n** [comment] 2017-10-11 15:30
Same result.

I already had

```
    * @bootstrap DRUSH_BOOTSTRAP_DRUPAL_FULL
```

-- isn't that the same thing?

**Comment by greg-1-anderson** [comment] 2017-10-11 15:45
Run with `--debug` and see if the bootstrap hook is being called. Does `drush status` show that your database is connected?

**Comment by greg-1-anderson** [comment] 2017-10-11 15:59
@joachim-n Oh, wait, sorry, you are talking explicitly about @hook init. Bootstrapping happens as part of hook init (unless your command is part of a module - as modules commands are not discovered until bootstrap full).

If you'd like your init hook to have access to the bootstrapped site, use `@hook post-init`.

Maybe we could alter things so that the bootstrap hook happens at the end of pre-init (or the very beginning of the init hook, before all other hooks). That might produce more intuitive results. However, there currently isn't any way to order hooks within a phase. Add an "after-pre" phase? 😛 That's probably too much.

**Comment by joachim-n** [comment] 2017-10-11 19:18
> Maybe we could alter things so that the bootstrap hook happens at the end of pre-init (or the very beginning of the init hook, before all other hooks).

That might be an idea.

At the moment, specifying ```@bootstrap full``` for a command doesn't actually mean the same thing in the code for a global or a module command, which is a bit of an inconsistency in the API for commands.

**Comment by weitzman** [comment] 2017-10-12 00:33
Closing. Please post here if this needs re-opening.

**Closed by weitzman** 2017-10-12 00:33 UTC

**Comment by joachim-n** [comment] 2017-10-12 06:46
I think it does -- there is an inconsistency in the API.

If I have a command in a module that uses ```@bootstrap full``` and has a hook_init, and try to copy that code to a command in a global location with the same bootstrap level, then that code will fail. That goes against developer expectations.

**Comment by greg-1-anderson** [comment] 2017-10-12 14:17
@joachim-n Sorry, that is by design and cannot be fixed. Note that in Drush 8 an earlier, the behavior of your command hooks vary based on the bootstrap level, and module commands were discovered during bootstrap full as well, so nothing has really changed.

We could clarify the documentation a bit, though. Docs PRs welcome.
