### ISSUE TITLE
Empty --idList resets all source_row_status values to STATUS_NEEDS_UPDATE

### ISSUE THREAD

**Issue by DrColossos** [drush-ops/drush#4749] opened 2021-05-07 08:41 UTC
**Describe the bug**
If no --idList parameter is provided, handleMissingSourceRows() kicks in because it checks for an empty "$this->idlist". Since none was provided, it resets all source row states to  MigrateIdMapInterface::STATUS_NEEDS_UPDATE. This defeats the purpose of track_changes as well as the "--update" option.  

**To Reproduce**
Run a regular migration. Note that the source_row_status was properly set to "0" inside the DB. Run a migration without any additional parameters.

**Expected behavior**
Only changed rows should be updated because of track_changes: true and no --update option provided

**Actual behavior**
The whole migration table gets update to source_row_status="1!

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.4.2
| Drupal version? | 9.0.7
| PHP version     | 7.4
| OS?             | Linux

**Additional information**
While using migrate_tools, this behavior was not observed. Might also be related to #4743 with the slow process

**Comment by vaish** [comment] 2021-05-07 10:11
This is duplicate of #4750. `--idlist` option is not really required to reproduce this bug.

**Comment by claudiu-cristea** [comment] 2021-06-19 09:20
This has been fixed in #4750

**Closed by claudiu-cristea** 2021-06-19 09:20 UTC
Labels: area-migrate
