### ISSUE TITLE
Notice: Undefined variable: translationOptions in LocaleCommands.php

### ISSUE THREAD

**Issue by MPParsley** [drush-ops/drush#3722] opened 2018-10-11 12:34 UTC
**Describe the bug**
A notice appears during `drush locale:update`.

**To Reproduce**
drush locale:update

**Expected behavior**
No notice

**Actual behavior**
Notice: Undefined variable: translationOptions in vendor/drush/drush/src/Drupal/Commands/core/LocaleCommands.php on line 92

**Workaround**
-

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.4
| Drupal version? | 8.6
| PHP version     | 7.2
| OS?             | Mac

**Additional information**
This also causes a Warning:
Warning: session_id(): Cannot change session id when headers already sent in /vendor/symfony/http-foundation/Session/Storage/Proxy/AbstractProxy.php on line 94

**Comment by greg-1-anderson** [comment] 2018-10-11 18:22
You're using [locale:check](https://github.com/drush-ops/drush/blob/9.4.0/src/Drupal/Commands/core/LocaleCommands.php#L45)?

**Comment by greg-1-anderson** [comment] 2018-10-11 18:47
Posted that on the wrong issue. Can't reproduce this. Provide steps to reproduce from a fresh install.

**Comment by weitzman** [comment] 2018-10-15 13:04
Closed via #3723

**Closed by weitzman** 2018-10-15 13:04 UTC
