### ISSUE TITLE
Run Drush by PHP CLI Interpreter and one specific PHP setting (enabling Xdebug)

### ISSUE THREAD

**Issue by jepster** [drush-ops/drush#4528] opened 2020-08-14 08:19 UTC
**Describe the bug**
I am searching for a possibility to run Drush in an isolated PHP process with Xdebug enabled. Currently I must enable Xdebug in my php.ini file. That influences all my PHP processes. But I would like to run the Drush PHP process with just one specific PHP setting like I am able with PHPUnit. E.g.:

```
/bin/php -d xdebug.remote_enable=true phpunit
```
The above command enables Xdebug for just one PHP process. This is currently not possible with Drush. I am wondering so much about that, because Drush needs the PHP cli for being run.

I have also tried the DRUSH_PHP environment variable, but that is too global. I would like just to pass one PHP setting to the Drush PHP process.

Question: Is there any possibility to run Drush by the PHP CLI interpreter with one specific PHP setting? A quick way for enabling/disabling Xdebug is important for PHP developers.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 9.7.2
| Drupal version? | 8.8
| PHP version     | 7.3
| OS?             | Mac

**Comment by greg-1-anderson** [comment] 2020-08-14 14:06
Duplicate of #4529

**Closed by greg-1-anderson** 2020-08-14 14:06 UTC
