### ISSUE TITLE
Allow drush make to generate compiled and/or updated makefiles

### ISSUE THREAD

**Issue by ergonlogic** [drush-ops/drush#53] opened 2013-09-01 22:19 UTC
Summary
-------

The patch below basically adds three options to the 'make' command:

**--generate**: Generate a makefile, based on the one passed in, with all versions resolved.
**--generate-update**: Generate an updated makefile, based on the one passed in, with all versions updated.
**--no-build**: Do not build a codebase. Makes the `build path` argument optional.

The first two default to printing to the terminal, but an output file may be specified. The last option allows these options to operate on makefiles without executing an actual build.

Examples
---------

**drush make example.make example --generate=compiled.make**

Create a 'snapshot' makefile (compiled.make) with the versions that were actually used in building the codebase.

**drush make example.make --generate-update --no-build**

Output an updated makefile to the terminal, without building a codebase, based on the source makefile (example.make).

Background & Patch
---------------------

See these two issues from drupal.org for the back-story:
 * [Issue #1212686: Create a versioned make file when running drush make with option --make-generate](https://drupal.org/node/1212686)
 * [Issue #1325818: Generate an upgrade makefile from an existing makefile?](https://drupal.org/node/1325818)

The latest patch that includes the changes from both issues is: https://drupal.org/files/drush-versioned_updated_makefiles-1325818-10.patch

**Comment by weitzman** [comment] 2015-01-06 03:21
dupe of #660 which has been merged.

**Closed by weitzman** 2015-01-06 03:21 UTC
