### ISSUE TITLE
drush.yml isn't discovered in web/sites/default/drush.yml

### ISSUE THREAD

**Issue by gitressa** [drush-ops/drush#4324] opened 2020-02-15 10:06 UTC
According to [example.drush.yml](https://github.com/drush-ops/drush/blob/master/examples/example.drush.yml) it should be possible to add a `drush.yml` file these locations:
```
# Directories and Discovery
#
# Rename this file to drush.yml and copy it to one of the places listed below
# in order of precedence:
#
# 1.  Drupal site folder (e.g. sites/{default|example.com}/drush.yml).
# 2.  Drupal /drush and sites/all/drush folders, or the /drush folder
#       in the directory above the Drupal root.
# 3.  In any location, as specified by the --config (-c) option.
# 4.  User's .drush folder (i.e. ~/.drush/drush.yml).
# 5.  System wide configuration folder (e.g. /etc/drush/drush.yml or C:\ProgramData\Drush\drush.yml).
```
I would prefer to use the first option, by simply adding a file to an existing folder, but it doesn't seem to work:
- `web/sites/default/drush.yml`

These work:
- `drush/drush.yml`
- `web/sites/all/drush/drush.yml`

**To Reproduce**
Add a `web/sites/default/drush.yml` file, which isn't discovered.

### System Configuration
| Q               | A
| --------------- | ---
| Drush version  | 9.7.2
| Drupal version | 8.8.2
| PHP version     | 7.2.24
| OS             | Ubuntu with Lando

**Comment by gitressa** [comment] 2020-02-15 10:33
The same happens with `Drush` 10.2.1.

**Comment by weitzman** [comment] 2020-02-15 13:13
Can you try a bit more nesting such as `sites/d8/drush/drush.yml`? Thats what I see at https://github.com/drush-ops/drush/blob/c7f062b2519242d5eb95302b854d106245d39480/tests/unit/ConfigLocatorTest.php#L37

**Comment by gitressa** [comment] 2020-02-15 16:25
I get the same result, i.e. it also doesn't register at `web/sites/default/drush/drush.yml` ...
Also, I should add that the content of my `drush.yml` is created dynamically via a script, so to keep it simple I would much prefer to not have to create a directory, which is why I prefer putting it in `web/sites/default`, since that folder already exists.

**Comment by richardbporter** [comment] 2020-03-04 14:30
I've tried both `default/drush.yml` and `default/drush/drush.yml` and neither seem to work.

**Comment by richardbporter** [comment] 2020-03-04 14:36
There is a comment in ConfigLocator related to multisite: https://github.com/drush-ops/drush/blob/master/src/Config/ConfigLocator.php#L109

Is that related?

**Comment by gitressa** [comment] 2020-03-04 16:48
You have probably already seen it @richardbporter, but there is further discussion in #4325.

**Comment by richardbporter** [comment] 2020-03-05 15:52
This seems like a duplicate of #3968.

**Comment by gitressa** [comment] 2020-03-05 16:25
Except that this issue is not about multisite. But if fixing #3968 enables `web/sites/default/drush.yml` in single sites as a side-effect, count me in :-)

**Comment by weitzman** [comment] 2020-03-05 19:03
I just noticed that the ConfigLocatorTest mentioned above is a Unit test and as such it doesnt really prove much for loading a config file from a drupal multisite. So, its likely that this has never worked, and the docs should be adjusted.

**Comment by greg-1-anderson** [comment] 2020-03-05 19:14
Correct, this has never worked in Drush9+. I believe it works for drushrc.php in Drush 8 (but I don't use multisite, though, so my memory is only going to be so good on this)

**Closed** 2021-01-19 14:40 UTC

**Comment by weitzman** [comment] 2021-01-19 14:43
Sorry, its not fixed. I updated the docs. Actually making this work is stuck in #4345
