### ISSUE TITLE
Allow other packages to use the integration test helper classes

### ISSUE THREAD

**Issue by Sweetchuck** [drush-ops/drush#3961] opened 2019-03-03 11:41 UTC
As a Drush command developer I also want to write _integration_ tests for commands.

There are helper class under `tests/unish/` directory,
and I can reach them if I add the following lines to my `composer.json`
```json
{
    "require-dev": {
        "drush/drush": "dev-master#9.6.0-rc3"
    },
    "autoload-dev": {
        "psr-4": {
            "Unish\\": "vendor/drush/drush/tests/unish/"
        }
    }
}
```
But the problem is that a lot of thing is hard-coded and impossible to override them, because the `self::` keyword is used instead of `static::`, or the _private_ access modifier is used.

The hard-coded things are the following:
* Path to composer root
* Path to web root
* Path to Drush executable
* path to Git executable
* List of global options (--simulate, --root, --uri etc...)
* Multi value options can appear only once. (--include --config)
* etc ...

**Comment by greg-1-anderson** [comment] 2019-03-03 14:30
I am -1 on Drush extensions reaching inside Drush and using its test code. I know devel does this.

I'd prefer to see DrushTestTraits that extensions could include and use on their own. See [example-drush-extension](https://github.com/drush-ops/example-drush-extension), in progress. The test traits there need a little work before they can be extracted and re-used, but I think they are close. Perhaps you could help out there?

Ideally, Drush could use the same traits. I don't remember if I have come across any reason why that  would be inconvenient.

**Comment by weitzman** [comment] 2019-03-03 14:57
Dupe of #3530. I'd like to see this come to fruition as greg describes.

**Closed by weitzman** 2019-03-03 14:57 UTC

**Comment by Sweetchuck** [comment] 2019-03-03 16:37
You don't have to encourage others to use the testing environment this way, but at least do not close the door until there is no another option.

**Comment by greg-1-anderson** [comment] 2019-03-03 17:58
Your PR is still open. We tend to not keep all the duplicate issues open in this queue while work is in progress.
