### ISSUE TITLE
Drupal 8: sql-conf returns an array instead of a string

### ISSUE THREAD

**Issue by colans** [drush-ops/drush#1869] opened 2015-12-16 17:41 UTC
Drush is reading the database configuration prefix as an array, not a string.

This is causing several Drush operations to fail because the array index is set (as an array) when it shouldn't be.  So Drush assumes that there is a prefix, and we end up with extra "{}" around table names in SQL.  This causes a syntax error.

Known operations affected:
* drush sql-conf
* drush sql-sanitize
* drush [sql-sync-pipe](https://www.drupal.org/project/drush_sql_sync_pipe) --sanitize (see [Fix --sanitize option](https://www.drupal.org/node/2537146))

For example, with the following in settings.(local.)?php:

```php
$databases['default']['default'] = array(
  ...
  'prefix' => '',
  ...
);
```

... or leaving out "prefix" entirely, `drush sql-conf` returns:

```php
Array
(
    [driver] => mysql
    [database] => DATABASE
    [username] => USER
    [host] => localhost
    [port] => 
    [prefix] => Array
        (
            [default] => 
        )

)
```

If "prefix" is set, you get:

```php
Array
(
    [driver] => mysql
    [database] => DATABASE
    [username] => USER
    [host] => localhost
    [port] => 
    [prefix] => Array
        (
            [default] => foo
        )

)
```

... instead of a string.

This is not a problem with Drush 8 on sites running Drupal 7.  It only happens on D8 sites.

**Comment by colans** [comment] 2015-12-16 17:47
So if I run `drush --verbose --debug sql-sanitize`, I get `UPDATE {users_field_data} SET ...` which of course comes back with:

`ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MySQL server version for the right syntax to use near `'} SET pass = ...'`

**Comment by greg-1-anderson** [comment] 2015-12-17 17:03
I have not looked into this, but perhaps the underlying definition of `prefix` has changed in Drupal 8. I believe Drush is probably just passing on what Drupal gives us.

If I recall correctly, the format you show above has always been valid, at least since Drupal 6, for some complex usage of prefix (table sharing), with a string prefix being just a shorthand. Code that deals with prefixes should therefore always work with the array format.  Yes, that includes Drush; however, Drush has never been really great with prefix support, mostly due to lack of interest.  Pull requests to fix Drush sql-sanitize to work with prefixes in array format would be welcome; I don't think we should try to convert prefix arrays back to strings, though.

**Comment by weitzman** [comment] 2015-12-19 02:09
The output in your example looks correct to me as well. Please post steps to reproduce the bug, including --verbose output and your $databases array and drupal version.

**Comment by gchaix** [comment] 2015-12-21 17:52
This issue reproduces reliably for me when running `drush sql-sanitize` on Drupal 8.0.1 and  Drush 8.1-dev.

$databases array:
```
$databases['default']['default'] = array (
  'database' => 'vagrant',
  'username' => 'vagrant',
  'password' => 'vagrant',
  'prefix' => '',
  'host' => 'localhost',
  'port' => '3306',
  'namespace' => 'Drupal\\Core\\Database\\Driver\\mysql',
  'driver' => 'mysql',
);
```

```
[vagrant@vagrant-multi1 default]$ drush status
 Drupal version             :  8.0.1
 Site URI                   :  http://default
 Database driver            :  mysql
 Database hostname          :  localhost
 Database port              :  3306
 Database username          :  vagrant
 Database name              :  vagrant
 Drupal bootstrap           :  Successful
 Drupal user                :
 Default theme              :  bartik_tag1
 Administration theme       :  seven
 PHP executable             :  /usr/bin/php
 PHP configuration          :  /etc/php.ini
 PHP OS                     :  Linux
 Drush script               :  /home/vagrant/.composer/vendor/drush/drush/drush.php
 Drush version              :  8.1-dev
 Drush temp directory       :  /tmp
 Drush configuration        :
 Drush alias files          :
 Install profile            :  standard
 Drupal root                :  /var/www/vagrant-multi1.tag1consulting.com
 Site path                  :  sites/default
 File directory path        :  sites/default/files
 Temporary file directory   :  /tmp
 path
 Sync config path           :  sites/default/files/config_RVLS1fyf14mG6lDA-JwIFSGCn
                               _jyHPAFGCl1ADVP7j4Xdh2w5GRWFRQo9ketO-dOXPJi8KgVwg/sy
                               nc
```


```
[vagrant@vagrant-multi1 default]$ drush sql-sanitize --debug --verbose
Using the Drush script found at /home/vagrant/.composer/vendor/drush/drush/drush.launcher using pcntl_exec
Drush preflight prepare loaded autoloader at                         [preflight]
/home/vagrant/.composer/vendor/autoload.php [0.01 sec, 2.88 MB]
Starting Drush preflight. [0.01 sec, 2.88 MB]                            [preflight]
Cache HIT cid: 8.1-dev-commandfiles-0-b4175ec541a5b0457a6af1fda10b4559       [debug]
[0.01 sec, 2.95 MB]
Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.03 sec,       [debug]
5.61 MB]
Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [0.03 sec,     [debug]
5.62 MB]
Scanning into /home/vagrant/.composer/vendor/drush/drush/includes/.. for     [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.03 sec, 5.62 MB]
Scanning into /home/vagrant/.composer/vendor/drush/drush/includes/.. for     [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.03 sec, 5.62 MB]
Scanning into /home/vagrant/.drush for /.*aliases\.drush(8|)rc\.php$/        [debug]
[0.03 sec, 5.62 MB]
Scanning into /home/vagrant/.drush for /self\.alias\.drush(8|)rc\.php$/      [debug]
[0.03 sec, 5.62 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/../drush for        [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.03 sec, 5.62 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/../drush for        [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.03 sec, 5.62 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/drush for           [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.03 sec, 5.62 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/drush for           [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.03 sec, 5.62 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/all/drush     [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.03 sec, 5.63 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/all/drush     [debug]
for /self\.alias\.drush(8|)rc\.php$/ [0.03 sec, 5.63 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/default       [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.03 sec, 5.63 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/default       [debug]
for /self\.alias\.drush(8|)rc\.php$/ [0.03 sec, 5.63 MB]
Bootstrap to phase 0. [0.12 sec, 7.83 MB]                                [bootstrap]
Bootstrap to phase -1. [0.12 sec, 7.84 MB]                               [bootstrap]
Found command: sql-sanitize (commandfile=sql) [0.12 sec, 7.84 MB]        [bootstrap]
Calling hook drush_sql_sanitize [0.12 sec, 7.88 MB]                          [debug]
Drush bootstrap phase : bootstrap_drupal_root() [0.13 sec, 8.57 MB]      [bootstrap]
Initialized Drupal 8.0.1 root directory at                               [bootstrap]
/var/www/vagrant-multi1.tag1consulting.com [0.13 sec, 8.57 MB]
Find command files for phase 1 (max=3) [0.14 sec, 6.38 MB]                   [debug]
Cache HIT cid: 8.1-dev-commandfiles-1-9ef9465878c909454e6d0febe4a9a351       [debug]
[0.14 sec, 6.38 MB]
Scanning into /etc/drush for /.*aliases\.drush(8|)rc\.php$/ [0.14 sec,       [debug]
6.47 MB]
Scanning into /etc/drush for /self\.alias\.drush(8|)rc\.php$/ [0.14 sec,     [debug]
6.47 MB]
Scanning into /home/vagrant/.composer/vendor/drush/drush/includes/.. for     [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /home/vagrant/.composer/vendor/drush/drush/includes/.. for     [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /home/vagrant/.drush for /.*aliases\.drush(8|)rc\.php$/        [debug]
[0.14 sec, 6.48 MB]
Scanning into /home/vagrant/.drush for /self\.alias\.drush(8|)rc\.php$/      [debug]
[0.14 sec, 6.48 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/../drush for        [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/../drush for        [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/drush for           [debug]
/.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/drush for           [debug]
/self\.alias\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/all/drush     [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 6.48 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/all/drush     [debug]
for /self\.alias\.drush(8|)rc\.php$/ [0.14 sec, 6.49 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/default       [debug]
for /.*aliases\.drush(8|)rc\.php$/ [0.14 sec, 6.49 MB]
Scanning into /var/www/vagrant-multi1.tag1consulting.com/sites/default       [debug]
for /self\.alias\.drush(8|)rc\.php$/ [0.14 sec, 6.49 MB]
Drush bootstrap phase : bootstrap_drupal_site() [0.15 sec, 7.38 MB]      [bootstrap]
Initialized Drupal site default at sites/default [0.15 sec, 7.38 MB]     [bootstrap]
Find command files for phase 2 (max=3) [0.15 sec, 7.38 MB]                   [debug]
Cache HIT cid: 8.1-dev-install_profile-66ecfeb9791a023150773849f1550c5d      [debug]
[0.15 sec, 7.39 MB]
Cache HIT cid: 8.1-dev-commandfiles-2-4b61ef228a19df5ad80d17078b12eaa6       [debug]
[0.15 sec, 7.39 MB]
Drush bootstrap phase : bootstrap_drupal_configuration() [0.16 sec, 7.39 [bootstrap]
MB]
Find command files for phase 3 (max=3) [0.16 sec, 7.63 MB]                   [debug]
Backend invoke: /usr/bin/php                                               [command]
/home/vagrant/.composer/vendor/drush/drush/drush.php --php=/usr/bin/php
--backend=2 --verbose --debug
--root=/var/www/vagrant-multi1.tag1consulting.com --uri=default  sql-conf
  --all 2>&1 [0.24 sec, 9.96 MB]
/usr/bin/php /home/vagrant/.composer/vendor/drush/drush/drush.php           [notice]
--php=/usr/bin/php  --backend=2 --verbose --debug
--root=/var/www/vagrant-multi1.tag1consulting.com --uri=default  sql-conf
  --all 2>&1 [0.24 sec, 9.97 MB]
sql-query: SELECT 1; [0.45 sec, 10.14 MB]                                   [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_UE36av --database=vagrant --host=localhost --port=3306 --silent  < /tmp/drush_N0tKWG
  1
sql-query: SHOW TABLES; [0.46 sec, 10.14 MB]                                [notice]
Executing: mysql --defaults-extra-file=/tmp/drush_lf2QG7 --database=vagrant --host=localhost --port=3306 --silent  < /tmp/drush_Yw2Xqj
  batch
  block_content
  block_content__body
  block_content__field_images
  block_content_field_data
  block_content_field_revision
  block_content_revision
  block_content_revision__body
  block_content_revision__field_images
  cache_bootstrap
  cache_config
  cache_container
  cache_data
  cache_default
  cache_discovery
  cache_dynamic_page_cache
  cache_entity
  cache_menu
  cache_render
  cache_rest
  cache_toolbar
  cachetags
  comment
  comment__comment_body
  comment_entity_statistics
  comment_field_data
  config
  config_snapshot
  content_access
  file_managed
  file_usage
  flood
  history
  key_value
  key_value_expire
  menu_link_content
  menu_link_content_data
  menu_link_content_data_2
  menu_tree
  node
  node__body
  node__comment
  node__field_blog_comments
  node__field_blog_tags
  node__field_comments
  node__field_files
  node__field_image
  node__field_images
  node__field_tags
  node__field_teaser_image
  node_access
  node_field_data
  node_field_revision
  node_revision
  node_revision__body
  node_revision__comment
  node_revision__field_blog_comments
  node_revision__field_blog_tags
  node_revision__field_comments
  node_revision__field_files
  node_revision__field_image
  node_revision__field_images
  node_revision__field_tags
  node_revision__field_teaser_image
  queue
  router
  search_dataset
  search_index
  search_total
  semaphore
  sequences
  sessions
  shortcut
  shortcut_field_data
  shortcut_set_users
  taxonomy_index
  taxonomy_term_data
  taxonomy_term_field_data
  taxonomy_term_hierarchy
  url_alias
  user__field_bio
  user__field_display_weight
  user__field_drupal_org_username
  user__field_first_name
  user__field_full_name
  user__field_hide_from_staff_page
  user__field_job_title
  user__field_last_name
  user__field_twitter
  user__roles
  user__user_picture
  users
  users_data
  users_field_data
  watchdog
Drush bootstrap phase : bootstrap_drupal_database() [0.48 sec, 10.16 MB] [bootstrap]
Successfully connected to the Drupal database. [0.48 sec, 10.16 MB]      [bootstrap]
Find command files for phase 4 (max=) [0.48 sec, 7.84 MB]                    [debug]
Drush bootstrap phase : bootstrap_drupal_full() [0.48 sec, 7.85 MB]      [bootstrap]
Cache HIT cid: 8.1-dev-install_profile-66ecfeb9791a023150773849f1550c5d      [debug]
[0.53 sec, 15.72 MB]
Find command files for phase 5 (max=) [0.53 sec, 15.72 MB]                   [debug]
Cache HIT cid: 8.1-dev-install_profile-66ecfeb9791a023150773849f1550c5d      [debug]
[0.53 sec, 15.72 MB]
Cache HIT cid: 8.1-dev-commandfiles-5-d90f78ffc8ab21754660bea868fb2b58       [debug]
[0.54 sec, 16.98 MB]

The following operations will be done on the target database:
  * Reset passwords and email addresses in {users_field_data} table
  * Truncate Drupal's sessions table

Do you really want to sanitize the current database? (y/n): y
sql-query: UPDATE {users_field_data} SET pass =                             [notice]
'$S$EIcSPS2n7FHjmobR0xAeVW/2XJUDrhS66x5dzlsRqw8VkHS8tUl1', mail =
concat('user+', uid, '@localhost.localdomain'), init = concat('user+',
uid, '@localhost.localdomain') WHERE uid > 0; TRUNCATE TABLE {sessions};
[17.38 sec, 17.04 MB]
Executing: mysql --defaults-extra-file=/tmp/drush_Hgtdge --database=vagrant --host=localhost --port=3306 --silent  < /tmp/drush_j4rvYF
  ERROR 1064 (42000) at line 1: You have an error in your SQL syntax; check the manual that corresponds to your MariaDB server version for the right syntax to use near '} SET pass = '$S$EIcSPS2n7FHjmobR0xAeVW/2XJUDrhS66x5dzlsRqw8VkHS8tUl1', mail = c' at line 1
Returned from hook drush_sql_sanitize [17.39 sec, 17.02 MB]                  [debug]
Command dispatch complete [17.39 sec, 16.99 MB]                             [notice]
Undefined index: memory Logger.php:109 [17.8 sec, 36.52 MB]                 [notice]
Cron run completed. [16.81 sec,  bytes]                                     [notice]
[vagrant@vagrant-multi1 default]$
```

**Comment by jeffsheltren** [comment] 2016-03-23 17:39
I committed bf2d905 to my fork which handles the D8 prefix correctly (```$databases['default']['default']['prefix']['default']``` instead of ```$databases['default']['default']['prefix']```). @weitzman and/or @greg-1-anderson I'd appreciate your review/thoughts.  Let me know if you'd prefer I submit a separate PR.  Would love to get this fixed so we can have a working sql-sanitize for D8 sites. Thanks!

**Comment by weitzman** [comment] 2016-03-24 19:16
I'm not sure what that commit achieves. It defines a variable $db_prefix but I dont see where that is used. Perhaps there is more logic in another commit?

**Comment by jeffsheltren** [comment] 2016-03-24 19:18
Thanks for taking a look.  This is replacing the check on ```!empty($databases['default']['default']['prefix'])``` with a check on ```!empty($db_prefix)``` (line 638 of the new file).

**Comment by weitzman** [comment] 2016-03-24 19:21
Ah right. I see it now. Thanks.

I think we need to factor out the db_prefix checking and review other places in drush that may do it the old way. Sorry to expand the scope but thats the best way to proceed.

**Comment by jeffsheltren** [comment] 2016-03-24 19:23
If I were to try to submit a patch for this, are you looking for function that will return the site's DB prefix, and replace each instance of hard-coded ```$databases['default']['default']['prefix']``` with that function?

**Comment by weitzman** [comment] 2016-03-24 19:29
Off the top of my head, I think we need getPrefix() and hasPrefix() methods on \Drush\Sql\SqlBase and replace existing code accordingly.

**Comment by weitzman** [comment] 2016-03-24 19:30
Actually, those method might go better on the \Drush\Sql\SqlVersion subclasses.

**Closed** 2016-03-29 14:27 UTC
Labels: area-sql, drupal8, stat-needs-work
