### ISSUE TITLE
Drush cex works, but drush cim show "deleted" all configurations

### ISSUE THREAD

**Issue by albertoperezdosaula** [drush-ops/drush#4701] opened 2021-03-23 09:08 UTC
**Describe the bug**
If we export the configuration, it works fine, but if after we run "drush cim" with the configuration exported, then appears deleted all files. I dont know the reason... I never have seen this in Drupal.

Related issue: #3291 

`drush cim
...
|            | system.mail        | Delete    |
|            | system.logging     | Delete    |
|            | system.image.gd    | Delete    |
|            | system.image       | Delete    |
|            | system.file        | Delete    |
|            | system.diff        | Delete    |
|            | system.date        | Delete    |
|            | system.cron        | Delete    |
|            | system.authorize   | Delete    |
`

### System Configuration
| Q               | A
| --------------- | ---
| Drush version?  | 10.3.6
| Drupal version? | 8.9.13
| PHP version     | 7.x,5.x
| OS?             | Linux

**Comment by weitzman** [comment] 2021-03-29 20:06
Looks like a duplicate of #3291

**Closed by weitzman** 2021-03-29 20:06 UTC
