### ISSUE TITLE
Drush super slow with big files directory

### ISSUE THREAD

**Issue by Schnitzel** [drush-ops/drush#1544] opened 2015-08-09 19:17 UTC
With https://github.com/drush-ops/drush/pull/1480 in, drush now searches recursively for an alias file also in sites/default, where the files directory is as well, which can be huge.

This happens here:
`sites/default` as a possible directory: https://github.com/drush-ops/drush/pull/1480/files#diff-7fa60dcfe6be9c85f3682fccc9d87899R417
And recursion: https://github.com/drush-ops/drush/pull/1480/files#diff-7fa60dcfe6be9c85f3682fccc9d87899R632

Drush got on some sites because of that around 50x slower, with an strace I can see that drush makes an lstat() for every file in the directory.

**Comment by Schnitzel** [comment] 2015-08-09 19:17
pull request was: https://github.com/drush-ops/drush/pull/1480

**Comment by weitzman** [comment] 2015-08-09 19:41
Dupe of #1537

**Closed by weitzman** 2015-08-09 19:41 UTC
